/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Api
 * Piccolo TPV API
 * OpenAPI spec version: 0.2.0
 */
export interface TimeclockEmployeeBrief {
  id: string;
  name: string;
}

/**
 * Mobile clock is fail-closed; mobileClockEnabled is always false at runtime
 */
export interface TimeclockMobileClockStatus {
  mobileClockEnabled: boolean;
  configuredMobileClockEnabled: boolean;
  reason: string;
}

export type TimeclockEmployeeStatusStatus = typeof TimeclockEmployeeStatusStatus[keyof typeof TimeclockEmployeeStatusStatus];


export const TimeclockEmployeeStatusStatus = {
  out: 'out',
  in: 'in',
  break: 'break',
} as const;

export type TimeclockRecordSource = typeof TimeclockRecordSource[keyof typeof TimeclockRecordSource];


export const TimeclockRecordSource = {
  pin: 'pin',
  nfc: 'nfc',
  manual: 'manual',
  anviz: 'anviz',
  import: 'import',
} as const;

export interface TimeclockRecord {
  id: string;
  employeeId: string;
  clockIn: string;
  clockOut?: string | null;
  source: TimeclockRecordSource;
  isManual: boolean;
  notes?: string | null;
  createdAt: string;
  updatedAt: string;
  createdBy?: string | null;
  importHistoryId?: string | null;
  importRowId?: string | null;
  externalRecordId?: string | null;
  deviceId?: string | null;
}

export interface TimeclockBreak {
  id: string;
  recordId: string;
  breakStart: string;
  breakEnd?: string | null;
  createdAt: string;
}

export interface TimeclockEmployeeStatus {
  status: TimeclockEmployeeStatusStatus;
  record?: TimeclockRecord | null;
  activeBreak?: TimeclockBreak | null;
}

export type PublicClockInputAction = typeof PublicClockInputAction[keyof typeof PublicClockInputAction];


export const PublicClockInputAction = {
  clock_in: 'clock_in',
  clock_out: 'clock_out',
  break_start: 'break_start',
  break_end: 'break_end',
} as const;

export interface PublicClockInput {
  employeeId: string;
  action: PublicClockInputAction;
  /** @minLength 1 */
  deviceToken: string;
  /** @minLength 32 */
  proof: string;
}

export interface TimeclockClockResult {
  success: boolean;
  record?: TimeclockRecord;
  break?: TimeclockBreak;
  serverTime: string;
}

export interface ErrorResponse {
  error: string;
}

export interface NfcIdentifyInput {
  /** @minLength 1 */
  rawToken: string;
  /** @minLength 1 */
  deviceToken: string;
}

export type NfcIdentifyResultCurrentStatus = typeof NfcIdentifyResultCurrentStatus[keyof typeof NfcIdentifyResultCurrentStatus];


export const NfcIdentifyResultCurrentStatus = {
  out: 'out',
  in: 'in',
  break: 'break',
} as const;

/**
 * Ephemeral proofs keyed by clock action; TTL ~90s
 */
export interface TimeclockClockProofs {
  clock_in: string;
  clock_out: string;
  break_start: string;
  break_end: string;
}

export interface NfcIdentifyResult {
  employeeId: string;
  employeeName: string;
  currentStatus: NfcIdentifyResultCurrentStatus;
  record?: TimeclockRecord | null;
  activeBreak?: TimeclockBreak | null;
  proofs: TimeclockClockProofs;
  expiresAt: string;
  serverTime: string;
}

export interface TimeclockRateLimitError {
  error: string;
  retryAfterMs?: number;
}

export interface TimeclockRecordListItem {
  id: string;
  employeeId: string;
  employeeName: string;
  clockIn: string;
  clockOut?: string | null;
  source: string;
  isManual: boolean;
  notes?: string | null;
  createdAt: string;
}

export interface ManualRecordInput {
  employeeId: string;
  /** ISO-8601 datetime */
  clockIn: string;
  /** ISO-8601 datetime */
  clockOut?: string;
  notes?: string;
}

/**
 * Creates a time_corrections audit row with correctedBy = authenticated manager
 */
export interface UpdateTimeclockRecordInput {
  /** ISO-8601 datetime */
  clockIn?: string;
  /** ISO-8601 datetime */
  clockOut?: string;
  notes?: string;
  reason?: string;
}

export interface TimeclockShift {
  id: string;
  employeeId: string;
  shiftDate: string;
  /** HH:MM */
  startTime: string;
  /** HH:MM */
  endTime: string;
  isSplit: boolean;
  splitStartTime?: string | null;
  splitEndTime?: string | null;
  notes?: string | null;
  createdAt: string;
  createdBy?: string | null;
}

export type TimeclockShiftListItem = TimeclockShift & {
  employeeName: string;
};

export interface CreateTimeclockShiftInput {
  employeeId: string;
  shiftDate: string;
  startTime: string;
  endTime: string;
  isSplit?: boolean;
  splitStartTime?: string;
  splitEndTime?: string;
  notes?: string;
}

export interface TimeclockSuccess {
  success: boolean;
}

export type TimeclockAbsenceAbsenceType = typeof TimeclockAbsenceAbsenceType[keyof typeof TimeclockAbsenceAbsenceType];


export const TimeclockAbsenceAbsenceType = {
  holiday: 'holiday',
  sick_leave: 'sick_leave',
  vacation: 'vacation',
  presentation: 'presentation',
  other: 'other',
} as const;

export type TimeclockAbsenceStatus = typeof TimeclockAbsenceStatus[keyof typeof TimeclockAbsenceStatus];


export const TimeclockAbsenceStatus = {
  pending: 'pending',
  approved: 'approved',
  rejected: 'rejected',
} as const;

export interface TimeclockAbsence {
  id: string;
  employeeId: string;
  absenceDate: string;
  absenceType: TimeclockAbsenceAbsenceType;
  status: TimeclockAbsenceStatus;
  reason?: string | null;
  approvedBy?: string | null;
  approvedAt?: string | null;
  createdAt: string;
}

export type TimeclockAbsenceListItem = TimeclockAbsence & {
  employeeName: string;
};

export type CreateTimeclockAbsenceInputAbsenceType = typeof CreateTimeclockAbsenceInputAbsenceType[keyof typeof CreateTimeclockAbsenceInputAbsenceType];


export const CreateTimeclockAbsenceInputAbsenceType = {
  holiday: 'holiday',
  sick_leave: 'sick_leave',
  vacation: 'vacation',
  presentation: 'presentation',
  other: 'other',
} as const;

export interface CreateTimeclockAbsenceInput {
  employeeId: string;
  absenceDate: string;
  absenceType: CreateTimeclockAbsenceInputAbsenceType;
  reason?: string;
}

export type ApproveTimeclockAbsenceInputStatus = typeof ApproveTimeclockAbsenceInputStatus[keyof typeof ApproveTimeclockAbsenceInputStatus];


export const ApproveTimeclockAbsenceInputStatus = {
  approved: 'approved',
  rejected: 'rejected',
} as const;

export interface ApproveTimeclockAbsenceInput {
  status: ApproveTimeclockAbsenceInputStatus;
}

export interface TimeclockReportSummaryRow {
  employeeId: string;
  employeeName: string;
  totalMinutes: number;
  totalHours: string;
  totalDays: number;
  totalRecords: number;
}

export interface AnvizImportRow {
  anvizId: string;
  /** ISO-8601 datetime */
  clockIn: string;
  /** ISO-8601 datetime */
  clockOut?: string;
}

export interface AnvizImportInput {
  filename: string;
  rows: AnvizImportRow[];
}

export interface AnvizImportError {
  row: number;
  message: string;
}

export interface AnvizImportResult {
  success: boolean;
  imported: number;
  skipped: number;
  errors: AnvizImportError[];
}

export interface TimeclockImportHistoryItem {
  id: string;
  filename: string;
  rowsTotal: number;
  rowsImported: number;
  rowsSkipped: number;
  rowsErrored: number;
  importedByName: string;
  createdAt: string;
}

export type FichajeSettingsWeekStart = typeof FichajeSettingsWeekStart[keyof typeof FichajeSettingsWeekStart];


export const FichajeSettingsWeekStart = {
  monday: 'monday',
  sunday: 'sunday',
} as const;

export interface FichajeSettings {
  id: number;
  companyName: string;
  locale: string;
  /** IANA timezone e.g. Europe/Madrid */
  timezone: string;
  weekStart: FichajeSettingsWeekStart;
  mobileClockEnabled: boolean;
  reportEmail?: string | null;
  reportDayOfWeek?: number | null;
  updatedAt: string;
}

export type UpdateFichajeSettingsInputWeekStart = typeof UpdateFichajeSettingsInputWeekStart[keyof typeof UpdateFichajeSettingsInputWeekStart];


export const UpdateFichajeSettingsInputWeekStart = {
  monday: 'monday',
  sunday: 'sunday',
} as const;

export interface UpdateFichajeSettingsInput {
  companyName?: string;
  locale?: string;
  timezone?: string;
  weekStart?: UpdateFichajeSettingsInputWeekStart;
  mobileClockEnabled?: boolean;
  reportEmail?: string | null;
  reportDayOfWeek?: number;
}

export type FichajeAuditEntryDetails = { [key: string]: unknown } | null;

export interface FichajeAuditEntry {
  id: string;
  action: string;
  employeeId?: string | null;
  performedByName?: string | null;
  entityType?: string | null;
  entityId?: string | null;
  details?: FichajeAuditEntryDetails;
  createdAt: string;
}

export interface NfcCardAssignInput {
  employeeId: string;
  /** @minLength 1 */
  rawToken: string;
  alias?: string;
}

export interface NfcCardCreated {
  id: string;
  alias?: string | null;
  status: string;
  assignedAt: string;
}

export type NfcCardBriefStatus = typeof NfcCardBriefStatus[keyof typeof NfcCardBriefStatus];


export const NfcCardBriefStatus = {
  active: 'active',
  revoked: 'revoked',
} as const;

export interface NfcCardBrief {
  id: string;
  alias?: string | null;
  status: NfcCardBriefStatus;
  lastUsedAt?: string | null;
  assignedAt: string;
  revokedAt?: string | null;
  revokedReason?: string | null;
}

export type NfcCardUpdateInputStatus = typeof NfcCardUpdateInputStatus[keyof typeof NfcCardUpdateInputStatus];


export const NfcCardUpdateInputStatus = {
  active: 'active',
  revoked: 'revoked',
} as const;

export interface NfcCardUpdateInput {
  alias?: string;
  status?: NfcCardUpdateInputStatus;
}

export interface NfcCardRevokeInput {
  reason?: string;
}

export type FichajeMeResponseEmployee = {
  id: string;
  name: string;
  role: string;
};

export type FichajeMeResponseStatus = typeof FichajeMeResponseStatus[keyof typeof FichajeMeResponseStatus];


export const FichajeMeResponseStatus = {
  out: 'out',
  in: 'in',
  break: 'break',
} as const;

export interface FichajeMeResponse {
  employee: FichajeMeResponseEmployee;
  status: FichajeMeResponseStatus;
  currentRecord?: TimeclockRecord | null;
  currentBreak?: TimeclockBreak | null;
}

export interface TabletPairingCode {
  code: string;
  expiresAt: string;
  expiresInSeconds: number;
}

export type TabletDeviceSafeStatus = typeof TabletDeviceSafeStatus[keyof typeof TabletDeviceSafeStatus];


export const TabletDeviceSafeStatus = {
  active: 'active',
  revoked: 'revoked',
} as const;

/**
 * Tablet device without deviceToken; hasToken indicates credential presence
 */
export interface TabletDeviceSafe {
  id: string;
  name: string;
  location: string;
  status: TabletDeviceSafeStatus;
  lastSeenAt?: string | null;
  appVersion?: string | null;
  createdAt: string;
  revokedAt?: string | null;
  hasToken: boolean;
}

export interface TabletRegisterInput {
  /** @minLength 1 */
  name: string;
  location?: string;
  /** @minLength 1 */
  pairingCode: string;
}

export interface TabletRegisterResult {
  deviceToken: string;
  deviceId: string;
}

export interface TabletDeviceInfo {
  id: string;
  name: string;
  status: string;
  location: string;
}

export interface TabletPingInput {
  appVersion?: string;
}

export interface TabletPingResult {
  ok: boolean;
}

export interface VerifyPinInput {
  employeeId: string;
  /**
     * @minLength 1
     * @maxLength 8
     */
  pin: string;
  /** @minLength 1 */
  deviceToken: string;
}

export interface TimeclockClockAuthorization {
  proofs: TimeclockClockProofs;
  expiresAt: string;
  serverTime?: string;
}

export type VerifyPinResult = TimeclockClockAuthorization & {
  ok: boolean;
};

export interface VerifyPinLockedError {
  error: string;
  locked?: boolean;
  retryAfterSeconds?: number;
  attemptsLeft?: number;
}

export type TabletClockInputAction = typeof TabletClockInputAction[keyof typeof TabletClockInputAction];


export const TabletClockInputAction = {
  clock_in: 'clock_in',
  clock_out: 'clock_out',
  break_start: 'break_start',
  break_end: 'break_end',
} as const;

export interface TabletClockInput {
  employeeId: string;
  action: TabletClockInputAction;
  /** @minLength 1 */
  deviceToken: string;
  /** @minLength 32 */
  proof: string;
}

/**
 * Authentication is required or invalid
 */
export type UnauthorizedResponse = ErrorResponse;

/**
 * Request validation failed
 */
export type BadRequestResponse = ErrorResponse;

/**
 * Current resource state conflicts with the operation
 */
export type ConflictResponse = ErrorResponse;

/**
 * Session or authorization verification is temporarily unavailable
 */
export type ServiceUnavailableResponse = ErrorResponse;

/**
 * The authenticated user lacks the required role or permission
 */
export type ForbiddenResponse = ErrorResponse;

/**
 * Requested resource was not found
 */
export type NotFoundResponse = ErrorResponse;

export type GetTimeclockRecordsParams = {
from?: string;
to?: string;
/**
 * Managers only
 */
employeeId?: string;
};

export type GetTimeclockShiftsParams = {
from?: string;
to?: string;
employeeId?: string;
};

export type GetTimeclockAbsencesParams = {
from?: string;
to?: string;
employeeId?: string;
status?: GetTimeclockAbsencesStatus;
};

export type GetTimeclockAbsencesStatus = typeof GetTimeclockAbsencesStatus[keyof typeof GetTimeclockAbsencesStatus];


export const GetTimeclockAbsencesStatus = {
  pending: 'pending',
  approved: 'approved',
  rejected: 'rejected',
} as const;

export type GetTimeclockReportSummaryParams = {
from?: string;
to?: string;
employeeId?: string;
};

export type GetFichajeAuditLogParams = {
/**
 * Max 500
 */
limit?: string;
};

export type PatchTabletDeviceBodyStatus = typeof PatchTabletDeviceBodyStatus[keyof typeof PatchTabletDeviceBodyStatus];


export const PatchTabletDeviceBodyStatus = {
  active: 'active',
  revoked: 'revoked',
} as const;

export type PatchTabletDeviceBody = {
  name?: string;
  location?: string;
  status?: PatchTabletDeviceBodyStatus;
};

