/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Api
 * Piccolo TPV API
 * OpenAPI spec version: 0.2.0
 */
export interface CashPaymentsMethod {
  id: string;
  code: string;
  name: string;
  active: boolean;
  sortOrder: number;
}

export interface CashPaymentsOpenSessionInput {
  openingFloat?: string;
  terminalName?: string;
  blindClose?: boolean;
  notes?: string;
}

export type CashPaymentsSessionDenominationBreakdown = {[key: string]: number} | null;

export type CashPaymentsSessionStatus = typeof CashPaymentsSessionStatus[keyof typeof CashPaymentsSessionStatus];


export const CashPaymentsSessionStatus = {
  open: 'open',
  closed: 'closed',
} as const;

export interface CashPaymentsSession {
  id: string;
  employeeId: string;
  openedAt: string;
  /** @pattern ^-?\d+(\.\d+)?$ */
  openingFloat: string;
  /** @nullable */
  closedAt: string | null;
  /** @nullable */
  expectedCash: string | null;
  /** @nullable */
  countedCash: string | null;
  /** @nullable */
  difference: string | null;
  status: CashPaymentsSessionStatus;
  terminalName: string;
  blindClose: boolean;
  /** @nullable */
  notes: string | null;
  /** @nullable */
  discrepancyReason: string | null;
  /** @nullable */
  closingNotes: string | null;
  isDemo: boolean;
  denominationBreakdown: CashPaymentsSessionDenominationBreakdown;
}

export type CashPaymentsSessionWithEmployee = CashPaymentsSession & {
  employeeName: string;
};

export type CashPaymentsMovementType = typeof CashPaymentsMovementType[keyof typeof CashPaymentsMovementType];


export const CashPaymentsMovementType = {
  in: 'in',
  out: 'out',
  supplier_payment: 'supplier_payment',
  tip: 'tip',
  change_added: 'change_added',
  correction: 'correction',
} as const;

export interface CashPaymentsCreateMovementInput {
  movementType: CashPaymentsMovementType;
  amount: string;
  /** @minLength 1 */
  reason: string;
}

export interface CashPaymentsMovement {
  id: string;
  cashSessionId: string;
  movementType: CashPaymentsMovementType;
  amount: string;
  reason: string;
  employeeId: string;
  createdAt: string;
  /** @nullable */
  employeeName?: string | null;
}

export type CashPaymentsCloseSessionInputDenominationBreakdown = {[key: string]: number};

export interface CashPaymentsCloseSessionInput {
  countedCash: string;
  discrepancyReason?: string;
  closingNotes?: string;
  denominationBreakdown?: CashPaymentsCloseSessionInputDenominationBreakdown;
}

export interface ErrorResponse {
  error: string;
}

export interface CashPaymentsSalesByMethod {
  methodCode: string;
  methodName: string;
  /** @nullable */
  total?: string | null;
}

export interface CashPaymentsSessionSummary {
  session: CashPaymentsSessionWithEmployee;
  salesByMethod: CashPaymentsSalesByMethod[];
  movements: CashPaymentsMovement[];
}

export interface CashPaymentsReportMovement {
  id: string;
  movementType: CashPaymentsMovementType;
  amount: string;
  reason: string;
  createdAt: string;
  /** @nullable */
  employeeName?: string | null;
}

export type CashPaymentsReportTipMethod = typeof CashPaymentsReportTipMethod[keyof typeof CashPaymentsReportTipMethod];


export const CashPaymentsReportTipMethod = {
  cash: 'cash',
  card: 'card',
} as const;

export interface CashPaymentsReportTip {
  amount: string;
  method: CashPaymentsReportTipMethod;
}

export interface CashPaymentsReportVoid {
  id: string;
  reason: string;
  createdAt: string;
  originalPaymentId: string;
  /** @nullable */
  employeeName?: string | null;
}

export type TaxBreakdownItemRate = typeof TaxBreakdownItemRate[keyof typeof TaxBreakdownItemRate];


export const TaxBreakdownItemRate = {
  NUMBER_4: 4,
  NUMBER_10: 10,
  NUMBER_21: 21,
} as const;

/**
 * @pattern ^-?\d+\.\d{2}$
 */
export type Money = string;

export interface TaxBreakdownItem {
  rate: TaxBreakdownItemRate;
  base: Money;
  cuota: Money;
}

export interface CashPaymentsZReport {
  session: CashPaymentsSessionWithEmployee;
  salesByMethod: CashPaymentsSalesByMethod[];
  movements: CashPaymentsReportMovement[];
  tips: CashPaymentsReportTip[];
  voids: CashPaymentsReportVoid[];
  totalSales: string;
  totalTips: string;
  movIn: string;
  movOut: string;
  paymentsCount: number;
  taxBreakdown: TaxBreakdownItem[];
}

export type CashPaymentsXReport = CashPaymentsZReport & {
  isProvisional: true;
};

export interface CashPaymentsVoidInput {
  paymentId: string;
  /** @minLength 5 */
  reason: string;
}

export interface CashPaymentsVoid {
  id: string;
  originalPaymentId: string;
  reason: string;
  authorizedBy: string;
  /** @nullable */
  cashSessionId: string | null;
  /** @nullable */
  counterMovementId: string | null;
  createdAt: string;
}

export interface CashPaymentsSessionHistoryItem {
  id: string;
  terminalName: string;
  openedAt: string;
  /** @nullable */
  closedAt: string | null;
  openingFloat: string;
  /** @nullable */
  expectedCash: string | null;
  /** @nullable */
  countedCash: string | null;
  /** @nullable */
  difference: string | null;
  status: CashPaymentsSessionStatus;
  blindClose: boolean;
  /** @nullable */
  employeeName: string | null;
}

export type CashPaymentsOrderSummaryOrder = {
  id: string;
  status: string;
  /** @nullable */
  tableName?: string | null;
  /** @nullable */
  employeeName?: string | null;
};

export interface CashPaymentsOrderSummaryItem {
  id: string;
  productName: string;
  quantity: number;
  unitPrice: string;
  lineTotal: string;
  taxRate?: number;
}

export type CashPaymentsSummaryPaymentStatus = typeof CashPaymentsSummaryPaymentStatus[keyof typeof CashPaymentsSummaryPaymentStatus];


export const CashPaymentsSummaryPaymentStatus = {
  completed: 'completed',
  voided: 'voided',
} as const;

export interface CashPaymentsSummaryPayment {
  id: string;
  amount: string;
  status: CashPaymentsSummaryPaymentStatus;
  createdAt: string;
  methodCode: string;
  methodName: string;
}

export interface CashPaymentsOrderSummary {
  order: CashPaymentsOrderSummaryOrder;
  items: CashPaymentsOrderSummaryItem[];
  discount?: string;
  taxBreakdown: TaxBreakdownItem[];
  subtotal: string;
  taxTotal: string;
  total: string;
  paid: string;
  remaining: string;
  methods: CashPaymentsMethod[];
  payments: CashPaymentsSummaryPayment[];
}

/**
 * Runtime-seeded method code; invitation additionally requires admin.
 */
export type CashPaymentsCreateOrderPaymentInputMethodCode = typeof CashPaymentsCreateOrderPaymentInputMethodCode[keyof typeof CashPaymentsCreateOrderPaymentInputMethodCode];


export const CashPaymentsCreateOrderPaymentInputMethodCode = {
  cash: 'cash',
  card: 'card',
  bizum: 'bizum',
  transfer: 'transfer',
  cheque_rest: 'cheque_rest',
  invitation: 'invitation',
  other: 'other',
  cash_machine: 'cash_machine',
} as const;

export interface CashPaymentsCreateOrderPaymentInput {
  /** Runtime-seeded method code; invitation additionally requires admin. */
  methodCode: CashPaymentsCreateOrderPaymentInputMethodCode;
  amount: string;
  reference?: string;
  terminal?: string;
}

export type CashPaymentsPaymentStatus = typeof CashPaymentsPaymentStatus[keyof typeof CashPaymentsPaymentStatus];


export const CashPaymentsPaymentStatus = {
  completed: 'completed',
  voided: 'voided',
} as const;

export interface CashPaymentsPayment {
  id: string;
  orderId: string;
  paymentMethodId: string;
  /** @nullable */
  cashSessionId: string | null;
  amount: string;
  status: CashPaymentsPaymentStatus;
  /** @nullable */
  reference: string | null;
  employeeId: string;
  createdAt: string;
  isDemo: boolean;
}

export interface CashPaymentsTicketHeader {
  id: string;
  orderId: string;
  ticketNumber: number;
  subtotal: string;
  taxTotal: string;
  total: string;
  issuedAt: string;
  [key: string]: unknown;
 }

export interface CashPaymentsResult {
  payment: CashPaymentsPayment;
  ticket: CashPaymentsTicketHeader | null;
  change: string;
  newRemaining: number;
  idempotent?: boolean;
}

export type CashPaymentsTicketOrder = { [key: string]: unknown };

export type CashPaymentsTicketItemsItem = { [key: string]: unknown };

export type CashPaymentsTicketPaymentsItem = { [key: string]: unknown };

export interface CashPaymentsTicket {
  ticket: CashPaymentsTicketHeader;
  order: CashPaymentsTicketOrder;
  items: CashPaymentsTicketItemsItem[];
  payments: CashPaymentsTicketPaymentsItem[];
  taxBreakdown: TaxBreakdownItem[];
  /** @nullable */
  employeeName: string | null;
}

export type CashPaymentsSplitGroupStatus = typeof CashPaymentsSplitGroupStatus[keyof typeof CashPaymentsSplitGroupStatus];


export const CashPaymentsSplitGroupStatus = {
  open: 'open',
  paid: 'paid',
} as const;

export interface CashPaymentsSplitItem {
  id?: string;
  orderItemId: string;
  quantity: string;
  productName?: string;
  unitPrice?: string;
  lineTotal?: string;
}

export interface CashPaymentsSplitGroup {
  id: string;
  orderId: string;
  label: string;
  status: CashPaymentsSplitGroupStatus;
  total: string;
  sortOrder: number;
  createdAt?: string;
  items?: CashPaymentsSplitItem[];
  paid?: string;
}

export type CashPaymentsCreateSplitsInputGroupsItemItemsItem = {
  orderItemId: string;
  quantity: number;
};

export type CashPaymentsCreateSplitsInputGroupsItem = {
  label: string;
  total?: string | number;
  items: CashPaymentsCreateSplitsInputGroupsItemItemsItem[];
};

export interface CashPaymentsCreateSplitsInput {
  /**
     * @minItems 1
     * @maxItems 8
     */
  groups: CashPaymentsCreateSplitsInputGroupsItem[];
}

export type CashPaymentsCreatedSplitGroupStatus = typeof CashPaymentsCreatedSplitGroupStatus[keyof typeof CashPaymentsCreatedSplitGroupStatus];


export const CashPaymentsCreatedSplitGroupStatus = {
  open: 'open',
  paid: 'paid',
} as const;

export type CashPaymentsCreatedSplitGroupItemsItem = {
  orderItemId: string;
  quantity: number;
};

export interface CashPaymentsCreatedSplitGroup {
  id: string;
  orderId: string;
  label: string;
  status: CashPaymentsCreatedSplitGroupStatus;
  total: string;
  sortOrder: number;
  createdAt: string;
  items: CashPaymentsCreatedSplitGroupItemsItem[];
}

export interface CashPaymentsMarkSplitPaidInput {
  paymentId?: string;
}

export type CashPaymentsCreateTipInputMethod = typeof CashPaymentsCreateTipInputMethod[keyof typeof CashPaymentsCreateTipInputMethod];


export const CashPaymentsCreateTipInputMethod = {
  cash: 'cash',
  card: 'card',
} as const;

export interface CashPaymentsCreateTipInput {
  amount: string;
  method?: CashPaymentsCreateTipInputMethod;
}

export type CashPaymentsTipMethod = typeof CashPaymentsTipMethod[keyof typeof CashPaymentsTipMethod];


export const CashPaymentsTipMethod = {
  cash: 'cash',
  card: 'card',
} as const;

export interface CashPaymentsTip {
  id: string;
  paymentId: string;
  orderId: string;
  amount: string;
  method: CashPaymentsTipMethod;
  /** @nullable */
  cashSessionId?: string | null;
  createdAt: string;
}

/**
 * Safe DTO; credentialKey is never returned.
 */
export interface CashPaymentsMachineConfig {
  /** @nullable */
  id: string | null;
  manufacturer: string;
  model: string;
  host: string;
  port: number;
  connectionType: string;
  deviceId: string;
  timeoutMs: number;
  enabled: boolean;
  hasCredential: boolean;
  createdAt?: string;
  updatedAt?: string;
}

export interface CashPaymentsUpdateMachineConfigInput {
  manufacturer?: string;
  model?: string;
  host?: string;
  port?: number;
  connectionType?: string;
  deviceId?: string;
  credentialKey?: string;
  timeoutMs?: number;
  enabled?: boolean;
}

export interface CashPaymentsMachineConnectionResult {
  ok: boolean;
  latencyMs?: number;
  error?: string;
}

export type CashPaymentsMachineStatusStatus = typeof CashPaymentsMachineStatusStatus[keyof typeof CashPaymentsMachineStatusStatus];


export const CashPaymentsMachineStatusStatus = {
  connected: 'connected',
  disconnected: 'disconnected',
  busy: 'busy',
  error: 'error',
  maintenance: 'maintenance',
} as const;

export interface CashPaymentsMachineStatus {
  status: CashPaymentsMachineStatusStatus;
  busyWithTransactionId?: string;
  jamDetected: boolean;
  doorOpen: boolean;
  maintenanceRequired: boolean;
  lastSeen: string;
  supportsCashLevels: boolean;
}

export interface CashPaymentsMachineCashLevel {
  denomination: number;
  count: number;
  isLow: boolean;
}

export interface CashPaymentsStartMachinePaymentInput {
  orderId?: string;
  amount: string;
  splitRef?: string;
  terminalName?: string;
}

export type CashPaymentsMachineTransactionTransactionType = typeof CashPaymentsMachineTransactionTransactionType[keyof typeof CashPaymentsMachineTransactionTransactionType];


export const CashPaymentsMachineTransactionTransactionType = {
  payment: 'payment',
  refund: 'refund',
} as const;

export type CashPaymentsMachineTransactionStatus = typeof CashPaymentsMachineTransactionStatus[keyof typeof CashPaymentsMachineTransactionStatus];


export const CashPaymentsMachineTransactionStatus = {
  pending: 'pending',
  iniciando: 'iniciando',
  esperando_efectivo: 'esperando_efectivo',
  efectivo_parcial: 'efectivo_parcial',
  devolviendo_cambio: 'devolviendo_cambio',
  completada: 'completada',
  cancelada: 'cancelada',
  tiempo_agotado: 'tiempo_agotado',
  error: 'error',
  intervencion_manual: 'intervencion_manual',
  conciliando: 'conciliando',
  conciliacion_pendiente: 'conciliacion_pendiente',
} as const;

export interface CashPaymentsMachineTransaction {
  id: string;
  /** @nullable */
  orderId: string | null;
  /** @nullable */
  splitRef: string | null;
  transactionType: CashPaymentsMachineTransactionTransactionType;
  amountRequested: string;
  amountReceived: string;
  changeDispensed: string;
  status: CashPaymentsMachineTransactionStatus;
  /** @nullable */
  deviceTransactionId: string | null;
  /** @nullable */
  deviceError: string | null;
  /** @nullable */
  employeeId: string | null;
  terminalName: string;
  deviceId: string;
  startedAt: string;
  /** @nullable */
  completedAt: string | null;
  createdAt: string;
}

export interface CashPaymentsMachineCommandResult {
  transaction: CashPaymentsMachineTransaction;
  recovering?: boolean;
  reconciliationRequired?: boolean;
  error?: string;
}

export type CashPaymentsMachinePaymentPollResultSettlement = { [key: string]: unknown } | null;

export type CashPaymentsMachinePaymentPollResult = CashPaymentsMachineCommandResult & {
  settlement?: CashPaymentsMachinePaymentPollResultSettlement;
  needsReconciliation?: boolean;
  error?: string;
};

export type CashPaymentsMachineRefundInput = CashPaymentsStartMachinePaymentInput;

export type CashPaymentsMachineTransactionLedgerRowTransactionType = typeof CashPaymentsMachineTransactionLedgerRowTransactionType[keyof typeof CashPaymentsMachineTransactionLedgerRowTransactionType];


export const CashPaymentsMachineTransactionLedgerRowTransactionType = {
  payment: 'payment',
  refund: 'refund',
} as const;

export interface CashPaymentsMachineTransactionLedgerRow {
  id: string;
  /** @nullable */
  orderId: string | null;
  transactionType: CashPaymentsMachineTransactionLedgerRowTransactionType;
  amountRequested: string;
  amountReceived: string;
  changeDispensed: string;
  status: CashPaymentsMachineTransactionStatus;
  terminalName: string;
  startedAt: string;
  /** @nullable */
  completedAt: string | null;
  /** @nullable */
  deviceError: string | null;
  /** @nullable */
  employeeName: string | null;
}

export interface CashPaymentsMachineSessionSummary {
  enabled: boolean;
  tpvTotal: string;
  deviceTotal: string;
  grossReceived: string;
  changeDispensed: string;
  refundsDispensed: string;
  difference: string;
  transactionCount: number;
}

export interface CashPaymentsMethodReportRow {
  methodId: string;
  name: string;
  code: string;
  total: number;
  count: number;
}

export interface CashPaymentsSessionReportRow {
  id: string;
  terminalName: string;
  employeeName: string;
  openedAt: string;
  /** @nullable */
  closedAt: string | null;
  status: CashPaymentsSessionStatus;
  openingFloat: number;
  /** @nullable */
  expectedCash: number | null;
  /** @nullable */
  countedCash: number | null;
  /** @nullable */
  difference: number | null;
  inMovements: number;
  outMovements: number;
}

/**
 * Authentication is required or invalid
 */
export type UnauthorizedResponse = ErrorResponse;

/**
 * The authenticated user lacks the required role or permission
 */
export type ForbiddenResponse = ErrorResponse;

/**
 * Current resource state conflicts with the operation
 */
export type ConflictResponse = ErrorResponse;

/**
 * Request validation failed
 */
export type BadRequestResponse = ErrorResponse;

/**
 * Requested resource was not found
 */
export type NotFoundResponse = ErrorResponse;

/**
 * Session or authorization verification is temporarily unavailable
 */
export type ServiceUnavailableResponse = ErrorResponse;

export type GetCurrentCashPaymentsSessionParams = {
terminal?: string;
};

export type ListCashPaymentsMachineTransactionsParams = {
/**
 * @minimum 1
 * @maximum 200
 */
limit?: number;
/**
 * @minimum 0
 */
offset?: number;
};

export type GetCashPaymentsMethodReportParams = {
from?: string;
to?: string;
};

export type GetCashPaymentsSessionReportListParams = {
from?: string;
to?: string;
};

