/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Api
 * Piccolo TPV API
 * OpenAPI spec version: 0.2.0
 */
export interface DeliveryAddress {
  id: string;
  clientId?: string | null;
  name: string;
  phone: string;
  street: string;
  number: string;
  floor: string;
  postalCode: string;
  city: string;
  notes: string;
  active: boolean;
  createdAt: string;
}

export interface CourierBrief {
  id: string;
  name: string;
  phone?: string;
  status?: string;
}

export interface DeliveryOrderListItem {
  id: string;
  orderNumber?: string | null;
  status: string;
  channel?: string;
  deliveryType: string;
  clientName: string;
  clientPhone?: string;
  estimatedReadyAt?: string | null;
  scheduledAt?: string | null;
  deliveryFee?: string;
  onlinePaymentStatus?: string;
  courierId?: string | null;
  notes?: string;
  createdAt: string;
  deliveryAddressId?: string | null;
  rejectionReason?: string | null;
  address?: DeliveryAddress | null;
  courier?: CourierBrief | null;
  total: string;
}

export type CreateDeliveryOrderInputDeliveryType = typeof CreateDeliveryOrderInputDeliveryType[keyof typeof CreateDeliveryOrderInputDeliveryType];


export const CreateDeliveryOrderInputDeliveryType = {
  takeaway: 'takeaway',
  delivery: 'delivery',
} as const;

export type CreateDeliveryOrderInputChannel = typeof CreateDeliveryOrderInputChannel[keyof typeof CreateDeliveryOrderInputChannel];


export const CreateDeliveryOrderInputChannel = {
  phone: 'phone',
  counter: 'counter',
  tpv: 'tpv',
} as const;

export type CreateDeliveryOrderInputDeliveryAddress = {
  street: string;
  number: string;
  floor?: string;
  postalCode: string;
  city: string;
  notes?: string;
};

export type CreateDeliveryOrderInputItemsItem = {
  productId: string;
  /**
     * @minimum 1
     * @maximum 99
     */
  quantity: number;
  formatId?: string;
  notes?: string;
  modifierIds?: string[];
};

export interface CreateDeliveryOrderInput {
  deliveryType?: CreateDeliveryOrderInputDeliveryType;
  channel?: CreateDeliveryOrderInputChannel;
  clientName: string;
  clientPhone?: string;
  scheduledAt?: string;
  deliveryAddress?: CreateDeliveryOrderInputDeliveryAddress;
  /** @minItems 1 */
  items: CreateDeliveryOrderInputItemsItem[];
  paymentMethod?: string;
  overrideDeliveryFee?: number;
  discountAmount?: number;
  notes?: string;
  courierId?: string;
  saveAddress?: boolean;
}

export interface DeliveryOrderCreated {
  id: string;
  orderNumber: string;
  status: string;
  total: string;
  estimatedReadyAt: string;
  matchedZone?: string | null;
  deliveryFee: number;
  requiresKitchenSend: boolean;
}

/**
 * @pattern ^-?\d+\.\d{2}$
 */
export type Money = string;

export interface OrderItemModifier {
  id: string;
  orderItemId: string;
  modifierId?: string;
  modifierName: string;
  priceDelta: string;
}

export interface OrderItem {
  id: string;
  orderId: string;
  productId: string;
  productName: string;
  formatId?: string | null;
  formatName?: string | null;
  quantity: number;
  unitPrice: string;
  status: string;
  notes: string;
  allergyNote: string;
  hasAllergy: boolean;
  isInvitation: boolean;
  modifiers?: OrderItemModifier[];
  createdAt: string;
}

export interface Order {
  id: string;
  tableId: string | null;
  employeeId: string | null;
  orderType: string;
  status: string;
  guestCount: number;
  notes: string;
  clientName: string;
  clientId?: string | null;
  openedByTerminal: string;
  createdAt: string;
  sentAt: string | null;
  channel: string;
  deliveryType: string;
  orderNumber: string | null;
  scheduledAt: string | null;
  estimatedReadyAt: string | null;
  clientPhone: string;
  deliveryAddressId: string | null;
  courierId: string | null;
  rejectionReason: string | null;
  onlinePaymentRef: string | null;
  onlinePaymentStatus: string;
  packagingCheckedBy: string | null;
  packagingCheckedAt: string | null;
  deliveryFee: Money;
  tipAmount: Money;
  idempotencyKey: string | null;
  tableSessionId: string | null;
  isDemo: boolean;
  items?: OrderItem[];
}

export interface DeliveryOrderStatusHistory {
  id: string;
  orderId: string;
  fromStatus?: string | null;
  toStatus: string;
  changedBy?: string | null;
  changedByName: string;
  device?: string;
  note?: string;
  source?: string;
  createdAt: string;
}

export type DeliveryOrderDetail = Order & ({
  items?: OrderItem[];
  history?: DeliveryOrderStatusHistory[];
  address?: DeliveryAddress | null;
  courier?: CourierBrief | null;
});

export interface PatchDeliveryOrderInput {
  status?: string;
  courierId?: string | null;
  estimatedReadyAt?: string;
  notes?: string;
  note?: string;
}

export interface DeliveryOrderPatchResult {
  success: boolean;
  courierId?: string | null;
  idempotent?: boolean;
}

export type OnlineOrderInboxItemItemsItem = {
  id: string;
  productName: string;
  quantity: number;
  unitPrice: string;
  taxRate?: number;
};

export interface OnlineOrderInboxItem {
  id: string;
  orderNumber?: string | null;
  status: string;
  channel?: string;
  deliveryType: string;
  clientName: string;
  clientPhone?: string;
  estimatedReadyAt?: string | null;
  scheduledAt?: string | null;
  deliveryFee?: string;
  onlinePaymentStatus?: string;
  onlinePaymentRef?: string | null;
  courierId?: string | null;
  rejectionReason?: string | null;
  packagingCheckedAt?: string | null;
  deliveryAddressId?: string | null;
  notes?: string;
  createdAt: string;
  items?: OnlineOrderInboxItemItemsItem[];
  address?: DeliveryAddress | null;
  courier?: CourierBrief | null;
  total: string;
}

export interface ConfirmOnlineOrderInput {
  estimatedReadyAt?: string;
}

export type OnlineOrderConfirmResultNotificationStatus = typeof OnlineOrderConfirmResultNotificationStatus[keyof typeof OnlineOrderConfirmResultNotificationStatus];


export const OnlineOrderConfirmResultNotificationStatus = {
  not_configured: 'not_configured',
  simulated: 'simulated',
} as const;

export interface OnlineOrderConfirmResult {
  ok: true;
  status: string;
  estimatedReadyAt: string;
  notificationStatus: OnlineOrderConfirmResultNotificationStatus;
  requiresKitchenSend: boolean;
}

export interface RejectOnlineOrderInput {
  reason: string;
}

export type OnlineOrderRejectResultNotificationStatus = typeof OnlineOrderRejectResultNotificationStatus[keyof typeof OnlineOrderRejectResultNotificationStatus];


export const OnlineOrderRejectResultNotificationStatus = {
  not_configured: 'not_configured',
  simulated: 'simulated',
} as const;

export interface OnlineOrderRejectResult {
  ok: true;
  status: string;
  notificationStatus: OnlineOrderRejectResultNotificationStatus;
}

export interface PatchOnlineOrderStatusInput {
  status: string;
  estimatedReadyAt?: string;
}

export type OnlineOrderStatusResultNotificationStatus = typeof OnlineOrderStatusResultNotificationStatus[keyof typeof OnlineOrderStatusResultNotificationStatus];


export const OnlineOrderStatusResultNotificationStatus = {
  not_configured: 'not_configured',
  simulated: 'simulated',
} as const;

export interface OnlineOrderStatusResult {
  ok: true;
  status: string;
  notificationStatus: OnlineOrderStatusResultNotificationStatus;
}

export interface PaymentSimulateInput {
  approve?: boolean;
}

export interface PaymentSimulateResult {
  ok: true;
  approved: boolean;
  ref?: string | null;
}

export interface AssignCourierInput {
  courierId: string;
}

export interface AssignCourierResult {
  ok: true;
  courier: CourierBrief;
}

export interface OkResponse {
  ok: true;
}

export type OnlineOrdersConfigMaskedSchedule = {[key: string]: {
  open?: string;
  close?: string;
  open2?: string;
  close2?: string;
}} | null;

export interface OnlineOrdersConfigMasked {
  id: string;
  takeawayEnabled: boolean;
  deliveryEnabled: boolean;
  schedule?: OnlineOrdersConfigMaskedSchedule;
  prepTimeMinutes: number;
  minOrder: string;
  minOrderDelivery: string;
  deliveryFee: string;
  freeDeliveryFrom?: string | null;
  maxAdvanceHours: number;
  maxOrdersPerSlot: number;
  paused: boolean;
  pauseReason: string;
  tipEnabled: boolean;
  tipPercentages?: number[];
  tableOrderingEnabled: boolean;
  stripePublishableKey: string;
  stripeSecretKey?: string;
  stripeWebhookSecret?: string;
  updatedAt: string;
}

export type DeliveryZoneType = typeof DeliveryZoneType[keyof typeof DeliveryZoneType];


export const DeliveryZoneType = {
  postal_code: 'postal_code',
  city: 'city',
  radius: 'radius',
} as const;

export type DeliveryZoneValue = { [key: string]: unknown };

export interface DeliveryZone {
  id: string;
  name: string;
  type: DeliveryZoneType;
  value?: DeliveryZoneValue;
  deliveryFee: string;
  minOrder: string;
  estimatedMinutes: number;
  active: boolean;
  sortOrder: number;
  createdAt: string;
}

/**
 * Courier record with bearer token stripped
 */
export interface CourierSafe {
  id: string;
  name: string;
  phone: string;
  status: string;
  active?: boolean;
  vehicleType?: string;
  plate?: string;
  zonaHabitual?: string;
  turno?: string;
  earnedCashPending?: string;
  earnedCardPending?: string;
  totalDeliveries?: number;
  avgDeliveryMinutes?: number;
  hasToken?: boolean;
  createdAt?: string;
}

export interface AdminOnlineConfigResponse {
  config?: OnlineOrdersConfigMasked | null;
  zones: DeliveryZone[];
  couriers: CourierSafe[];
}

export type PatchOnlineConfigInputSchedule = {[key: string]: {
  open?: string;
  close?: string;
  open2?: string;
  close2?: string;
}};

export interface PatchOnlineConfigInput {
  takeawayEnabled?: boolean;
  deliveryEnabled?: boolean;
  schedule?: PatchOnlineConfigInputSchedule;
  prepTimeMinutes?: number;
  minOrder?: string;
  minOrderDelivery?: string;
  deliveryFee?: string;
  freeDeliveryFrom?: string;
  maxAdvanceHours?: number;
  maxOrdersPerSlot?: number;
  paused?: boolean;
  pauseReason?: string;
  tipEnabled?: boolean;
  tipPercentages?: number[];
  tableOrderingEnabled?: boolean;
  stripePublishableKey?: string;
}

export type CreateDeliveryZoneInputType = typeof CreateDeliveryZoneInputType[keyof typeof CreateDeliveryZoneInputType];


export const CreateDeliveryZoneInputType = {
  postal_code: 'postal_code',
  city: 'city',
  radius: 'radius',
} as const;

export type CreateDeliveryZoneInputValue = { [key: string]: unknown };

export interface CreateDeliveryZoneInput {
  name: string;
  type?: CreateDeliveryZoneInputType;
  value?: CreateDeliveryZoneInputValue;
  deliveryFee?: string;
  minOrder?: string;
  estimatedMinutes?: number;
  sortOrder?: number;
}

export interface PatchDeliveryZoneInput { [key: string]: unknown }

export interface CreateCourierInput {
  name: string;
  phone?: string;
}

export interface PatchCourierInput { [key: string]: unknown }

export type CourierAdminSummaryCourier = {
  id: string;
  name: string;
  phone: string;
  status: string;
  vehicleType?: string;
  plate?: string;
  earnedCashPending?: string;
  earnedCardPending?: string;
  totalDeliveries?: number;
};

export type CourierAdminSummaryActiveOrdersItem = { [key: string]: unknown };

export interface CourierAdminSummary {
  courier: CourierAdminSummaryCourier;
  activeOrders: CourierAdminSummaryActiveOrdersItem[];
  todayDeliveries: number;
}

export interface SettleCourierInput {
  tips?: number;
  expenses?: number;
  differences?: number;
  notes?: string;
}

export interface CourierSettlement {
  id: string;
  courierId: string;
  periodStart: string;
  periodEnd: string;
  ordersCount: number;
  totalCash: string;
  totalCard: string;
  totalOnline: string;
  tips: string;
  expenses: string;
  differences: string;
  closedBy?: string | null;
  closedByName: string;
  notes: string;
  createdAt: string;
}

export interface SettleCourierResult {
  settlement: CourierSettlement;
}

export type CourierSettlementWithName = CourierSettlement & {
  courierName: string;
};

export interface ErrorResponse {
  error: string;
}

/**
 * Authentication is required or invalid
 */
export type UnauthorizedResponse = ErrorResponse;

/**
 * The authenticated user lacks the required role or permission
 */
export type ForbiddenResponse = ErrorResponse;

/**
 * Session or authorization verification is temporarily unavailable
 */
export type ServiceUnavailableResponse = ErrorResponse;

/**
 * Request validation failed
 */
export type BadRequestResponse = ErrorResponse;

/**
 * Requested resource was not found
 */
export type NotFoundResponse = ErrorResponse;

/**
 * Current resource state conflicts with the operation
 */
export type ConflictResponse = ErrorResponse;

export type GetDeliveryOrdersParams = {
/**
 * Filter by calendar day (YYYY-MM-DD)
 */
date?: string;
from?: string;
to?: string;
/**
 * Skip filter when value is "all"
 */
status?: string;
courierId?: string;
type?: GetDeliveryOrdersType;
};

export type GetDeliveryOrdersType = typeof GetDeliveryOrdersType[keyof typeof GetDeliveryOrdersType];


export const GetDeliveryOrdersType = {
  delivery: 'delivery',
  takeaway: 'takeaway',
} as const;

export type GetOnlineOrdersInboxParams = {
/**
 * Skip filter when value is "all"
 */
status?: string;
date?: string;
};

export type GetCourierSettlementsParams = {
courierId?: string;
from?: string;
to?: string;
};

