/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Api
 * Piccolo TPV API
 * OpenAPI spec version: 0.2.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AdminOnlineConfigResponse,
  AssignCourierInput,
  AssignCourierResult,
  BadRequestResponse,
  ConfirmOnlineOrderInput,
  ConflictResponse,
  CourierAdminSummary,
  CourierSafe,
  CourierSettlementWithName,
  CreateCourierInput,
  CreateDeliveryOrderInput,
  CreateDeliveryZoneInput,
  DeliveryOrderCreated,
  DeliveryOrderDetail,
  DeliveryOrderListItem,
  DeliveryOrderPatchResult,
  DeliveryOrderStatusHistory,
  DeliveryZone,
  ForbiddenResponse,
  GetCourierSettlementsParams,
  GetDeliveryOrdersParams,
  GetOnlineOrdersInboxParams,
  NotFoundResponse,
  OkResponse,
  OnlineOrderConfirmResult,
  OnlineOrderInboxItem,
  OnlineOrderRejectResult,
  OnlineOrderStatusResult,
  OnlineOrdersConfigMasked,
  PatchCourierInput,
  PatchDeliveryOrderInput,
  PatchDeliveryZoneInput,
  PatchOnlineConfigInput,
  PatchOnlineOrderStatusInput,
  PaymentSimulateInput,
  PaymentSimulateResult,
  RejectOnlineOrderInput,
  ServiceUnavailableResponse,
  SettleCourierInput,
  SettleCourierResult,
  UnauthorizedResponse
} from './api.schemas';

import { customFetch } from '../custom-fetch';
import type { ErrorType , BodyType } from '../custom-fetch';

type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const getGetDeliveryOrdersUrl = (params?: GetDeliveryOrdersParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/delivery-orders?${stringifiedParams}` : `/api/delivery-orders`
}

/**
 * @summary List delivery and takeaway orders with filters
 */
export const getDeliveryOrders = async (params?: GetDeliveryOrdersParams, options?: RequestInit): Promise<DeliveryOrderListItem[]> => {

  return customFetch<DeliveryOrderListItem[]>(getGetDeliveryOrdersUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetDeliveryOrdersQueryKey = (params?: GetDeliveryOrdersParams,) => {
    return [
    `/api/delivery-orders`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetDeliveryOrdersQueryOptions = <TData = Awaited<ReturnType<typeof getDeliveryOrders>>, TError = ErrorType<UnauthorizedResponse | ForbiddenResponse | ServiceUnavailableResponse>>(params?: GetDeliveryOrdersParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getDeliveryOrders>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetDeliveryOrdersQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getDeliveryOrders>>> = ({ signal }) => getDeliveryOrders(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getDeliveryOrders>>, TError, TData> & { queryKey: QueryKey }
}

export type GetDeliveryOrdersQueryResult = NonNullable<Awaited<ReturnType<typeof getDeliveryOrders>>>
export type GetDeliveryOrdersQueryError = ErrorType<UnauthorizedResponse | ForbiddenResponse | ServiceUnavailableResponse>


/**
 * @summary List delivery and takeaway orders with filters
 */

export function useGetDeliveryOrders<TData = Awaited<ReturnType<typeof getDeliveryOrders>>, TError = ErrorType<UnauthorizedResponse | ForbiddenResponse | ServiceUnavailableResponse>>(
 params?: GetDeliveryOrdersParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getDeliveryOrders>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetDeliveryOrdersQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}







export const getCreateDeliveryOrderUrl = () => {




  return `/api/delivery-orders`
}

/**
 * @summary Create a manual delivery or pickup order from the TPV
 */
export const createDeliveryOrder = async (createDeliveryOrderInput: CreateDeliveryOrderInput, options?: RequestInit): Promise<DeliveryOrderCreated> => {

  return customFetch<DeliveryOrderCreated>(getCreateDeliveryOrderUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createDeliveryOrderInput)
  }
);}





export const getCreateDeliveryOrderMutationOptions = <TError = ErrorType<BadRequestResponse | UnauthorizedResponse | ForbiddenResponse | NotFoundResponse | ServiceUnavailableResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createDeliveryOrder>>, TError,{data: BodyType<CreateDeliveryOrderInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof createDeliveryOrder>>, TError,{data: BodyType<CreateDeliveryOrderInput>}, TContext> => {

const mutationKey = ['createDeliveryOrder'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createDeliveryOrder>>, {data: BodyType<CreateDeliveryOrderInput>}> = (props) => {
          const {data} = props ?? {};

          return  createDeliveryOrder(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateDeliveryOrderMutationResult = NonNullable<Awaited<ReturnType<typeof createDeliveryOrder>>>
    export type CreateDeliveryOrderMutationBody = BodyType<CreateDeliveryOrderInput>
    export type CreateDeliveryOrderMutationError = ErrorType<BadRequestResponse | UnauthorizedResponse | ForbiddenResponse | NotFoundResponse | ServiceUnavailableResponse>

    /**
 * @summary Create a manual delivery or pickup order from the TPV
 */
export const useCreateDeliveryOrder = <TError = ErrorType<BadRequestResponse | UnauthorizedResponse | ForbiddenResponse | NotFoundResponse | ServiceUnavailableResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createDeliveryOrder>>, TError,{data: BodyType<CreateDeliveryOrderInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof createDeliveryOrder>>,
        TError,
        {data: BodyType<CreateDeliveryOrderInput>},
        TContext
      > => {
      return useMutation(getCreateDeliveryOrderMutationOptions(options));
    }

export const getGetDeliveryOrderUrl = (id: string,) => {




  return `/api/delivery-orders/${id}`
}

/**
 * @summary Get delivery order detail with items, history and address
 */
export const getDeliveryOrder = async (id: string, options?: RequestInit): Promise<DeliveryOrderDetail> => {

  return customFetch<DeliveryOrderDetail>(getGetDeliveryOrderUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetDeliveryOrderQueryKey = (id: string,) => {
    return [
    `/api/delivery-orders/${id}`
    ] as const;
    }


export const getGetDeliveryOrderQueryOptions = <TData = Awaited<ReturnType<typeof getDeliveryOrder>>, TError = ErrorType<UnauthorizedResponse | ForbiddenResponse | NotFoundResponse | ServiceUnavailableResponse>>(id: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getDeliveryOrder>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetDeliveryOrderQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getDeliveryOrder>>> = ({ signal }) => getDeliveryOrder(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getDeliveryOrder>>, TError, TData> & { queryKey: QueryKey }
}

export type GetDeliveryOrderQueryResult = NonNullable<Awaited<ReturnType<typeof getDeliveryOrder>>>
export type GetDeliveryOrderQueryError = ErrorType<UnauthorizedResponse | ForbiddenResponse | NotFoundResponse | ServiceUnavailableResponse>


/**
 * @summary Get delivery order detail with items, history and address
 */

export function useGetDeliveryOrder<TData = Awaited<ReturnType<typeof getDeliveryOrder>>, TError = ErrorType<UnauthorizedResponse | ForbiddenResponse | NotFoundResponse | ServiceUnavailableResponse>>(
 id: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getDeliveryOrder>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetDeliveryOrderQueryOptions(id,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}







export const getPatchDeliveryOrderUrl = (id: string,) => {




  return `/api/delivery-orders/${id}`
}

/**
 * @summary Update delivery order status, courier or notes
 */
export const patchDeliveryOrder = async (id: string,
    patchDeliveryOrderInput: PatchDeliveryOrderInput, options?: RequestInit): Promise<DeliveryOrderPatchResult> => {

  return customFetch<DeliveryOrderPatchResult>(getPatchDeliveryOrderUrl(id),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(patchDeliveryOrderInput)
  }
);}





export const getPatchDeliveryOrderMutationOptions = <TError = ErrorType<UnauthorizedResponse | ForbiddenResponse | NotFoundResponse | ConflictResponse | ServiceUnavailableResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchDeliveryOrder>>, TError,{id: string;data: BodyType<PatchDeliveryOrderInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof patchDeliveryOrder>>, TError,{id: string;data: BodyType<PatchDeliveryOrderInput>}, TContext> => {

const mutationKey = ['patchDeliveryOrder'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchDeliveryOrder>>, {id: string;data: BodyType<PatchDeliveryOrderInput>}> = (props) => {
          const {id,data} = props ?? {};

          return  patchDeliveryOrder(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PatchDeliveryOrderMutationResult = NonNullable<Awaited<ReturnType<typeof patchDeliveryOrder>>>
    export type PatchDeliveryOrderMutationBody = BodyType<PatchDeliveryOrderInput>
    export type PatchDeliveryOrderMutationError = ErrorType<UnauthorizedResponse | ForbiddenResponse | NotFoundResponse | ConflictResponse | ServiceUnavailableResponse>

    /**
 * @summary Update delivery order status, courier or notes
 */
export const usePatchDeliveryOrder = <TError = ErrorType<UnauthorizedResponse | ForbiddenResponse | NotFoundResponse | ConflictResponse | ServiceUnavailableResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchDeliveryOrder>>, TError,{id: string;data: BodyType<PatchDeliveryOrderInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof patchDeliveryOrder>>,
        TError,
        {id: string;data: BodyType<PatchDeliveryOrderInput>},
        TContext
      > => {
      return useMutation(getPatchDeliveryOrderMutationOptions(options));
    }

export const getGetDeliveryOrderHistoryUrl = (id: string,) => {




  return `/api/delivery-orders/${id}/history`
}

/**
 * @summary List status history for a delivery order
 */
export const getDeliveryOrderHistory = async (id: string, options?: RequestInit): Promise<DeliveryOrderStatusHistory[]> => {

  return customFetch<DeliveryOrderStatusHistory[]>(getGetDeliveryOrderHistoryUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetDeliveryOrderHistoryQueryKey = (id: string,) => {
    return [
    `/api/delivery-orders/${id}/history`
    ] as const;
    }


export const getGetDeliveryOrderHistoryQueryOptions = <TData = Awaited<ReturnType<typeof getDeliveryOrderHistory>>, TError = ErrorType<UnauthorizedResponse | ForbiddenResponse | ServiceUnavailableResponse>>(id: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getDeliveryOrderHistory>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetDeliveryOrderHistoryQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getDeliveryOrderHistory>>> = ({ signal }) => getDeliveryOrderHistory(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getDeliveryOrderHistory>>, TError, TData> & { queryKey: QueryKey }
}

export type GetDeliveryOrderHistoryQueryResult = NonNullable<Awaited<ReturnType<typeof getDeliveryOrderHistory>>>
export type GetDeliveryOrderHistoryQueryError = ErrorType<UnauthorizedResponse | ForbiddenResponse | ServiceUnavailableResponse>


/**
 * @summary List status history for a delivery order
 */

export function useGetDeliveryOrderHistory<TData = Awaited<ReturnType<typeof getDeliveryOrderHistory>>, TError = ErrorType<UnauthorizedResponse | ForbiddenResponse | ServiceUnavailableResponse>>(
 id: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getDeliveryOrderHistory>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetDeliveryOrderHistoryQueryOptions(id,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}







export const getGetOnlineOrdersInboxUrl = (params?: GetOnlineOrdersInboxParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/online-orders?${stringifiedParams}` : `/api/online-orders`
}

/**
 * @summary Online orders inbox for TPV staff
 */
export const getOnlineOrdersInbox = async (params?: GetOnlineOrdersInboxParams, options?: RequestInit): Promise<OnlineOrderInboxItem[]> => {

  return customFetch<OnlineOrderInboxItem[]>(getGetOnlineOrdersInboxUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetOnlineOrdersInboxQueryKey = (params?: GetOnlineOrdersInboxParams,) => {
    return [
    `/api/online-orders`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetOnlineOrdersInboxQueryOptions = <TData = Awaited<ReturnType<typeof getOnlineOrdersInbox>>, TError = ErrorType<UnauthorizedResponse | ForbiddenResponse | ServiceUnavailableResponse>>(params?: GetOnlineOrdersInboxParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getOnlineOrdersInbox>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetOnlineOrdersInboxQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getOnlineOrdersInbox>>> = ({ signal }) => getOnlineOrdersInbox(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getOnlineOrdersInbox>>, TError, TData> & { queryKey: QueryKey }
}

export type GetOnlineOrdersInboxQueryResult = NonNullable<Awaited<ReturnType<typeof getOnlineOrdersInbox>>>
export type GetOnlineOrdersInboxQueryError = ErrorType<UnauthorizedResponse | ForbiddenResponse | ServiceUnavailableResponse>


/**
 * @summary Online orders inbox for TPV staff
 */

export function useGetOnlineOrdersInbox<TData = Awaited<ReturnType<typeof getOnlineOrdersInbox>>, TError = ErrorType<UnauthorizedResponse | ForbiddenResponse | ServiceUnavailableResponse>>(
 params?: GetOnlineOrdersInboxParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getOnlineOrdersInbox>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetOnlineOrdersInboxQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}







export const getConfirmOnlineOrderUrl = (id: string,) => {




  return `/api/online-orders/${id}/confirm`
}

/**
 * @summary Confirm an online order (manager)
 */
export const confirmOnlineOrder = async (id: string,
    confirmOnlineOrderInput?: ConfirmOnlineOrderInput, options?: RequestInit): Promise<OnlineOrderConfirmResult> => {

  return customFetch<OnlineOrderConfirmResult>(getConfirmOnlineOrderUrl(id),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(confirmOnlineOrderInput)
  }
);}





export const getConfirmOnlineOrderMutationOptions = <TError = ErrorType<UnauthorizedResponse | ForbiddenResponse | NotFoundResponse | ConflictResponse | ServiceUnavailableResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof confirmOnlineOrder>>, TError,{id: string;data?: BodyType<ConfirmOnlineOrderInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof confirmOnlineOrder>>, TError,{id: string;data?: BodyType<ConfirmOnlineOrderInput>}, TContext> => {

const mutationKey = ['confirmOnlineOrder'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof confirmOnlineOrder>>, {id: string;data?: BodyType<ConfirmOnlineOrderInput>}> = (props) => {
          const {id,data} = props ?? {};

          return  confirmOnlineOrder(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ConfirmOnlineOrderMutationResult = NonNullable<Awaited<ReturnType<typeof confirmOnlineOrder>>>
    export type ConfirmOnlineOrderMutationBody = BodyType<ConfirmOnlineOrderInput> | undefined
    export type ConfirmOnlineOrderMutationError = ErrorType<UnauthorizedResponse | ForbiddenResponse | NotFoundResponse | ConflictResponse | ServiceUnavailableResponse>

    /**
 * @summary Confirm an online order (manager)
 */
export const useConfirmOnlineOrder = <TError = ErrorType<UnauthorizedResponse | ForbiddenResponse | NotFoundResponse | ConflictResponse | ServiceUnavailableResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof confirmOnlineOrder>>, TError,{id: string;data?: BodyType<ConfirmOnlineOrderInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof confirmOnlineOrder>>,
        TError,
        {id: string;data?: BodyType<ConfirmOnlineOrderInput>},
        TContext
      > => {
      return useMutation(getConfirmOnlineOrderMutationOptions(options));
    }

export const getRejectOnlineOrderUrl = (id: string,) => {




  return `/api/online-orders/${id}/reject`
}

/**
 * @summary Reject an online order with reason
 */
export const rejectOnlineOrder = async (id: string,
    rejectOnlineOrderInput: RejectOnlineOrderInput, options?: RequestInit): Promise<OnlineOrderRejectResult> => {

  return customFetch<OnlineOrderRejectResult>(getRejectOnlineOrderUrl(id),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(rejectOnlineOrderInput)
  }
);}





export const getRejectOnlineOrderMutationOptions = <TError = ErrorType<BadRequestResponse | UnauthorizedResponse | ForbiddenResponse | NotFoundResponse | ServiceUnavailableResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof rejectOnlineOrder>>, TError,{id: string;data: BodyType<RejectOnlineOrderInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof rejectOnlineOrder>>, TError,{id: string;data: BodyType<RejectOnlineOrderInput>}, TContext> => {

const mutationKey = ['rejectOnlineOrder'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof rejectOnlineOrder>>, {id: string;data: BodyType<RejectOnlineOrderInput>}> = (props) => {
          const {id,data} = props ?? {};

          return  rejectOnlineOrder(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type RejectOnlineOrderMutationResult = NonNullable<Awaited<ReturnType<typeof rejectOnlineOrder>>>
    export type RejectOnlineOrderMutationBody = BodyType<RejectOnlineOrderInput>
    export type RejectOnlineOrderMutationError = ErrorType<BadRequestResponse | UnauthorizedResponse | ForbiddenResponse | NotFoundResponse | ServiceUnavailableResponse>

    /**
 * @summary Reject an online order with reason
 */
export const useRejectOnlineOrder = <TError = ErrorType<BadRequestResponse | UnauthorizedResponse | ForbiddenResponse | NotFoundResponse | ServiceUnavailableResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof rejectOnlineOrder>>, TError,{id: string;data: BodyType<RejectOnlineOrderInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof rejectOnlineOrder>>,
        TError,
        {id: string;data: BodyType<RejectOnlineOrderInput>},
        TContext
      > => {
      return useMutation(getRejectOnlineOrderMutationOptions(options));
    }

export const getPatchOnlineOrderStatusUrl = (id: string,) => {




  return `/api/online-orders/${id}/status`
}

/**
 * @summary Change online order status
 */
export const patchOnlineOrderStatus = async (id: string,
    patchOnlineOrderStatusInput: PatchOnlineOrderStatusInput, options?: RequestInit): Promise<OnlineOrderStatusResult> => {

  return customFetch<OnlineOrderStatusResult>(getPatchOnlineOrderStatusUrl(id),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(patchOnlineOrderStatusInput)
  }
);}





export const getPatchOnlineOrderStatusMutationOptions = <TError = ErrorType<BadRequestResponse | UnauthorizedResponse | ForbiddenResponse | NotFoundResponse | ServiceUnavailableResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchOnlineOrderStatus>>, TError,{id: string;data: BodyType<PatchOnlineOrderStatusInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof patchOnlineOrderStatus>>, TError,{id: string;data: BodyType<PatchOnlineOrderStatusInput>}, TContext> => {

const mutationKey = ['patchOnlineOrderStatus'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchOnlineOrderStatus>>, {id: string;data: BodyType<PatchOnlineOrderStatusInput>}> = (props) => {
          const {id,data} = props ?? {};

          return  patchOnlineOrderStatus(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PatchOnlineOrderStatusMutationResult = NonNullable<Awaited<ReturnType<typeof patchOnlineOrderStatus>>>
    export type PatchOnlineOrderStatusMutationBody = BodyType<PatchOnlineOrderStatusInput>
    export type PatchOnlineOrderStatusMutationError = ErrorType<BadRequestResponse | UnauthorizedResponse | ForbiddenResponse | NotFoundResponse | ServiceUnavailableResponse>

    /**
 * @summary Change online order status
 */
export const usePatchOnlineOrderStatus = <TError = ErrorType<BadRequestResponse | UnauthorizedResponse | ForbiddenResponse | NotFoundResponse | ServiceUnavailableResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchOnlineOrderStatus>>, TError,{id: string;data: BodyType<PatchOnlineOrderStatusInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof patchOnlineOrderStatus>>,
        TError,
        {id: string;data: BodyType<PatchOnlineOrderStatusInput>},
        TContext
      > => {
      return useMutation(getPatchOnlineOrderStatusMutationOptions(options));
    }

export const getSimulateOnlineOrderPaymentUrl = (id: string,) => {




  return `/api/online-orders/${id}/payment-simulate`
}

/**
 * @summary Simulate online payment approval (non-production)
 */
export const simulateOnlineOrderPayment = async (id: string,
    paymentSimulateInput?: PaymentSimulateInput, options?: RequestInit): Promise<PaymentSimulateResult> => {

  return customFetch<PaymentSimulateResult>(getSimulateOnlineOrderPaymentUrl(id),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(paymentSimulateInput)
  }
);}





export const getSimulateOnlineOrderPaymentMutationOptions = <TError = ErrorType<UnauthorizedResponse | ForbiddenResponse | NotFoundResponse | ConflictResponse | ServiceUnavailableResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof simulateOnlineOrderPayment>>, TError,{id: string;data?: BodyType<PaymentSimulateInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof simulateOnlineOrderPayment>>, TError,{id: string;data?: BodyType<PaymentSimulateInput>}, TContext> => {

const mutationKey = ['simulateOnlineOrderPayment'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof simulateOnlineOrderPayment>>, {id: string;data?: BodyType<PaymentSimulateInput>}> = (props) => {
          const {id,data} = props ?? {};

          return  simulateOnlineOrderPayment(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type SimulateOnlineOrderPaymentMutationResult = NonNullable<Awaited<ReturnType<typeof simulateOnlineOrderPayment>>>
    export type SimulateOnlineOrderPaymentMutationBody = BodyType<PaymentSimulateInput> | undefined
    export type SimulateOnlineOrderPaymentMutationError = ErrorType<UnauthorizedResponse | ForbiddenResponse | NotFoundResponse | ConflictResponse | ServiceUnavailableResponse>

    /**
 * @summary Simulate online payment approval (non-production)
 */
export const useSimulateOnlineOrderPayment = <TError = ErrorType<UnauthorizedResponse | ForbiddenResponse | NotFoundResponse | ConflictResponse | ServiceUnavailableResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof simulateOnlineOrderPayment>>, TError,{id: string;data?: BodyType<PaymentSimulateInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof simulateOnlineOrderPayment>>,
        TError,
        {id: string;data?: BodyType<PaymentSimulateInput>},
        TContext
      > => {
      return useMutation(getSimulateOnlineOrderPaymentMutationOptions(options));
    }

export const getAssignOnlineOrderCourierUrl = (id: string,) => {




  return `/api/online-orders/${id}/assign-courier`
}

/**
 * @summary Assign a courier to an online order
 */
export const assignOnlineOrderCourier = async (id: string,
    assignCourierInput: AssignCourierInput, options?: RequestInit): Promise<AssignCourierResult> => {

  return customFetch<AssignCourierResult>(getAssignOnlineOrderCourierUrl(id),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(assignCourierInput)
  }
);}





export const getAssignOnlineOrderCourierMutationOptions = <TError = ErrorType<UnauthorizedResponse | ForbiddenResponse | NotFoundResponse | ServiceUnavailableResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof assignOnlineOrderCourier>>, TError,{id: string;data: BodyType<AssignCourierInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof assignOnlineOrderCourier>>, TError,{id: string;data: BodyType<AssignCourierInput>}, TContext> => {

const mutationKey = ['assignOnlineOrderCourier'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof assignOnlineOrderCourier>>, {id: string;data: BodyType<AssignCourierInput>}> = (props) => {
          const {id,data} = props ?? {};

          return  assignOnlineOrderCourier(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AssignOnlineOrderCourierMutationResult = NonNullable<Awaited<ReturnType<typeof assignOnlineOrderCourier>>>
    export type AssignOnlineOrderCourierMutationBody = BodyType<AssignCourierInput>
    export type AssignOnlineOrderCourierMutationError = ErrorType<UnauthorizedResponse | ForbiddenResponse | NotFoundResponse | ServiceUnavailableResponse>

    /**
 * @summary Assign a courier to an online order
 */
export const useAssignOnlineOrderCourier = <TError = ErrorType<UnauthorizedResponse | ForbiddenResponse | NotFoundResponse | ServiceUnavailableResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof assignOnlineOrderCourier>>, TError,{id: string;data: BodyType<AssignCourierInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof assignOnlineOrderCourier>>,
        TError,
        {id: string;data: BodyType<AssignCourierInput>},
        TContext
      > => {
      return useMutation(getAssignOnlineOrderCourierMutationOptions(options));
    }

export const getCheckOnlineOrderPackagingUrl = (id: string,) => {




  return `/api/online-orders/${id}/packaging-check`
}

/**
 * @summary Mark packaging as checked for an online order
 */
export const checkOnlineOrderPackaging = async (id: string, options?: RequestInit): Promise<OkResponse> => {

  return customFetch<OkResponse>(getCheckOnlineOrderPackagingUrl(id),
  {
    ...options,
    method: 'POST'


  }
);}





export const getCheckOnlineOrderPackagingMutationOptions = <TError = ErrorType<UnauthorizedResponse | ForbiddenResponse | ServiceUnavailableResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof checkOnlineOrderPackaging>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof checkOnlineOrderPackaging>>, TError,{id: string}, TContext> => {

const mutationKey = ['checkOnlineOrderPackaging'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof checkOnlineOrderPackaging>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  checkOnlineOrderPackaging(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CheckOnlineOrderPackagingMutationResult = NonNullable<Awaited<ReturnType<typeof checkOnlineOrderPackaging>>>

    export type CheckOnlineOrderPackagingMutationError = ErrorType<UnauthorizedResponse | ForbiddenResponse | ServiceUnavailableResponse>

    /**
 * @summary Mark packaging as checked for an online order
 */
export const useCheckOnlineOrderPackaging = <TError = ErrorType<UnauthorizedResponse | ForbiddenResponse | ServiceUnavailableResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof checkOnlineOrderPackaging>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof checkOnlineOrderPackaging>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getCheckOnlineOrderPackagingMutationOptions(options));
    }

export const getGetAdminOnlineConfigUrl = () => {




  return `/api/admin/online-config`
}

/**
 * @summary Get online delivery configuration with zones and couriers
 */
export const getAdminOnlineConfig = async ( options?: RequestInit): Promise<AdminOnlineConfigResponse> => {

  return customFetch<AdminOnlineConfigResponse>(getGetAdminOnlineConfigUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetAdminOnlineConfigQueryKey = () => {
    return [
    `/api/admin/online-config`
    ] as const;
    }


export const getGetAdminOnlineConfigQueryOptions = <TData = Awaited<ReturnType<typeof getAdminOnlineConfig>>, TError = ErrorType<UnauthorizedResponse | ForbiddenResponse | ServiceUnavailableResponse>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getAdminOnlineConfig>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAdminOnlineConfigQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAdminOnlineConfig>>> = ({ signal }) => getAdminOnlineConfig({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAdminOnlineConfig>>, TError, TData> & { queryKey: QueryKey }
}

export type GetAdminOnlineConfigQueryResult = NonNullable<Awaited<ReturnType<typeof getAdminOnlineConfig>>>
export type GetAdminOnlineConfigQueryError = ErrorType<UnauthorizedResponse | ForbiddenResponse | ServiceUnavailableResponse>


/**
 * @summary Get online delivery configuration with zones and couriers
 */

export function useGetAdminOnlineConfig<TData = Awaited<ReturnType<typeof getAdminOnlineConfig>>, TError = ErrorType<UnauthorizedResponse | ForbiddenResponse | ServiceUnavailableResponse>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getAdminOnlineConfig>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetAdminOnlineConfigQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}







export const getPatchAdminOnlineConfigUrl = () => {




  return `/api/admin/online-config`
}

/**
 * @summary Update online delivery configuration (admin only)
 */
export const patchAdminOnlineConfig = async (patchOnlineConfigInput: PatchOnlineConfigInput, options?: RequestInit): Promise<OnlineOrdersConfigMasked> => {

  return customFetch<OnlineOrdersConfigMasked>(getPatchAdminOnlineConfigUrl(),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(patchOnlineConfigInput)
  }
);}





export const getPatchAdminOnlineConfigMutationOptions = <TError = ErrorType<BadRequestResponse | UnauthorizedResponse | ForbiddenResponse | ServiceUnavailableResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchAdminOnlineConfig>>, TError,{data: BodyType<PatchOnlineConfigInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof patchAdminOnlineConfig>>, TError,{data: BodyType<PatchOnlineConfigInput>}, TContext> => {

const mutationKey = ['patchAdminOnlineConfig'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchAdminOnlineConfig>>, {data: BodyType<PatchOnlineConfigInput>}> = (props) => {
          const {data} = props ?? {};

          return  patchAdminOnlineConfig(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PatchAdminOnlineConfigMutationResult = NonNullable<Awaited<ReturnType<typeof patchAdminOnlineConfig>>>
    export type PatchAdminOnlineConfigMutationBody = BodyType<PatchOnlineConfigInput>
    export type PatchAdminOnlineConfigMutationError = ErrorType<BadRequestResponse | UnauthorizedResponse | ForbiddenResponse | ServiceUnavailableResponse>

    /**
 * @summary Update online delivery configuration (admin only)
 */
export const usePatchAdminOnlineConfig = <TError = ErrorType<BadRequestResponse | UnauthorizedResponse | ForbiddenResponse | ServiceUnavailableResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchAdminOnlineConfig>>, TError,{data: BodyType<PatchOnlineConfigInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof patchAdminOnlineConfig>>,
        TError,
        {data: BodyType<PatchOnlineConfigInput>},
        TContext
      > => {
      return useMutation(getPatchAdminOnlineConfigMutationOptions(options));
    }

export const getGetDeliveryZonesUrl = () => {




  return `/api/admin/delivery-zones`
}

/**
 * @summary List delivery zones
 */
export const getDeliveryZones = async ( options?: RequestInit): Promise<DeliveryZone[]> => {

  return customFetch<DeliveryZone[]>(getGetDeliveryZonesUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetDeliveryZonesQueryKey = () => {
    return [
    `/api/admin/delivery-zones`
    ] as const;
    }


export const getGetDeliveryZonesQueryOptions = <TData = Awaited<ReturnType<typeof getDeliveryZones>>, TError = ErrorType<UnauthorizedResponse | ForbiddenResponse | ServiceUnavailableResponse>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getDeliveryZones>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetDeliveryZonesQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getDeliveryZones>>> = ({ signal }) => getDeliveryZones({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getDeliveryZones>>, TError, TData> & { queryKey: QueryKey }
}

export type GetDeliveryZonesQueryResult = NonNullable<Awaited<ReturnType<typeof getDeliveryZones>>>
export type GetDeliveryZonesQueryError = ErrorType<UnauthorizedResponse | ForbiddenResponse | ServiceUnavailableResponse>


/**
 * @summary List delivery zones
 */

export function useGetDeliveryZones<TData = Awaited<ReturnType<typeof getDeliveryZones>>, TError = ErrorType<UnauthorizedResponse | ForbiddenResponse | ServiceUnavailableResponse>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getDeliveryZones>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetDeliveryZonesQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}







export const getCreateDeliveryZoneUrl = () => {




  return `/api/admin/delivery-zones`
}

/**
 * @summary Create a delivery zone
 */
export const createDeliveryZone = async (createDeliveryZoneInput: CreateDeliveryZoneInput, options?: RequestInit): Promise<DeliveryZone> => {

  return customFetch<DeliveryZone>(getCreateDeliveryZoneUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createDeliveryZoneInput)
  }
);}





export const getCreateDeliveryZoneMutationOptions = <TError = ErrorType<BadRequestResponse | UnauthorizedResponse | ForbiddenResponse | ServiceUnavailableResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createDeliveryZone>>, TError,{data: BodyType<CreateDeliveryZoneInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof createDeliveryZone>>, TError,{data: BodyType<CreateDeliveryZoneInput>}, TContext> => {

const mutationKey = ['createDeliveryZone'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createDeliveryZone>>, {data: BodyType<CreateDeliveryZoneInput>}> = (props) => {
          const {data} = props ?? {};

          return  createDeliveryZone(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateDeliveryZoneMutationResult = NonNullable<Awaited<ReturnType<typeof createDeliveryZone>>>
    export type CreateDeliveryZoneMutationBody = BodyType<CreateDeliveryZoneInput>
    export type CreateDeliveryZoneMutationError = ErrorType<BadRequestResponse | UnauthorizedResponse | ForbiddenResponse | ServiceUnavailableResponse>

    /**
 * @summary Create a delivery zone
 */
export const useCreateDeliveryZone = <TError = ErrorType<BadRequestResponse | UnauthorizedResponse | ForbiddenResponse | ServiceUnavailableResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createDeliveryZone>>, TError,{data: BodyType<CreateDeliveryZoneInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof createDeliveryZone>>,
        TError,
        {data: BodyType<CreateDeliveryZoneInput>},
        TContext
      > => {
      return useMutation(getCreateDeliveryZoneMutationOptions(options));
    }

export const getPatchDeliveryZoneUrl = (id: string,) => {




  return `/api/admin/delivery-zones/${id}`
}

/**
 * @summary Partially update a delivery zone
 */
export const patchDeliveryZone = async (id: string,
    patchDeliveryZoneInput: PatchDeliveryZoneInput, options?: RequestInit): Promise<DeliveryZone> => {

  return customFetch<DeliveryZone>(getPatchDeliveryZoneUrl(id),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(patchDeliveryZoneInput)
  }
);}





export const getPatchDeliveryZoneMutationOptions = <TError = ErrorType<UnauthorizedResponse | ForbiddenResponse | NotFoundResponse | ServiceUnavailableResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchDeliveryZone>>, TError,{id: string;data: BodyType<PatchDeliveryZoneInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof patchDeliveryZone>>, TError,{id: string;data: BodyType<PatchDeliveryZoneInput>}, TContext> => {

const mutationKey = ['patchDeliveryZone'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchDeliveryZone>>, {id: string;data: BodyType<PatchDeliveryZoneInput>}> = (props) => {
          const {id,data} = props ?? {};

          return  patchDeliveryZone(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PatchDeliveryZoneMutationResult = NonNullable<Awaited<ReturnType<typeof patchDeliveryZone>>>
    export type PatchDeliveryZoneMutationBody = BodyType<PatchDeliveryZoneInput>
    export type PatchDeliveryZoneMutationError = ErrorType<UnauthorizedResponse | ForbiddenResponse | NotFoundResponse | ServiceUnavailableResponse>

    /**
 * @summary Partially update a delivery zone
 */
export const usePatchDeliveryZone = <TError = ErrorType<UnauthorizedResponse | ForbiddenResponse | NotFoundResponse | ServiceUnavailableResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchDeliveryZone>>, TError,{id: string;data: BodyType<PatchDeliveryZoneInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof patchDeliveryZone>>,
        TError,
        {id: string;data: BodyType<PatchDeliveryZoneInput>},
        TContext
      > => {
      return useMutation(getPatchDeliveryZoneMutationOptions(options));
    }

export const getDeleteDeliveryZoneUrl = (id: string,) => {




  return `/api/admin/delivery-zones/${id}`
}

/**
 * @summary Soft-delete a delivery zone
 */
export const deleteDeliveryZone = async (id: string, options?: RequestInit): Promise<OkResponse> => {

  return customFetch<OkResponse>(getDeleteDeliveryZoneUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}





export const getDeleteDeliveryZoneMutationOptions = <TError = ErrorType<UnauthorizedResponse | ForbiddenResponse | ServiceUnavailableResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteDeliveryZone>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteDeliveryZone>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteDeliveryZone'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteDeliveryZone>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteDeliveryZone(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteDeliveryZoneMutationResult = NonNullable<Awaited<ReturnType<typeof deleteDeliveryZone>>>

    export type DeleteDeliveryZoneMutationError = ErrorType<UnauthorizedResponse | ForbiddenResponse | ServiceUnavailableResponse>

    /**
 * @summary Soft-delete a delivery zone
 */
export const useDeleteDeliveryZone = <TError = ErrorType<UnauthorizedResponse | ForbiddenResponse | ServiceUnavailableResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteDeliveryZone>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof deleteDeliveryZone>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getDeleteDeliveryZoneMutationOptions(options));
    }

export const getGetCouriersUrl = () => {




  return `/api/admin/couriers`
}

/**
 * @summary List active couriers (token stripped)
 */
export const getCouriers = async ( options?: RequestInit): Promise<CourierSafe[]> => {

  return customFetch<CourierSafe[]>(getGetCouriersUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetCouriersQueryKey = () => {
    return [
    `/api/admin/couriers`
    ] as const;
    }


export const getGetCouriersQueryOptions = <TData = Awaited<ReturnType<typeof getCouriers>>, TError = ErrorType<UnauthorizedResponse | ForbiddenResponse | ServiceUnavailableResponse>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getCouriers>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetCouriersQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getCouriers>>> = ({ signal }) => getCouriers({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getCouriers>>, TError, TData> & { queryKey: QueryKey }
}

export type GetCouriersQueryResult = NonNullable<Awaited<ReturnType<typeof getCouriers>>>
export type GetCouriersQueryError = ErrorType<UnauthorizedResponse | ForbiddenResponse | ServiceUnavailableResponse>


/**
 * @summary List active couriers (token stripped)
 */

export function useGetCouriers<TData = Awaited<ReturnType<typeof getCouriers>>, TError = ErrorType<UnauthorizedResponse | ForbiddenResponse | ServiceUnavailableResponse>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getCouriers>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetCouriersQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}







export const getCreateCourierUrl = () => {




  return `/api/admin/couriers`
}

/**
 * @summary Create a courier
 */
export const createCourier = async (createCourierInput: CreateCourierInput, options?: RequestInit): Promise<CourierSafe> => {

  return customFetch<CourierSafe>(getCreateCourierUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createCourierInput)
  }
);}





export const getCreateCourierMutationOptions = <TError = ErrorType<BadRequestResponse | UnauthorizedResponse | ForbiddenResponse | ServiceUnavailableResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createCourier>>, TError,{data: BodyType<CreateCourierInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof createCourier>>, TError,{data: BodyType<CreateCourierInput>}, TContext> => {

const mutationKey = ['createCourier'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createCourier>>, {data: BodyType<CreateCourierInput>}> = (props) => {
          const {data} = props ?? {};

          return  createCourier(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateCourierMutationResult = NonNullable<Awaited<ReturnType<typeof createCourier>>>
    export type CreateCourierMutationBody = BodyType<CreateCourierInput>
    export type CreateCourierMutationError = ErrorType<BadRequestResponse | UnauthorizedResponse | ForbiddenResponse | ServiceUnavailableResponse>

    /**
 * @summary Create a courier
 */
export const useCreateCourier = <TError = ErrorType<BadRequestResponse | UnauthorizedResponse | ForbiddenResponse | ServiceUnavailableResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createCourier>>, TError,{data: BodyType<CreateCourierInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof createCourier>>,
        TError,
        {data: BodyType<CreateCourierInput>},
        TContext
      > => {
      return useMutation(getCreateCourierMutationOptions(options));
    }

export const getPatchCourierUrl = (id: string,) => {




  return `/api/admin/couriers/${id}`
}

/**
 * @summary Partially update a courier
 */
export const patchCourier = async (id: string,
    patchCourierInput: PatchCourierInput, options?: RequestInit): Promise<CourierSafe> => {

  return customFetch<CourierSafe>(getPatchCourierUrl(id),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(patchCourierInput)
  }
);}





export const getPatchCourierMutationOptions = <TError = ErrorType<UnauthorizedResponse | ForbiddenResponse | NotFoundResponse | ServiceUnavailableResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchCourier>>, TError,{id: string;data: BodyType<PatchCourierInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof patchCourier>>, TError,{id: string;data: BodyType<PatchCourierInput>}, TContext> => {

const mutationKey = ['patchCourier'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchCourier>>, {id: string;data: BodyType<PatchCourierInput>}> = (props) => {
          const {id,data} = props ?? {};

          return  patchCourier(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PatchCourierMutationResult = NonNullable<Awaited<ReturnType<typeof patchCourier>>>
    export type PatchCourierMutationBody = BodyType<PatchCourierInput>
    export type PatchCourierMutationError = ErrorType<UnauthorizedResponse | ForbiddenResponse | NotFoundResponse | ServiceUnavailableResponse>

    /**
 * @summary Partially update a courier
 */
export const usePatchCourier = <TError = ErrorType<UnauthorizedResponse | ForbiddenResponse | NotFoundResponse | ServiceUnavailableResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchCourier>>, TError,{id: string;data: BodyType<PatchCourierInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof patchCourier>>,
        TError,
        {id: string;data: BodyType<PatchCourierInput>},
        TContext
      > => {
      return useMutation(getPatchCourierMutationOptions(options));
    }

export const getDeleteCourierUrl = (id: string,) => {




  return `/api/admin/couriers/${id}`
}

/**
 * @summary Soft-delete a courier
 */
export const deleteCourier = async (id: string, options?: RequestInit): Promise<OkResponse> => {

  return customFetch<OkResponse>(getDeleteCourierUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}





export const getDeleteCourierMutationOptions = <TError = ErrorType<UnauthorizedResponse | ForbiddenResponse | ServiceUnavailableResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteCourier>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteCourier>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteCourier'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteCourier>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteCourier(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteCourierMutationResult = NonNullable<Awaited<ReturnType<typeof deleteCourier>>>

    export type DeleteCourierMutationError = ErrorType<UnauthorizedResponse | ForbiddenResponse | ServiceUnavailableResponse>

    /**
 * @summary Soft-delete a courier
 */
export const useDeleteCourier = <TError = ErrorType<UnauthorizedResponse | ForbiddenResponse | ServiceUnavailableResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteCourier>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof deleteCourier>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getDeleteCourierMutationOptions(options));
    }

export const getGetCourierSummaryUrl = (id: string,) => {




  return `/api/admin/couriers/${id}/summary`
}

/**
 * @summary Active shift summary for a courier
 */
export const getCourierSummary = async (id: string, options?: RequestInit): Promise<CourierAdminSummary> => {

  return customFetch<CourierAdminSummary>(getGetCourierSummaryUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetCourierSummaryQueryKey = (id: string,) => {
    return [
    `/api/admin/couriers/${id}/summary`
    ] as const;
    }


export const getGetCourierSummaryQueryOptions = <TData = Awaited<ReturnType<typeof getCourierSummary>>, TError = ErrorType<UnauthorizedResponse | ForbiddenResponse | NotFoundResponse | ServiceUnavailableResponse>>(id: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getCourierSummary>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetCourierSummaryQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getCourierSummary>>> = ({ signal }) => getCourierSummary(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getCourierSummary>>, TError, TData> & { queryKey: QueryKey }
}

export type GetCourierSummaryQueryResult = NonNullable<Awaited<ReturnType<typeof getCourierSummary>>>
export type GetCourierSummaryQueryError = ErrorType<UnauthorizedResponse | ForbiddenResponse | NotFoundResponse | ServiceUnavailableResponse>


/**
 * @summary Active shift summary for a courier
 */

export function useGetCourierSummary<TData = Awaited<ReturnType<typeof getCourierSummary>>, TError = ErrorType<UnauthorizedResponse | ForbiddenResponse | NotFoundResponse | ServiceUnavailableResponse>>(
 id: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getCourierSummary>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetCourierSummaryQueryOptions(id,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}







export const getSettleCourierUrl = (id: string,) => {




  return `/api/admin/couriers/${id}/settle`
}

/**
 * @summary Close courier shift and create settlement
 */
export const settleCourier = async (id: string,
    settleCourierInput?: SettleCourierInput, options?: RequestInit): Promise<SettleCourierResult> => {

  return customFetch<SettleCourierResult>(getSettleCourierUrl(id),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(settleCourierInput)
  }
);}





export const getSettleCourierMutationOptions = <TError = ErrorType<UnauthorizedResponse | ForbiddenResponse | NotFoundResponse | ServiceUnavailableResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof settleCourier>>, TError,{id: string;data?: BodyType<SettleCourierInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof settleCourier>>, TError,{id: string;data?: BodyType<SettleCourierInput>}, TContext> => {

const mutationKey = ['settleCourier'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof settleCourier>>, {id: string;data?: BodyType<SettleCourierInput>}> = (props) => {
          const {id,data} = props ?? {};

          return  settleCourier(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type SettleCourierMutationResult = NonNullable<Awaited<ReturnType<typeof settleCourier>>>
    export type SettleCourierMutationBody = BodyType<SettleCourierInput> | undefined
    export type SettleCourierMutationError = ErrorType<UnauthorizedResponse | ForbiddenResponse | NotFoundResponse | ServiceUnavailableResponse>

    /**
 * @summary Close courier shift and create settlement
 */
export const useSettleCourier = <TError = ErrorType<UnauthorizedResponse | ForbiddenResponse | NotFoundResponse | ServiceUnavailableResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof settleCourier>>, TError,{id: string;data?: BodyType<SettleCourierInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof settleCourier>>,
        TError,
        {id: string;data?: BodyType<SettleCourierInput>},
        TContext
      > => {
      return useMutation(getSettleCourierMutationOptions(options));
    }

export const getGetCourierSettlementsUrl = (params?: GetCourierSettlementsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/admin/courier-settlements?${stringifiedParams}` : `/api/admin/courier-settlements`
}

/**
 * @summary List courier settlements
 */
export const getCourierSettlements = async (params?: GetCourierSettlementsParams, options?: RequestInit): Promise<CourierSettlementWithName[]> => {

  return customFetch<CourierSettlementWithName[]>(getGetCourierSettlementsUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetCourierSettlementsQueryKey = (params?: GetCourierSettlementsParams,) => {
    return [
    `/api/admin/courier-settlements`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetCourierSettlementsQueryOptions = <TData = Awaited<ReturnType<typeof getCourierSettlements>>, TError = ErrorType<UnauthorizedResponse | ForbiddenResponse | ServiceUnavailableResponse>>(params?: GetCourierSettlementsParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getCourierSettlements>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetCourierSettlementsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getCourierSettlements>>> = ({ signal }) => getCourierSettlements(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getCourierSettlements>>, TError, TData> & { queryKey: QueryKey }
}

export type GetCourierSettlementsQueryResult = NonNullable<Awaited<ReturnType<typeof getCourierSettlements>>>
export type GetCourierSettlementsQueryError = ErrorType<UnauthorizedResponse | ForbiddenResponse | ServiceUnavailableResponse>


/**
 * @summary List courier settlements
 */

export function useGetCourierSettlements<TData = Awaited<ReturnType<typeof getCourierSettlements>>, TError = ErrorType<UnauthorizedResponse | ForbiddenResponse | ServiceUnavailableResponse>>(
 params?: GetCourierSettlementsParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getCourierSettlements>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetCourierSettlementsQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}







