/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Api
 * Piccolo TPV API
 * OpenAPI spec version: 0.2.0
 */
export interface UpdateOrderItemInput {
  /** @minimum 1 */
  quantity?: number;
  notes?: string;
  allergyNote?: string;
  hasAllergy?: boolean;
  isInvitation?: boolean;
}

export interface OrderItemModifier {
  id: string;
  orderItemId: string;
  modifierId?: string;
  modifierName: string;
  priceDelta: string;
}

export interface OrderItem {
  id: string;
  orderId: string;
  productId: string;
  productName: string;
  formatId?: string | null;
  formatName?: string | null;
  quantity: number;
  unitPrice: string;
  status: string;
  notes: string;
  allergyNote: string;
  hasAllergy: boolean;
  isInvitation: boolean;
  modifiers?: OrderItemModifier[];
  createdAt: string;
}

export interface ErrorResponse {
  error: string;
}

export type UpdateTaskStatusInputStatus = typeof UpdateTaskStatusInputStatus[keyof typeof UpdateTaskStatusInputStatus];


export const UpdateTaskStatusInputStatus = {
  new: 'new',
  preparing: 'preparing',
  in_oven: 'in_oven',
  ready: 'ready',
  collected: 'collected',
  served: 'served',
  cancelled: 'cancelled',
} as const;

export interface UpdateTaskStatusInput {
  status: UpdateTaskStatusInputStatus;
}

export type KitchenTaskRecordStatus = typeof KitchenTaskRecordStatus[keyof typeof KitchenTaskRecordStatus];


export const KitchenTaskRecordStatus = {
  new: 'new',
  preparing: 'preparing',
  in_oven: 'in_oven',
  ready: 'ready',
  collected: 'collected',
  served: 'served',
  cancelled: 'cancelled',
} as const;

export interface KitchenTaskRecord {
  id: string;
  orderId: string;
  orderItemId: string;
  prepZone: string;
  productName: string;
  quantity: number;
  status: KitchenTaskRecordStatus;
  notes: string;
  allergyNote: string;
  hasAllergy: boolean;
  createdAt: string;
  updatedAt: string;
  readyAt: string | null;
  collectedAt: string | null;
  servedAt: string | null;
  cancelledAt: string | null;
}

export interface ValidationError {
  error: string;
  from?: string;
  to?: string;
  zone?: string;
  allowed?: string[];
}

export type UpdateOrderInputStatus = typeof UpdateOrderInputStatus[keyof typeof UpdateOrderInputStatus];


export const UpdateOrderInputStatus = {
  open: 'open',
  bill_requested: 'bill_requested',
} as const;

export interface UpdateOrderInput {
  /** @minimum 1 */
  guestCount?: number;
  notes?: string;
  status?: UpdateOrderInputStatus;
}

/**
 * @pattern ^-?\d+\.\d{2}$
 */
export type Money = string;

export interface Order {
  id: string;
  tableId: string | null;
  employeeId: string | null;
  orderType: string;
  status: string;
  guestCount: number;
  notes: string;
  clientName: string;
  clientId?: string | null;
  openedByTerminal: string;
  createdAt: string;
  sentAt: string | null;
  channel: string;
  deliveryType: string;
  orderNumber: string | null;
  scheduledAt: string | null;
  estimatedReadyAt: string | null;
  clientPhone: string;
  deliveryAddressId: string | null;
  courierId: string | null;
  rejectionReason: string | null;
  onlinePaymentRef: string | null;
  onlinePaymentStatus: string;
  packagingCheckedBy: string | null;
  packagingCheckedAt: string | null;
  deliveryFee: Money;
  tipAmount: Money;
  idempotencyKey: string | null;
  tableSessionId: string | null;
  isDemo: boolean;
  items?: OrderItem[];
}

export interface AuditLogEntry {
  id: string;
  orderId?: string | null;
  employeeId?: string | null;
  employeeName: string;
  action: string;
  details: string;
  createdAt: string;
}

export interface OccupationSummary {
  freeCount: number;
  occupiedCount: number;
  reservedCount: number;
  pendingCleaningCount: number;
  blockedCount: number;
  currentGuests: number;
  pendingReservations: number;
  avgOccupationMinutes: number;
}

/**
 * Event-specific metadata persisted as JSON by the existing event logger.
 */
export type TableEventMetadata = { [key: string]: unknown } | null;

export interface TableEvent {
  id: string;
  tableId: string;
  orderId?: string | null;
  employeeId?: string | null;
  employeeName: string;
  action: string;
  details: string;
  /** Event-specific metadata persisted as JSON by the existing event logger. */
  metadata?: TableEventMetadata;
  createdAt: string;
}

export interface AlertConfig {
  id: string;
  /** @minimum 1 */
  reservaProximaMin: number;
  /** @minimum 1 */
  sinComandaMin: number;
  /** @minimum 1 */
  prefacturaPendienteMin: number;
  /** @minimum 1 */
  mesaSuciaMin: number;
  updatedAt: string;
}

export interface UpdateAlertConfigInput {
  /** @minimum 1 */
  reservaProximaMin?: number;
  /** @minimum 1 */
  sinComandaMin?: number;
  /** @minimum 1 */
  prefacturaPendienteMin?: number;
  /** @minimum 1 */
  mesaSuciaMin?: number;
}

export type TableStatus = typeof TableStatus[keyof typeof TableStatus];


export const TableStatus = {
  free: 'free',
  reserved: 'reserved',
  occupied: 'occupied',
  pendiente_limpieza: 'pendiente_limpieza',
  bloqueada: 'bloqueada',
  out_of_service: 'out_of_service',
  comanda_abierta: 'comanda_abierta',
  prefactura_impresa: 'prefactura_impresa',
  pendiente_cobro: 'pendiente_cobro',
  parcialmente_cobrada: 'parcialmente_cobrada',
  waiting: 'waiting',
  bill_requested: 'bill_requested',
} as const;

export interface Table {
  id: string;
  zoneId: string;
  name: string;
  capacity: number;
  status: TableStatus;
  x: number;
  y: number;
  width: number;
  height: number;
  shape: string;
  rotation: number;
  layout: string;
  mergeGroup?: string | null;
  currentOrderId: string | null;
  openedAt: string | null;
  employeeName: string | null;
  currentTotal: number | null;
  active: boolean;
  guestCount: number | null;
  clientName: string | null;
}

export interface TableIdInput {
  targetTableId: string;
}

export interface TableTransferResult {
  success: true;
  orderId: string;
}

export interface MergeTablesInput {
  /** @minItems 2 */
  tableIds: string[];
}

export interface MergeTablesResult {
  success: true;
  mergeGroupId: string;
  hostOrderId: string;
}

export interface SuccessResponse {
  success: true;
}

export interface MoveItemsInput {
  /** @minItems 1 */
  itemIds: string[];
  targetTableId: string;
}

export interface MoveItemsResult {
  success: true;
  targetOrderId: string;
}

export interface TransferWaiterInput {
  newEmployeeId: string;
  authorisedById?: string;
}

export interface TransferWaiterResult {
  success: true;
  orderId: string;
  newEmployeeId: string;
}

export interface PrefacturaPrintResult {
  prefacturaNumber: number;
  /** @pattern ^P-\d{4,}$ */
  prefacturaCode: string;
  isReprint: boolean;
  /** @minimum 1 */
  totalPrints: number;
  amount: Money;
}

export interface PrefacturaStatus {
  hasPrinted: boolean;
  /** @minimum 0 */
  totalPrints: number;
  prefacturaNumber: number | null;
  prefacturaCode: string | null;
  lastPrintedAt: string | null;
}

export type KitchenTask = KitchenTaskRecord & ({
  tableName: string | null;
  employeeName: string | null;
  employeeId: string | null;
  orderType: string;
  clientName: string | null;
});

export interface KdsStation {
  id: string;
  name: string;
  zoneType: string;
  ip: string;
  displayUrl?: string | null;
  notes?: string | null;
  lastPingAt?: string | null;
  active: boolean;
  createdAt: string;
  updatedAt: string;
}

export interface CreateKdsStationInput {
  /** @minLength 1 */
  name: string;
  zoneType?: string;
  ip?: string;
  displayUrl?: string | null;
  notes?: string | null;
}

export interface UpdateKdsStationInput {
  name?: string;
  zoneType?: string;
  ip?: string;
  displayUrl?: string | null;
  notes?: string | null;
  active?: boolean;
}

export interface KdsPingResult {
  ok: true;
  reachable: boolean;
  latencyMs: number | null;
  target: string | null;
}

export interface KdsTransitionMap {
  new: string[];
  preparing: string[];
  in_oven?: string[];
  ready: string[];
  collected: string[];
  served?: string[];
  cancelled: string[];
}

export interface KdsTransitions {
  cocina: KdsTransitionMap;
  pizza: KdsTransitionMap;
  ensalada: KdsTransitionMap;
  barra: KdsTransitionMap;
  pase: KdsTransitionMap;
  sin_partida: KdsTransitionMap;
}

/**
 * The authenticated user lacks the required role or permission
 */
export type ForbiddenResponse = ErrorResponse;

/**
 * Requested resource was not found
 */
export type NotFoundResponse = ErrorResponse;

/**
 * Authentication is required or invalid
 */
export type UnauthorizedResponse = ErrorResponse;

/**
 * Current resource state conflicts with the operation
 */
export type ConflictResponse = ErrorResponse;

/**
 * Request validation failed
 */
export type BadRequestResponse = ErrorResponse;

export type BlockTableBody = {
  reason?: string;
};

export type DeleteKdsStation200 = {
  ok: true;
};

