/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Api
 * Piccolo TPV API
 * OpenAPI spec version: 0.2.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AlertConfig,
  AuditLogEntry,
  BadRequestResponse,
  BlockTableBody,
  ConflictResponse,
  CreateKdsStationInput,
  DeleteKdsStation200,
  ErrorResponse,
  ForbiddenResponse,
  KdsPingResult,
  KdsStation,
  KdsTransitions,
  KitchenTask,
  KitchenTaskRecord,
  MergeTablesInput,
  MergeTablesResult,
  MoveItemsInput,
  MoveItemsResult,
  NotFoundResponse,
  OccupationSummary,
  Order,
  OrderItem,
  PrefacturaPrintResult,
  PrefacturaStatus,
  SuccessResponse,
  Table,
  TableEvent,
  TableIdInput,
  TableTransferResult,
  TransferWaiterInput,
  TransferWaiterResult,
  UnauthorizedResponse,
  UpdateAlertConfigInput,
  UpdateKdsStationInput,
  UpdateOrderInput,
  UpdateOrderItemInput,
  UpdateTaskStatusInput,
  ValidationError
} from './api.schemas';

import { customFetch } from '../custom-fetch';
import type { ErrorType , BodyType } from '../custom-fetch';

type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const getUpdateOrderItemUrl = (itemId: string,) => {




  return `/api/order-items/${itemId}`
}

/**
 * @summary Update quantity, notes, allergy or invitation flag on a line item
 */
export const updateOrderItem = async (itemId: string,
    updateOrderItemInput: UpdateOrderItemInput, options?: RequestInit): Promise<OrderItem> => {

  return customFetch<OrderItem>(getUpdateOrderItemUrl(itemId),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updateOrderItemInput)
  }
);}





export const getUpdateOrderItemMutationOptions = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateOrderItem>>, TError,{itemId: string;data: BodyType<UpdateOrderItemInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof updateOrderItem>>, TError,{itemId: string;data: BodyType<UpdateOrderItemInput>}, TContext> => {

const mutationKey = ['updateOrderItem'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateOrderItem>>, {itemId: string;data: BodyType<UpdateOrderItemInput>}> = (props) => {
          const {itemId,data} = props ?? {};

          return  updateOrderItem(itemId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateOrderItemMutationResult = NonNullable<Awaited<ReturnType<typeof updateOrderItem>>>
    export type UpdateOrderItemMutationBody = BodyType<UpdateOrderItemInput>
    export type UpdateOrderItemMutationError = ErrorType<ErrorResponse>

    /**
 * @summary Update quantity, notes, allergy or invitation flag on a line item
 */
export const useUpdateOrderItem = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateOrderItem>>, TError,{itemId: string;data: BodyType<UpdateOrderItemInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof updateOrderItem>>,
        TError,
        {itemId: string;data: BodyType<UpdateOrderItemInput>},
        TContext
      > => {
      return useMutation(getUpdateOrderItemMutationOptions(options));
    }

export const getUpdateKitchenTaskStatusUrl = (taskId: string,) => {




  return `/api/kitchen-tasks/${taskId}/status`
}

/**
 * @summary Update status of a kitchen task
 */
export const updateKitchenTaskStatus = async (taskId: string,
    updateTaskStatusInput: UpdateTaskStatusInput, options?: RequestInit): Promise<KitchenTaskRecord> => {

  return customFetch<KitchenTaskRecord>(getUpdateKitchenTaskStatusUrl(taskId),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updateTaskStatusInput)
  }
);}





export const getUpdateKitchenTaskStatusMutationOptions = <TError = ErrorType<ErrorResponse | ForbiddenResponse | NotFoundResponse | ValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateKitchenTaskStatus>>, TError,{taskId: string;data: BodyType<UpdateTaskStatusInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof updateKitchenTaskStatus>>, TError,{taskId: string;data: BodyType<UpdateTaskStatusInput>}, TContext> => {

const mutationKey = ['updateKitchenTaskStatus'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateKitchenTaskStatus>>, {taskId: string;data: BodyType<UpdateTaskStatusInput>}> = (props) => {
          const {taskId,data} = props ?? {};

          return  updateKitchenTaskStatus(taskId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateKitchenTaskStatusMutationResult = NonNullable<Awaited<ReturnType<typeof updateKitchenTaskStatus>>>
    export type UpdateKitchenTaskStatusMutationBody = BodyType<UpdateTaskStatusInput>
    export type UpdateKitchenTaskStatusMutationError = ErrorType<ErrorResponse | ForbiddenResponse | NotFoundResponse | ValidationError>

    /**
 * @summary Update status of a kitchen task
 */
export const useUpdateKitchenTaskStatus = <TError = ErrorType<ErrorResponse | ForbiddenResponse | NotFoundResponse | ValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateKitchenTaskStatus>>, TError,{taskId: string;data: BodyType<UpdateTaskStatusInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof updateKitchenTaskStatus>>,
        TError,
        {taskId: string;data: BodyType<UpdateTaskStatusInput>},
        TContext
      > => {
      return useMutation(getUpdateKitchenTaskStatusMutationOptions(options));
    }

export const getUpdateOrderUrl = (orderId: string,) => {




  return `/api/orders/${orderId}`
}

/**
 * @summary Update order guest count, notes or status
 */
export const updateOrder = async (orderId: string,
    updateOrderInput: UpdateOrderInput, options?: RequestInit): Promise<Order> => {

  return customFetch<Order>(getUpdateOrderUrl(orderId),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updateOrderInput)
  }
);}





export const getUpdateOrderMutationOptions = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateOrder>>, TError,{orderId: string;data: BodyType<UpdateOrderInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof updateOrder>>, TError,{orderId: string;data: BodyType<UpdateOrderInput>}, TContext> => {

const mutationKey = ['updateOrder'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateOrder>>, {orderId: string;data: BodyType<UpdateOrderInput>}> = (props) => {
          const {orderId,data} = props ?? {};

          return  updateOrder(orderId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateOrderMutationResult = NonNullable<Awaited<ReturnType<typeof updateOrder>>>
    export type UpdateOrderMutationBody = BodyType<UpdateOrderInput>
    export type UpdateOrderMutationError = ErrorType<ErrorResponse>

    /**
 * @summary Update order guest count, notes or status
 */
export const useUpdateOrder = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateOrder>>, TError,{orderId: string;data: BodyType<UpdateOrderInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof updateOrder>>,
        TError,
        {orderId: string;data: BodyType<UpdateOrderInput>},
        TContext
      > => {
      return useMutation(getUpdateOrderMutationOptions(options));
    }

export const getDuplicateOrderItemUrl = (itemId: string,) => {




  return `/api/order-items/${itemId}/duplicate`
}

/**
 * @summary Duplicate a line item (copies product, format, modifiers)
 */
export const duplicateOrderItem = async (itemId: string, options?: RequestInit): Promise<OrderItem> => {

  return customFetch<OrderItem>(getDuplicateOrderItemUrl(itemId),
  {
    ...options,
    method: 'POST'


  }
);}





export const getDuplicateOrderItemMutationOptions = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof duplicateOrderItem>>, TError,{itemId: string}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof duplicateOrderItem>>, TError,{itemId: string}, TContext> => {

const mutationKey = ['duplicateOrderItem'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof duplicateOrderItem>>, {itemId: string}> = (props) => {
          const {itemId} = props ?? {};

          return  duplicateOrderItem(itemId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DuplicateOrderItemMutationResult = NonNullable<Awaited<ReturnType<typeof duplicateOrderItem>>>

    export type DuplicateOrderItemMutationError = ErrorType<ErrorResponse>

    /**
 * @summary Duplicate a line item (copies product, format, modifiers)
 */
export const useDuplicateOrderItem = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof duplicateOrderItem>>, TError,{itemId: string}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof duplicateOrderItem>>,
        TError,
        {itemId: string},
        TContext
      > => {
      return useMutation(getDuplicateOrderItemMutationOptions(options));
    }

export const getGetOrderAuditUrl = (orderId: string,) => {




  return `/api/orders/${orderId}/audit`
}

/**
 * @summary Get audit log entries for an order
 */
export const getOrderAudit = async (orderId: string, options?: RequestInit): Promise<AuditLogEntry[]> => {

  return customFetch<AuditLogEntry[]>(getGetOrderAuditUrl(orderId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetOrderAuditQueryKey = (orderId: string,) => {
    return [
    `/api/orders/${orderId}/audit`
    ] as const;
    }


export const getGetOrderAuditQueryOptions = <TData = Awaited<ReturnType<typeof getOrderAudit>>, TError = ErrorType<ErrorResponse>>(orderId: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getOrderAudit>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetOrderAuditQueryKey(orderId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getOrderAudit>>> = ({ signal }) => getOrderAudit(orderId, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: orderId !== null && orderId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getOrderAudit>>, TError, TData> & { queryKey: QueryKey }
}

export type GetOrderAuditQueryResult = NonNullable<Awaited<ReturnType<typeof getOrderAudit>>>
export type GetOrderAuditQueryError = ErrorType<ErrorResponse>


/**
 * @summary Get audit log entries for an order
 */

export function useGetOrderAudit<TData = Awaited<ReturnType<typeof getOrderAudit>>, TError = ErrorType<ErrorResponse>>(
 orderId: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getOrderAudit>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetOrderAuditQueryOptions(orderId,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}







export const getGetOccupationSummaryUrl = () => {




  return `/api/tables/occupation-summary`
}

/**
 * @summary Get current table occupation counters
 */
export const getOccupationSummary = async ( options?: RequestInit): Promise<OccupationSummary> => {

  return customFetch<OccupationSummary>(getGetOccupationSummaryUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetOccupationSummaryQueryKey = () => {
    return [
    `/api/tables/occupation-summary`
    ] as const;
    }


export const getGetOccupationSummaryQueryOptions = <TData = Awaited<ReturnType<typeof getOccupationSummary>>, TError = ErrorType<UnauthorizedResponse>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getOccupationSummary>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetOccupationSummaryQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getOccupationSummary>>> = ({ signal }) => getOccupationSummary({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getOccupationSummary>>, TError, TData> & { queryKey: QueryKey }
}

export type GetOccupationSummaryQueryResult = NonNullable<Awaited<ReturnType<typeof getOccupationSummary>>>
export type GetOccupationSummaryQueryError = ErrorType<UnauthorizedResponse>


/**
 * @summary Get current table occupation counters
 */

export function useGetOccupationSummary<TData = Awaited<ReturnType<typeof getOccupationSummary>>, TError = ErrorType<UnauthorizedResponse>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getOccupationSummary>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetOccupationSummaryQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}







export const getGetTableHistoryUrl = (tableId: string,) => {




  return `/api/tables/${tableId}/history`
}

/**
 * @summary Get the chronological event history for a table
 */
export const getTableHistory = async (tableId: string, options?: RequestInit): Promise<TableEvent[]> => {

  return customFetch<TableEvent[]>(getGetTableHistoryUrl(tableId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetTableHistoryQueryKey = (tableId: string,) => {
    return [
    `/api/tables/${tableId}/history`
    ] as const;
    }


export const getGetTableHistoryQueryOptions = <TData = Awaited<ReturnType<typeof getTableHistory>>, TError = ErrorType<UnauthorizedResponse | ForbiddenResponse>>(tableId: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getTableHistory>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetTableHistoryQueryKey(tableId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getTableHistory>>> = ({ signal }) => getTableHistory(tableId, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: tableId !== null && tableId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getTableHistory>>, TError, TData> & { queryKey: QueryKey }
}

export type GetTableHistoryQueryResult = NonNullable<Awaited<ReturnType<typeof getTableHistory>>>
export type GetTableHistoryQueryError = ErrorType<UnauthorizedResponse | ForbiddenResponse>


/**
 * @summary Get the chronological event history for a table
 */

export function useGetTableHistory<TData = Awaited<ReturnType<typeof getTableHistory>>, TError = ErrorType<UnauthorizedResponse | ForbiddenResponse>>(
 tableId: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getTableHistory>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetTableHistoryQueryOptions(tableId,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}







export const getGetAlertConfigUrl = () => {




  return `/api/admin/alert-config`
}

/**
 * @summary Get operational table alert thresholds
 */
export const getAlertConfig = async ( options?: RequestInit): Promise<AlertConfig> => {

  return customFetch<AlertConfig>(getGetAlertConfigUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetAlertConfigQueryKey = () => {
    return [
    `/api/admin/alert-config`
    ] as const;
    }


export const getGetAlertConfigQueryOptions = <TData = Awaited<ReturnType<typeof getAlertConfig>>, TError = ErrorType<UnauthorizedResponse | ForbiddenResponse>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getAlertConfig>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAlertConfigQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAlertConfig>>> = ({ signal }) => getAlertConfig({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAlertConfig>>, TError, TData> & { queryKey: QueryKey }
}

export type GetAlertConfigQueryResult = NonNullable<Awaited<ReturnType<typeof getAlertConfig>>>
export type GetAlertConfigQueryError = ErrorType<UnauthorizedResponse | ForbiddenResponse>


/**
 * @summary Get operational table alert thresholds
 */

export function useGetAlertConfig<TData = Awaited<ReturnType<typeof getAlertConfig>>, TError = ErrorType<UnauthorizedResponse | ForbiddenResponse>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getAlertConfig>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetAlertConfigQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}







export const getPatchAlertConfigUrl = () => {




  return `/api/admin/alert-config`
}

/**
 * @summary Update positive table alert thresholds
 */
export const patchAlertConfig = async (updateAlertConfigInput: UpdateAlertConfigInput, options?: RequestInit): Promise<AlertConfig> => {

  return customFetch<AlertConfig>(getPatchAlertConfigUrl(),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updateAlertConfigInput)
  }
);}





export const getPatchAlertConfigMutationOptions = <TError = ErrorType<UnauthorizedResponse | ForbiddenResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchAlertConfig>>, TError,{data: BodyType<UpdateAlertConfigInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof patchAlertConfig>>, TError,{data: BodyType<UpdateAlertConfigInput>}, TContext> => {

const mutationKey = ['patchAlertConfig'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchAlertConfig>>, {data: BodyType<UpdateAlertConfigInput>}> = (props) => {
          const {data} = props ?? {};

          return  patchAlertConfig(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PatchAlertConfigMutationResult = NonNullable<Awaited<ReturnType<typeof patchAlertConfig>>>
    export type PatchAlertConfigMutationBody = BodyType<UpdateAlertConfigInput>
    export type PatchAlertConfigMutationError = ErrorType<UnauthorizedResponse | ForbiddenResponse>

    /**
 * @summary Update positive table alert thresholds
 */
export const usePatchAlertConfig = <TError = ErrorType<UnauthorizedResponse | ForbiddenResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchAlertConfig>>, TError,{data: BodyType<UpdateAlertConfigInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof patchAlertConfig>>,
        TError,
        {data: BodyType<UpdateAlertConfigInput>},
        TContext
      > => {
      return useMutation(getPatchAlertConfigMutationOptions(options));
    }

export const getCleanTableUrl = (tableId: string,) => {




  return `/api/tables/${tableId}/clean`
}

/**
 * @summary Mark a pending-cleaning table as free
 */
export const cleanTable = async (tableId: string, options?: RequestInit): Promise<Table> => {

  return customFetch<Table>(getCleanTableUrl(tableId),
  {
    ...options,
    method: 'POST'


  }
);}





export const getCleanTableMutationOptions = <TError = ErrorType<UnauthorizedResponse | ConflictResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof cleanTable>>, TError,{tableId: string}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof cleanTable>>, TError,{tableId: string}, TContext> => {

const mutationKey = ['cleanTable'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof cleanTable>>, {tableId: string}> = (props) => {
          const {tableId} = props ?? {};

          return  cleanTable(tableId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CleanTableMutationResult = NonNullable<Awaited<ReturnType<typeof cleanTable>>>

    export type CleanTableMutationError = ErrorType<UnauthorizedResponse | ConflictResponse>

    /**
 * @summary Mark a pending-cleaning table as free
 */
export const useCleanTable = <TError = ErrorType<UnauthorizedResponse | ConflictResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof cleanTable>>, TError,{tableId: string}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof cleanTable>>,
        TError,
        {tableId: string},
        TContext
      > => {
      return useMutation(getCleanTableMutationOptions(options));
    }

export const getBlockTableUrl = (tableId: string,) => {




  return `/api/tables/${tableId}/block`
}

/**
 * @summary Toggle a table between blocked and free
 */
export const blockTable = async (tableId: string,
    blockTableBody?: BlockTableBody, options?: RequestInit): Promise<Table> => {

  return customFetch<Table>(getBlockTableUrl(tableId),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(blockTableBody)
  }
);}





export const getBlockTableMutationOptions = <TError = ErrorType<UnauthorizedResponse | ForbiddenResponse | NotFoundResponse | ConflictResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof blockTable>>, TError,{tableId: string;data?: BodyType<BlockTableBody>}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof blockTable>>, TError,{tableId: string;data?: BodyType<BlockTableBody>}, TContext> => {

const mutationKey = ['blockTable'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof blockTable>>, {tableId: string;data?: BodyType<BlockTableBody>}> = (props) => {
          const {tableId,data} = props ?? {};

          return  blockTable(tableId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type BlockTableMutationResult = NonNullable<Awaited<ReturnType<typeof blockTable>>>
    export type BlockTableMutationBody = BodyType<BlockTableBody> | undefined
    export type BlockTableMutationError = ErrorType<UnauthorizedResponse | ForbiddenResponse | NotFoundResponse | ConflictResponse>

    /**
 * @summary Toggle a table between blocked and free
 */
export const useBlockTable = <TError = ErrorType<UnauthorizedResponse | ForbiddenResponse | NotFoundResponse | ConflictResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof blockTable>>, TError,{tableId: string;data?: BodyType<BlockTableBody>}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof blockTable>>,
        TError,
        {tableId: string;data?: BodyType<BlockTableBody>},
        TContext
      > => {
      return useMutation(getBlockTableMutationOptions(options));
    }

export const getTransferTableUrl = (tableId: string,) => {




  return `/api/tables/${tableId}/transfer`
}

/**
 * @summary Move an open order to a free table atomically
 */
export const transferTable = async (tableId: string,
    tableIdInput: TableIdInput, options?: RequestInit): Promise<TableTransferResult> => {

  return customFetch<TableTransferResult>(getTransferTableUrl(tableId),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(tableIdInput)
  }
);}





export const getTransferTableMutationOptions = <TError = ErrorType<BadRequestResponse | UnauthorizedResponse | NotFoundResponse | ConflictResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof transferTable>>, TError,{tableId: string;data: BodyType<TableIdInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof transferTable>>, TError,{tableId: string;data: BodyType<TableIdInput>}, TContext> => {

const mutationKey = ['transferTable'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof transferTable>>, {tableId: string;data: BodyType<TableIdInput>}> = (props) => {
          const {tableId,data} = props ?? {};

          return  transferTable(tableId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type TransferTableMutationResult = NonNullable<Awaited<ReturnType<typeof transferTable>>>
    export type TransferTableMutationBody = BodyType<TableIdInput>
    export type TransferTableMutationError = ErrorType<BadRequestResponse | UnauthorizedResponse | NotFoundResponse | ConflictResponse>

    /**
 * @summary Move an open order to a free table atomically
 */
export const useTransferTable = <TError = ErrorType<BadRequestResponse | UnauthorizedResponse | NotFoundResponse | ConflictResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof transferTable>>, TError,{tableId: string;data: BodyType<TableIdInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof transferTable>>,
        TError,
        {tableId: string;data: BodyType<TableIdInput>},
        TContext
      > => {
      return useMutation(getTransferTableMutationOptions(options));
    }

export const getMergeTablesUrl = () => {




  return `/api/tables/merge`
}

/**
 * @summary Merge at least two tables and consolidate their open orders
 */
export const mergeTables = async (mergeTablesInput: MergeTablesInput, options?: RequestInit): Promise<MergeTablesResult> => {

  return customFetch<MergeTablesResult>(getMergeTablesUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(mergeTablesInput)
  }
);}





export const getMergeTablesMutationOptions = <TError = ErrorType<BadRequestResponse | UnauthorizedResponse | ForbiddenResponse | NotFoundResponse | ConflictResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof mergeTables>>, TError,{data: BodyType<MergeTablesInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof mergeTables>>, TError,{data: BodyType<MergeTablesInput>}, TContext> => {

const mutationKey = ['mergeTables'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof mergeTables>>, {data: BodyType<MergeTablesInput>}> = (props) => {
          const {data} = props ?? {};

          return  mergeTables(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type MergeTablesMutationResult = NonNullable<Awaited<ReturnType<typeof mergeTables>>>
    export type MergeTablesMutationBody = BodyType<MergeTablesInput>
    export type MergeTablesMutationError = ErrorType<BadRequestResponse | UnauthorizedResponse | ForbiddenResponse | NotFoundResponse | ConflictResponse>

    /**
 * @summary Merge at least two tables and consolidate their open orders
 */
export const useMergeTables = <TError = ErrorType<BadRequestResponse | UnauthorizedResponse | ForbiddenResponse | NotFoundResponse | ConflictResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof mergeTables>>, TError,{data: BodyType<MergeTablesInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof mergeTables>>,
        TError,
        {data: BodyType<MergeTablesInput>},
        TContext
      > => {
      return useMutation(getMergeTablesMutationOptions(options));
    }

export const getSeparateTableUrl = (tableId: string,) => {




  return `/api/tables/${tableId}/separate`
}

/**
 * @summary Separate all tables in an existing merge group
 */
export const separateTable = async (tableId: string, options?: RequestInit): Promise<SuccessResponse> => {

  return customFetch<SuccessResponse>(getSeparateTableUrl(tableId),
  {
    ...options,
    method: 'POST'


  }
);}





export const getSeparateTableMutationOptions = <TError = ErrorType<UnauthorizedResponse | ForbiddenResponse | ConflictResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof separateTable>>, TError,{tableId: string}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof separateTable>>, TError,{tableId: string}, TContext> => {

const mutationKey = ['separateTable'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof separateTable>>, {tableId: string}> = (props) => {
          const {tableId} = props ?? {};

          return  separateTable(tableId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type SeparateTableMutationResult = NonNullable<Awaited<ReturnType<typeof separateTable>>>

    export type SeparateTableMutationError = ErrorType<UnauthorizedResponse | ForbiddenResponse | ConflictResponse>

    /**
 * @summary Separate all tables in an existing merge group
 */
export const useSeparateTable = <TError = ErrorType<UnauthorizedResponse | ForbiddenResponse | ConflictResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof separateTable>>, TError,{tableId: string}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof separateTable>>,
        TError,
        {tableId: string},
        TContext
      > => {
      return useMutation(getSeparateTableMutationOptions(options));
    }

export const getMoveItemsUrl = (orderId: string,) => {




  return `/api/orders/${orderId}/move-items`
}

/**
 * @summary Move selected order items to an order on another table
 */
export const moveItems = async (orderId: string,
    moveItemsInput: MoveItemsInput, options?: RequestInit): Promise<MoveItemsResult> => {

  return customFetch<MoveItemsResult>(getMoveItemsUrl(orderId),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(moveItemsInput)
  }
);}





export const getMoveItemsMutationOptions = <TError = ErrorType<BadRequestResponse | UnauthorizedResponse | NotFoundResponse | ConflictResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof moveItems>>, TError,{orderId: string;data: BodyType<MoveItemsInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof moveItems>>, TError,{orderId: string;data: BodyType<MoveItemsInput>}, TContext> => {

const mutationKey = ['moveItems'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof moveItems>>, {orderId: string;data: BodyType<MoveItemsInput>}> = (props) => {
          const {orderId,data} = props ?? {};

          return  moveItems(orderId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type MoveItemsMutationResult = NonNullable<Awaited<ReturnType<typeof moveItems>>>
    export type MoveItemsMutationBody = BodyType<MoveItemsInput>
    export type MoveItemsMutationError = ErrorType<BadRequestResponse | UnauthorizedResponse | NotFoundResponse | ConflictResponse>

    /**
 * @summary Move selected order items to an order on another table
 */
export const useMoveItems = <TError = ErrorType<BadRequestResponse | UnauthorizedResponse | NotFoundResponse | ConflictResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof moveItems>>, TError,{orderId: string;data: BodyType<MoveItemsInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof moveItems>>,
        TError,
        {orderId: string;data: BodyType<MoveItemsInput>},
        TContext
      > => {
      return useMutation(getMoveItemsMutationOptions(options));
    }

export const getTransferWaiterUrl = (tableId: string,) => {




  return `/api/tables/${tableId}/transfer-waiter`
}

/**
 * @summary Reassign the open table order to another employee
 */
export const transferWaiter = async (tableId: string,
    transferWaiterInput: TransferWaiterInput, options?: RequestInit): Promise<TransferWaiterResult> => {

  return customFetch<TransferWaiterResult>(getTransferWaiterUrl(tableId),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(transferWaiterInput)
  }
);}





export const getTransferWaiterMutationOptions = <TError = ErrorType<BadRequestResponse | UnauthorizedResponse | ForbiddenResponse | ConflictResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof transferWaiter>>, TError,{tableId: string;data: BodyType<TransferWaiterInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof transferWaiter>>, TError,{tableId: string;data: BodyType<TransferWaiterInput>}, TContext> => {

const mutationKey = ['transferWaiter'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof transferWaiter>>, {tableId: string;data: BodyType<TransferWaiterInput>}> = (props) => {
          const {tableId,data} = props ?? {};

          return  transferWaiter(tableId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type TransferWaiterMutationResult = NonNullable<Awaited<ReturnType<typeof transferWaiter>>>
    export type TransferWaiterMutationBody = BodyType<TransferWaiterInput>
    export type TransferWaiterMutationError = ErrorType<BadRequestResponse | UnauthorizedResponse | ForbiddenResponse | ConflictResponse>

    /**
 * @summary Reassign the open table order to another employee
 */
export const useTransferWaiter = <TError = ErrorType<BadRequestResponse | UnauthorizedResponse | ForbiddenResponse | ConflictResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof transferWaiter>>, TError,{tableId: string;data: BodyType<TransferWaiterInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof transferWaiter>>,
        TError,
        {tableId: string;data: BodyType<TransferWaiterInput>},
        TContext
      > => {
      return useMutation(getTransferWaiterMutationOptions(options));
    }

export const getCreatePrefacturaPrintUrl = (orderId: string,) => {




  return `/api/orders/${orderId}/prefactura/print`
}

/**
 * @summary Allocate or reuse a prefactura number and record a print
 */
export const createPrefacturaPrint = async (orderId: string, options?: RequestInit): Promise<PrefacturaPrintResult> => {

  return customFetch<PrefacturaPrintResult>(getCreatePrefacturaPrintUrl(orderId),
  {
    ...options,
    method: 'POST'


  }
);}





export const getCreatePrefacturaPrintMutationOptions = <TError = ErrorType<UnauthorizedResponse | NotFoundResponse | ConflictResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createPrefacturaPrint>>, TError,{orderId: string}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof createPrefacturaPrint>>, TError,{orderId: string}, TContext> => {

const mutationKey = ['createPrefacturaPrint'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createPrefacturaPrint>>, {orderId: string}> = (props) => {
          const {orderId} = props ?? {};

          return  createPrefacturaPrint(orderId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreatePrefacturaPrintMutationResult = NonNullable<Awaited<ReturnType<typeof createPrefacturaPrint>>>

    export type CreatePrefacturaPrintMutationError = ErrorType<UnauthorizedResponse | NotFoundResponse | ConflictResponse>

    /**
 * @summary Allocate or reuse a prefactura number and record a print
 */
export const useCreatePrefacturaPrint = <TError = ErrorType<UnauthorizedResponse | NotFoundResponse | ConflictResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createPrefacturaPrint>>, TError,{orderId: string}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof createPrefacturaPrint>>,
        TError,
        {orderId: string},
        TContext
      > => {
      return useMutation(getCreatePrefacturaPrintMutationOptions(options));
    }

export const getGetPrefacturaStatusUrl = (orderId: string,) => {




  return `/api/orders/${orderId}/prefactura/status`
}

/**
 * @summary Get prefactura print status for an order
 */
export const getPrefacturaStatus = async (orderId: string, options?: RequestInit): Promise<PrefacturaStatus> => {

  return customFetch<PrefacturaStatus>(getGetPrefacturaStatusUrl(orderId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetPrefacturaStatusQueryKey = (orderId: string,) => {
    return [
    `/api/orders/${orderId}/prefactura/status`
    ] as const;
    }


export const getGetPrefacturaStatusQueryOptions = <TData = Awaited<ReturnType<typeof getPrefacturaStatus>>, TError = ErrorType<UnauthorizedResponse>>(orderId: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getPrefacturaStatus>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetPrefacturaStatusQueryKey(orderId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getPrefacturaStatus>>> = ({ signal }) => getPrefacturaStatus(orderId, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: orderId !== null && orderId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getPrefacturaStatus>>, TError, TData> & { queryKey: QueryKey }
}

export type GetPrefacturaStatusQueryResult = NonNullable<Awaited<ReturnType<typeof getPrefacturaStatus>>>
export type GetPrefacturaStatusQueryError = ErrorType<UnauthorizedResponse>


/**
 * @summary Get prefactura print status for an order
 */

export function useGetPrefacturaStatus<TData = Awaited<ReturnType<typeof getPrefacturaStatus>>, TError = ErrorType<UnauthorizedResponse>>(
 orderId: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getPrefacturaStatus>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetPrefacturaStatusQueryOptions(orderId,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}







export const getGetKdsHistoryUrl = () => {




  return `/api/kds/history`
}

/**
 * @summary Get terminal KDS tasks updated in the last eight hours
 */
export const getKdsHistory = async ( options?: RequestInit): Promise<KitchenTask[]> => {

  return customFetch<KitchenTask[]>(getGetKdsHistoryUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetKdsHistoryQueryKey = () => {
    return [
    `/api/kds/history`
    ] as const;
    }


export const getGetKdsHistoryQueryOptions = <TData = Awaited<ReturnType<typeof getKdsHistory>>, TError = ErrorType<UnauthorizedResponse | ForbiddenResponse>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getKdsHistory>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetKdsHistoryQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getKdsHistory>>> = ({ signal }) => getKdsHistory({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getKdsHistory>>, TError, TData> & { queryKey: QueryKey }
}

export type GetKdsHistoryQueryResult = NonNullable<Awaited<ReturnType<typeof getKdsHistory>>>
export type GetKdsHistoryQueryError = ErrorType<UnauthorizedResponse | ForbiddenResponse>


/**
 * @summary Get terminal KDS tasks updated in the last eight hours
 */

export function useGetKdsHistory<TData = Awaited<ReturnType<typeof getKdsHistory>>, TError = ErrorType<UnauthorizedResponse | ForbiddenResponse>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getKdsHistory>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetKdsHistoryQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}







export const getResendKitchenTaskUrl = (taskId: string,) => {




  return `/api/kitchen-tasks/${taskId}/resend`
}

/**
 * @summary Reset a non-terminal kitchen task to new
 */
export const resendKitchenTask = async (taskId: string, options?: RequestInit): Promise<KitchenTaskRecord> => {

  return customFetch<KitchenTaskRecord>(getResendKitchenTaskUrl(taskId),
  {
    ...options,
    method: 'POST'


  }
);}





export const getResendKitchenTaskMutationOptions = <TError = ErrorType<UnauthorizedResponse | ForbiddenResponse | NotFoundResponse | ConflictResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof resendKitchenTask>>, TError,{taskId: string}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof resendKitchenTask>>, TError,{taskId: string}, TContext> => {

const mutationKey = ['resendKitchenTask'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof resendKitchenTask>>, {taskId: string}> = (props) => {
          const {taskId} = props ?? {};

          return  resendKitchenTask(taskId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ResendKitchenTaskMutationResult = NonNullable<Awaited<ReturnType<typeof resendKitchenTask>>>

    export type ResendKitchenTaskMutationError = ErrorType<UnauthorizedResponse | ForbiddenResponse | NotFoundResponse | ConflictResponse>

    /**
 * @summary Reset a non-terminal kitchen task to new
 */
export const useResendKitchenTask = <TError = ErrorType<UnauthorizedResponse | ForbiddenResponse | NotFoundResponse | ConflictResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof resendKitchenTask>>, TError,{taskId: string}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof resendKitchenTask>>,
        TError,
        {taskId: string},
        TContext
      > => {
      return useMutation(getResendKitchenTaskMutationOptions(options));
    }

export const getGetKdsStationsUrl = () => {




  return `/api/admin/kds-stations`
}

/**
 * @summary List configured KDS stations
 */
export const getKdsStations = async ( options?: RequestInit): Promise<KdsStation[]> => {

  return customFetch<KdsStation[]>(getGetKdsStationsUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetKdsStationsQueryKey = () => {
    return [
    `/api/admin/kds-stations`
    ] as const;
    }


export const getGetKdsStationsQueryOptions = <TData = Awaited<ReturnType<typeof getKdsStations>>, TError = ErrorType<UnauthorizedResponse | ForbiddenResponse>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getKdsStations>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetKdsStationsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getKdsStations>>> = ({ signal }) => getKdsStations({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getKdsStations>>, TError, TData> & { queryKey: QueryKey }
}

export type GetKdsStationsQueryResult = NonNullable<Awaited<ReturnType<typeof getKdsStations>>>
export type GetKdsStationsQueryError = ErrorType<UnauthorizedResponse | ForbiddenResponse>


/**
 * @summary List configured KDS stations
 */

export function useGetKdsStations<TData = Awaited<ReturnType<typeof getKdsStations>>, TError = ErrorType<UnauthorizedResponse | ForbiddenResponse>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getKdsStations>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetKdsStationsQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}







export const getCreateKdsStationUrl = () => {




  return `/api/admin/kds-stations`
}

/**
 * @summary Create a KDS station
 */
export const createKdsStation = async (createKdsStationInput: CreateKdsStationInput, options?: RequestInit): Promise<KdsStation> => {

  return customFetch<KdsStation>(getCreateKdsStationUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createKdsStationInput)
  }
);}





export const getCreateKdsStationMutationOptions = <TError = ErrorType<BadRequestResponse | UnauthorizedResponse | ForbiddenResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createKdsStation>>, TError,{data: BodyType<CreateKdsStationInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof createKdsStation>>, TError,{data: BodyType<CreateKdsStationInput>}, TContext> => {

const mutationKey = ['createKdsStation'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createKdsStation>>, {data: BodyType<CreateKdsStationInput>}> = (props) => {
          const {data} = props ?? {};

          return  createKdsStation(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateKdsStationMutationResult = NonNullable<Awaited<ReturnType<typeof createKdsStation>>>
    export type CreateKdsStationMutationBody = BodyType<CreateKdsStationInput>
    export type CreateKdsStationMutationError = ErrorType<BadRequestResponse | UnauthorizedResponse | ForbiddenResponse>

    /**
 * @summary Create a KDS station
 */
export const useCreateKdsStation = <TError = ErrorType<BadRequestResponse | UnauthorizedResponse | ForbiddenResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createKdsStation>>, TError,{data: BodyType<CreateKdsStationInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof createKdsStation>>,
        TError,
        {data: BodyType<CreateKdsStationInput>},
        TContext
      > => {
      return useMutation(getCreateKdsStationMutationOptions(options));
    }

export const getUpdateKdsStationUrl = (id: string,) => {




  return `/api/admin/kds-stations/${id}`
}

/**
 * @summary Partially update a KDS station
 */
export const updateKdsStation = async (id: string,
    updateKdsStationInput: UpdateKdsStationInput, options?: RequestInit): Promise<KdsStation> => {

  return customFetch<KdsStation>(getUpdateKdsStationUrl(id),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updateKdsStationInput)
  }
);}





export const getUpdateKdsStationMutationOptions = <TError = ErrorType<UnauthorizedResponse | ForbiddenResponse | NotFoundResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateKdsStation>>, TError,{id: string;data: BodyType<UpdateKdsStationInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof updateKdsStation>>, TError,{id: string;data: BodyType<UpdateKdsStationInput>}, TContext> => {

const mutationKey = ['updateKdsStation'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateKdsStation>>, {id: string;data: BodyType<UpdateKdsStationInput>}> = (props) => {
          const {id,data} = props ?? {};

          return  updateKdsStation(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateKdsStationMutationResult = NonNullable<Awaited<ReturnType<typeof updateKdsStation>>>
    export type UpdateKdsStationMutationBody = BodyType<UpdateKdsStationInput>
    export type UpdateKdsStationMutationError = ErrorType<UnauthorizedResponse | ForbiddenResponse | NotFoundResponse>

    /**
 * @summary Partially update a KDS station
 */
export const useUpdateKdsStation = <TError = ErrorType<UnauthorizedResponse | ForbiddenResponse | NotFoundResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateKdsStation>>, TError,{id: string;data: BodyType<UpdateKdsStationInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof updateKdsStation>>,
        TError,
        {id: string;data: BodyType<UpdateKdsStationInput>},
        TContext
      > => {
      return useMutation(getUpdateKdsStationMutationOptions(options));
    }

export const getDeleteKdsStationUrl = (id: string,) => {




  return `/api/admin/kds-stations/${id}`
}

/**
 * @summary Soft-delete a KDS station
 */
export const deleteKdsStation = async (id: string, options?: RequestInit): Promise<DeleteKdsStation200> => {

  return customFetch<DeleteKdsStation200>(getDeleteKdsStationUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}





export const getDeleteKdsStationMutationOptions = <TError = ErrorType<UnauthorizedResponse | ForbiddenResponse | NotFoundResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteKdsStation>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteKdsStation>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteKdsStation'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteKdsStation>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteKdsStation(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteKdsStationMutationResult = NonNullable<Awaited<ReturnType<typeof deleteKdsStation>>>

    export type DeleteKdsStationMutationError = ErrorType<UnauthorizedResponse | ForbiddenResponse | NotFoundResponse>

    /**
 * @summary Soft-delete a KDS station
 */
export const useDeleteKdsStation = <TError = ErrorType<UnauthorizedResponse | ForbiddenResponse | NotFoundResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteKdsStation>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof deleteKdsStation>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getDeleteKdsStationMutationOptions(options));
    }

export const getPingKdsStationUrl = (id: string,) => {




  return `/api/admin/kds-stations/${id}/ping`
}

/**
 * @summary Probe a KDS display URL or IP with a three-second timeout
 */
export const pingKdsStation = async (id: string, options?: RequestInit): Promise<KdsPingResult> => {

  return customFetch<KdsPingResult>(getPingKdsStationUrl(id),
  {
    ...options,
    method: 'POST'


  }
);}





export const getPingKdsStationMutationOptions = <TError = ErrorType<UnauthorizedResponse | ForbiddenResponse | NotFoundResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof pingKdsStation>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof pingKdsStation>>, TError,{id: string}, TContext> => {

const mutationKey = ['pingKdsStation'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof pingKdsStation>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  pingKdsStation(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PingKdsStationMutationResult = NonNullable<Awaited<ReturnType<typeof pingKdsStation>>>

    export type PingKdsStationMutationError = ErrorType<UnauthorizedResponse | ForbiddenResponse | NotFoundResponse>

    /**
 * @summary Probe a KDS display URL or IP with a three-second timeout
 */
export const usePingKdsStation = <TError = ErrorType<UnauthorizedResponse | ForbiddenResponse | NotFoundResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof pingKdsStation>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof pingKdsStation>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getPingKdsStationMutationOptions(options));
    }

export const getGetKdsZoneTransitionsUrl = () => {




  return `/api/admin/kds-zones/transitions`
}

/**
 * @summary Get the KDS state machines used by every preparation zone
 */
export const getKdsZoneTransitions = async ( options?: RequestInit): Promise<KdsTransitions> => {

  return customFetch<KdsTransitions>(getGetKdsZoneTransitionsUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetKdsZoneTransitionsQueryKey = () => {
    return [
    `/api/admin/kds-zones/transitions`
    ] as const;
    }


export const getGetKdsZoneTransitionsQueryOptions = <TData = Awaited<ReturnType<typeof getKdsZoneTransitions>>, TError = ErrorType<UnauthorizedResponse | ForbiddenResponse>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getKdsZoneTransitions>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetKdsZoneTransitionsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getKdsZoneTransitions>>> = ({ signal }) => getKdsZoneTransitions({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getKdsZoneTransitions>>, TError, TData> & { queryKey: QueryKey }
}

export type GetKdsZoneTransitionsQueryResult = NonNullable<Awaited<ReturnType<typeof getKdsZoneTransitions>>>
export type GetKdsZoneTransitionsQueryError = ErrorType<UnauthorizedResponse | ForbiddenResponse>


/**
 * @summary Get the KDS state machines used by every preparation zone
 */

export function useGetKdsZoneTransitions<TData = Awaited<ReturnType<typeof getKdsZoneTransitions>>, TError = ErrorType<UnauthorizedResponse | ForbiddenResponse>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getKdsZoneTransitions>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetKdsZoneTransitionsQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}







