import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import zonesRouter from "./zones";
import tablesRouter from "./tables";
import dashboardRouter from "./dashboard";
import categoriesRouter from "./categories";
import ordersRouter from "./orders";
import kdsRouter from "./kds";
import modifiersRouter from "./modifiers";
import notificationsRouter from "./notifications";
import cashRouter from "./cash";
import paymentsRouter from "./payments";
import canvasElementsRouter from "./canvas-elements";
import productsRouter from "./products";
import configRouter from "./config";
import documentsRouter from "./documents";
import discountsRouter from "./discounts";
import tipsRouter from "./tips";
import splitsRouter from "./splits";
import ingredientsRouter from "./ingredients";
import recipesRouter from "./recipes";
import subrecipesRouter from "./subrecipes";
import profitabilityRouter from "./profitability";
import tableOperationsRouter from "./table-operations";
import reservationsRouter from "./reservations";
import cashMachineRouter from "./cash-machine";
import suppliersRouter from "./suppliers";
import purchaseOrdersRouter from "./purchase-orders";
import goodsReceiptsRouter from "./goods-receipts";
import supplierInvoicesRouter from "./supplier-invoices";
import purchaseReportsRouter from "./purchase-reports";
import invoiceScannerRouter from "./invoice-scanner";
import allergensRouter from "./allergens";
import tableAllergiesRouter from "./table-allergies";
import traceabilityRouter from "./traceability";
import fichajeRouter from "./fichaje";
import verifactuRouter from "./verifactu";
import crmRouter from "./crm";
import onlineOrdersRouter from "./online-orders";
import printersRouter from "./printers";
import ingredientCategoriesRouter from "./ingredient-categories";
import storageLocationsRouter from "./storage-locations";
import wasteRecordsRouter from "./waste-records";
import serviceShiftsRouter from "./service-shifts";
import waitingListRouter from "./waiting-list";
import deliveryOrdersRouter from "./delivery-orders";
import onlineOrdersV2Router from "./online-orders-v2";
import loyaltyExtendedRouter from "./loyalty-extended";
import hrRouter from "./hr";
import hrImportRouter from "./hr-import";
import directorRouter from "./director";
import directorManagementRouter from "./director-management";
import backupRouter from "./backup";
import diagnosticsRouter from "./diagnostics";
import offlineRouter from "./offline";
import setupRouter from "./setup";
import auditRouter from "./audit";
import installationRouter from "./installation";
import demoDataRouter from "./demo-data";
import systemInfoRouter from "./system-info";
import rolePermissionsRouter from "./role-permissions";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(zonesRouter);
router.use(tableOperationsRouter);
router.use(reservationsRouter);
router.use(tablesRouter);
router.use(dashboardRouter);
router.use(categoriesRouter);
router.use(ordersRouter);
router.use(kdsRouter);
router.use(modifiersRouter);
router.use(notificationsRouter);
router.use(cashRouter);
router.use(paymentsRouter);
router.use(canvasElementsRouter);
router.use(productsRouter);
router.use(configRouter);
router.use(documentsRouter);
router.use(discountsRouter);
router.use(tipsRouter);
router.use(splitsRouter);
router.use(ingredientsRouter);
router.use(recipesRouter);
router.use(subrecipesRouter);
router.use(profitabilityRouter);
router.use(cashMachineRouter);
router.use(suppliersRouter);
router.use(purchaseOrdersRouter);
router.use(goodsReceiptsRouter);
router.use(supplierInvoicesRouter);
router.use(purchaseReportsRouter);
router.use(invoiceScannerRouter);
router.use(allergensRouter);
router.use(tableAllergiesRouter);
router.use(traceabilityRouter);
router.use(fichajeRouter);
router.use(verifactuRouter);
router.use(crmRouter);
router.use(onlineOrdersRouter);
router.use(printersRouter);
router.use(ingredientCategoriesRouter);
router.use(storageLocationsRouter);
router.use(wasteRecordsRouter);
router.use(serviceShiftsRouter);
router.use(waitingListRouter);
router.use(deliveryOrdersRouter);
router.use(onlineOrdersV2Router);
router.use(loyaltyExtendedRouter);
router.use(hrRouter);
router.use(hrImportRouter);
router.use(directorRouter);
router.use(directorManagementRouter);
router.use(backupRouter);
router.use(diagnosticsRouter);
router.use(offlineRouter);
router.use(setupRouter);
router.use(auditRouter);
router.use(installationRouter);
router.use(demoDataRouter);
router.use(systemInfoRouter);
router.use(rolePermissionsRouter);

export default router;
