/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Api
 * Piccolo TPV API
 * OpenAPI spec version: 0.2.0
 */
/**
 * Active category for staff TPV (id, name, sortOrder only)
 */
export interface CatalogStaffCategory {
  id: string;
  name: string;
  sortOrder: number;
}

/**
 * Applicable VAT rate (Spain). Prices are VAT-inclusive.
 */
export type CatalogTaxRate = typeof CatalogTaxRate[keyof typeof CatalogTaxRate];


export const CatalogTaxRate = {
  NUMBER_4: 4,
  NUMBER_10: 10,
  NUMBER_21: 21,
} as const;

export interface CatalogProductFormat {
  id: string;
  productId: string;
  name: string;
  /** Numeric string from DB */
  price: string;
  /** Numeric string from DB */
  cost?: string | null;
  prepTime?: number | null;
  kdsDestination?: string | null;
  sortOrder: number;
  active: boolean;
  taxRate?: CatalogTaxRate | null;
}

/**
 * Product with formats for staff category listing
 */
export interface CatalogStaffCategoryProduct {
  id: string;
  categoryId: string;
  subcategoryId?: string | null;
  name: string;
  price: string;
  taxRate: CatalogTaxRate;
  prepZone: string;
  tpvVisible: boolean;
  outOfStock: boolean;
  allergens: string;
  imageUrl?: string | null;
  hasModifiers: boolean;
  formats: CatalogProductFormat[];
}

export interface CatalogStaffModifierOption {
  id: string;
  name: string;
  priceDelta: string;
}

/**
 * Modifier group with options for staff product ordering
 */
export interface CatalogStaffModifierGroup {
  id: string;
  name: string;
  required: boolean;
  maxSelect: number;
  modifiers: CatalogStaffModifierOption[];
}

export interface CatalogCreateProductFormatInput {
  name: string;
  /** Numeric string */
  price: string;
  cost?: string | null;
  prepTime?: number;
  kdsDestination?: string;
  sortOrder?: number;
  taxRate?: CatalogTaxRate;
}

export interface CatalogUpdateProductFormatInput {
  name?: string;
  price?: string;
  cost?: string | null;
  prepTime?: number | null;
  kdsDestination?: string | null;
  sortOrder?: number;
  active?: boolean;
  taxRate?: CatalogTaxRate | null;
}

export interface CatalogOkResult {
  ok: true;
}

export interface CatalogTranslations {[key: string]: {
  name?: string;
  description?: string;
}}

export interface CatalogCategory {
  id: string;
  name: string;
  sortOrder: number;
  active: boolean;
  color?: string | null;
  icon?: string | null;
  nameEn: string;
  translations?: CatalogTranslations | null;
}

export interface CatalogSubcategory {
  id: string;
  categoryId: string;
  name: string;
  sortOrder: number;
  active: boolean;
}

export type CatalogCategoryWithSubcategories = CatalogCategory & {
  subcategories: CatalogSubcategory[];
};

export interface CatalogCreateCategoryInput {
  name: string;
  color?: string | null;
  icon?: string | null;
  sortOrder?: number;
}

export interface CatalogSortOrderItem {
  id: string;
  sortOrder: number;
}

export interface CatalogSortOrderInput {
  order: CatalogSortOrderItem[];
}

export interface CatalogUpdateCategoryInput {
  name?: string;
  color?: string | null;
  icon?: string | null;
  active?: boolean;
  sortOrder?: number;
  translations?: CatalogTranslations;
}

export interface CatalogCategoryTranslationsInput {
  nameEn?: string;
}

export interface CatalogCategoryTranslationsResult {
  ok: true;
  nameEn: string;
}

export interface CatalogCreateSubcategoryInput {
  categoryId: string;
  name: string;
  sortOrder?: number;
}

export interface CatalogUpdateSubcategoryInput {
  name?: string;
  active?: boolean;
  sortOrder?: number;
}

export interface CatalogProductModifierGroupRef {
  productId: string;
  groupId: string;
  groupName: string;
  required: boolean;
}

/**
 * Admin product list item with nested formats and modifier groups
 */
export interface CatalogProduct {
  id: string;
  name: string;
  internalCode?: string | null;
  description?: string | null;
  /** Numeric string from DB */
  price: string;
  cost?: string | null;
  taxRate: CatalogTaxRate;
  categoryId: string;
  subcategoryId?: string | null;
  prepZone: string;
  active: boolean;
  tpvVisible: boolean;
  qrVisible: boolean;
  deliveryVisible: boolean;
  outOfStock: boolean;
  allergens: string;
  sortOrder: number;
  imageUrl?: string | null;
  videoUrl?: string | null;
  halfPortionPrice?: string | null;
  quantity?: string | null;
  isVegetariano?: boolean;
  isVegano?: boolean;
  isSinGluten?: boolean;
  isPicante?: boolean;
  categoryName: string;
  formats: CatalogProductFormat[];
  modifierGroups: CatalogProductModifierGroupRef[];
}

export interface CatalogCreateProductInput {
  categoryId: string;
  subcategoryId?: string;
  name: string;
  internalCode?: string;
  description?: string;
  price: string;
  cost?: string;
  prepZone?: string;
  active?: boolean;
  tpvVisible?: boolean;
  qrVisible?: boolean;
  deliveryVisible?: boolean;
  taxRate?: CatalogTaxRate;
  sortOrder?: number;
  allergens?: string;
  halfPortionPrice?: string;
  quantity?: string;
  isVegetariano?: boolean;
  isVegano?: boolean;
  isSinGluten?: boolean;
  isPicante?: boolean;
}

export interface CatalogProductImportResult {
  imported: number;
  skipped: number;
  errors: string[];
}

export interface CatalogUpdateProductInput {
  categoryId?: string;
  subcategoryId?: string | null;
  name?: string;
  internalCode?: string | null;
  description?: string | null;
  price?: string;
  cost?: string | null;
  prepZone?: string;
  active?: boolean;
  tpvVisible?: boolean;
  qrVisible?: boolean;
  deliveryVisible?: boolean;
  outOfStock?: boolean;
  taxRate?: CatalogTaxRate;
  sortOrder?: number;
  allergens?: string;
  imageUrl?: string | null;
  videoUrl?: string | null;
  halfPortionPrice?: string | null;
  quantity?: string | null;
  isVegetariano?: boolean;
  isVegano?: boolean;
  isSinGluten?: boolean;
  isPicante?: boolean;
  translations?: CatalogTranslations;
}

/**
 * Full product row returned by create/update
 */
export interface CatalogProductDetail {
  id: string;
  categoryId: string;
  subcategoryId?: string | null;
  name: string;
  internalCode?: string | null;
  description?: string | null;
  price: string;
  cost?: string | null;
  imageUrl?: string | null;
  videoUrl?: string | null;
  prepZone: string;
  active: boolean;
  tpvVisible?: boolean;
  qrVisible?: boolean;
  deliveryVisible?: boolean;
  outOfStock?: boolean;
  allergens?: string;
  sortOrder?: number;
  taxRate: CatalogTaxRate;
  halfPortionPrice?: string | null;
  quantity?: string | null;
  isVegetariano?: boolean;
  isVegano?: boolean;
  isSinGluten?: boolean;
  isPicante?: boolean;
  nameEn?: string;
  descriptionEn?: string;
  nameEs?: string;
  descriptionEs?: string;
  translations?: CatalogTranslations | null;
}

export interface CatalogProductModifierGroupsInput {
  modifierGroupIds: string[];
}

export interface CatalogSoldoutInput {
  outOfStock: boolean;
}

export interface CatalogSoldoutResult {
  ok: true;
  outOfStock: boolean;
}

export interface CatalogProductTranslationsInput {
  nameEn?: string;
  descriptionEn?: string;
  nameEs?: string;
  descriptionEs?: string;
}

export interface CatalogProductTranslationsResult {
  ok: true;
  nameEn: string;
  descriptionEn: string;
}

export interface CatalogProductAvailabilityRule {
  id: string;
  productId?: string | null;
  categoryId?: string | null;
  label: string;
  /**
     * Day-of-week numbers 0=Sun … 6=Sat
     * @items.minimum 0
     * @items.maximum 6
     */
  daysOfWeek: number[];
  /** HH:mm */
  timeFrom: string;
  /** HH:mm */
  timeTo: string;
  active: boolean;
  createdAt: string;
}

export interface CatalogCreateProductAvailabilityRuleInput {
  productId?: string;
  categoryId?: string;
  label?: string;
  /**
     * @items.minimum 0
     * @items.maximum 6
     */
  daysOfWeek?: number[];
  timeFrom?: string;
  timeTo?: string;
  active?: boolean;
}

export interface CatalogUpdateProductAvailabilityRuleInput {
  productId?: string | null;
  categoryId?: string | null;
  label?: string;
  /**
     * @items.minimum 0
     * @items.maximum 6
     */
  daysOfWeek?: number[];
  timeFrom?: string;
  timeTo?: string;
  active?: boolean;
}

export interface CatalogModifierGroup {
  id: string;
  name: string;
  required: boolean;
  maxSelect: number;
  sortOrder: number;
  active: boolean;
}

export interface CatalogModifier {
  id: string;
  groupId: string;
  name: string;
  /** Numeric string from DB */
  priceDelta: string;
  sortOrder: number;
  active: boolean;
}

export type CatalogModifierGroupWithModifiers = CatalogModifierGroup & {
  modifiers: CatalogModifier[];
};

export interface CatalogCreateModifierGroupInput {
  name: string;
  required?: boolean;
  maxSelect?: number;
  sortOrder?: number;
}

export interface CatalogUpdateModifierGroupInput {
  name?: string;
  required?: boolean;
  maxSelect?: number;
  active?: boolean;
  sortOrder?: number;
}

export interface CatalogCreateModifierInput {
  name: string;
  priceDelta?: string;
  sortOrder?: number;
}

export interface CatalogUpdateModifierInput {
  name?: string;
  priceDelta?: string;
  active?: boolean;
  sortOrder?: number;
}

/**
 * EU Regulation 1169/2011 allergen catalogue entry
 */
export interface CatalogAllergen {
  code: string;
  nameEs: string;
  nameEn: string;
  description: string;
  iconSlug: string;
  active: boolean;
  sortOrder: string;
}

export type CatalogProductAllergenCacheEntryType = typeof CatalogProductAllergenCacheEntryType[keyof typeof CatalogProductAllergenCacheEntryType];


export const CatalogProductAllergenCacheEntryType = {
  contains: 'contains',
  traces: 'traces',
  cross_contamination: 'cross_contamination',
} as const;

export type CatalogProductAllergenCacheEntrySource = typeof CatalogProductAllergenCacheEntrySource[keyof typeof CatalogProductAllergenCacheEntrySource];


export const CatalogProductAllergenCacheEntrySource = {
  ingredient: 'ingredient',
  subrecipe: 'subrecipe',
  manual: 'manual',
} as const;

export interface CatalogProductAllergenCacheEntry {
  allergenCode: string;
  type: CatalogProductAllergenCacheEntryType;
  source: CatalogProductAllergenCacheEntrySource;
  needsReview: boolean;
  calculatedAt: string;
  allergenName: string;
  allergenNameEn: string;
  iconSlug: string;
}

export type CatalogProductAllergenOverrideType = typeof CatalogProductAllergenOverrideType[keyof typeof CatalogProductAllergenOverrideType];


export const CatalogProductAllergenOverrideType = {
  contains: 'contains',
  traces: 'traces',
  cross_contamination: 'cross_contamination',
} as const;

export interface CatalogProductAllergenOverride {
  allergenCode: string;
  type: CatalogProductAllergenOverrideType;
  allergenName: string;
  iconSlug: string;
}

export interface CatalogProductAllergensResponse {
  cache: CatalogProductAllergenCacheEntry[];
  overrides: CatalogProductAllergenOverride[];
  needsReview: boolean;
}

export type CatalogProductAllergenOverrideInputType = typeof CatalogProductAllergenOverrideInputType[keyof typeof CatalogProductAllergenOverrideInputType];


export const CatalogProductAllergenOverrideInputType = {
  contains: 'contains',
  traces: 'traces',
  cross_contamination: 'cross_contamination',
} as const;

export interface CatalogProductAllergenOverrideInput {
  allergenCode: string;
  type: CatalogProductAllergenOverrideInputType;
  note?: string;
}

/**
 * Product row from GET /products staff search
 */
export interface CatalogStaffProductSearchItem {
  id: string;
  name: string;
  price: string;
  taxRate: CatalogTaxRate;
  active: boolean;
  outOfStock: boolean;
  imageUrl?: string | null;
  categoryId: string;
  tpvVisible: boolean;
  deliveryVisible: boolean;
}

export interface ErrorResponse {
  error: string;
}

/**
 * Authentication is required or invalid
 */
export type UnauthorizedResponse = ErrorResponse;

/**
 * Request validation failed
 */
export type BadRequestResponse = ErrorResponse;

/**
 * The authenticated user lacks the required role or permission
 */
export type ForbiddenResponse = ErrorResponse;

/**
 * Requested resource was not found
 */
export type NotFoundResponse = ErrorResponse;

export type GetCatalogAdminProductsParams = {
categoryId?: string;
active?: GetCatalogAdminProductsActive;
search?: string;
};

export type GetCatalogAdminProductsActive = typeof GetCatalogAdminProductsActive[keyof typeof GetCatalogAdminProductsActive];


export const GetCatalogAdminProductsActive = {
  true: 'true',
  false: 'false',
} as const;

export type ExportCatalogAdminProductsParams = {
format?: ExportCatalogAdminProductsFormat;
};

export type ExportCatalogAdminProductsFormat = typeof ExportCatalogAdminProductsFormat[keyof typeof ExportCatalogAdminProductsFormat];


export const ExportCatalogAdminProductsFormat = {
  csv: 'csv',
  xlsx: 'xlsx',
} as const;

export type ImportCatalogAdminProductsBody = {
  file: Blob;
};

export type SearchCatalogProductsParams = {
q?: string;
/**
 * @maximum 50
 */
limit?: number;
};

