// Generated compatibility exports. Do not edit manually.
export {
  getAdminBranding,
  getAdminQrBranding,
  getGetAdminBrandingQueryKey,
  getGetAdminBrandingQueryOptions,
  getGetAdminBrandingUrl,
  getGetAdminQrBrandingQueryKey,
  getGetAdminQrBrandingQueryOptions,
  getGetAdminQrBrandingUrl,
  getGetPublicBrandingQueryKey,
  getGetPublicBrandingQueryOptions,
  getGetPublicBrandingUrl,
  getPatchAdminBrandingMutationOptions,
  getPatchAdminBrandingUrl,
  getPublicBranding,
  getPutAdminQrBrandingMutationOptions,
  getPutAdminQrBrandingUrl,
  patchAdminBranding,
  putAdminQrBranding,
  useGetAdminBranding,
  useGetAdminQrBranding,
  useGetPublicBranding,
  usePatchAdminBranding,
  usePutAdminQrBranding,
} from "./branding-generated/api";
export type {
  GetAdminBrandingQueryError,
  GetAdminBrandingQueryResult,
  GetAdminQrBrandingQueryError,
  GetAdminQrBrandingQueryResult,
  GetPublicBrandingQueryError,
  GetPublicBrandingQueryResult,
  PatchAdminBrandingMutationBody,
  PatchAdminBrandingMutationError,
  PatchAdminBrandingMutationResult,
  PutAdminQrBrandingMutationBody,
  PutAdminQrBrandingMutationError,
  PutAdminQrBrandingMutationResult,
} from "./branding-generated/api";
export type {
  AdminBranding,
  BrandingCardSettings,
  BrandingCardSettingsLayout,
  BrandingInput,
  BrandingThemeColors,
  BrandingThemeFonts,
  OpeningHours,
  OpeningHoursDay,
  PublicBrandingResponse,
  QrBranding,
  QrBrandingOkResponse,
  QrDaySchedule,
  QrNotConfiguredError,
  QrNotConfiguredErrorCode,
  QrShift,
  UpdateQrBrandingInput,
} from "./branding-generated/api.schemas";
