/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Api
 * Piccolo TPV API
 * OpenAPI spec version: 0.2.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  BadRequestResponse,
  Client,
  ConflictResponse,
  CreateClientInput,
  CreateDocumentTemplateInput,
  CreateInvoiceInput,
  CreatePrinterConfigInput,
  CreateReprintInput,
  DeleteDocumentTemplate200,
  DeletePrinterConfig200,
  DocumentAuditLog,
  DocumentReprint,
  DocumentTemplate,
  ForbiddenResponse,
  GetDocumentAuditLogParams,
  GetDocumentTemplatesParams,
  GetInvoice200,
  Invoice,
  NotFoundResponse,
  PrinterConfig,
  RectifyInvoice201,
  RectifyInvoiceInput,
  ServiceUnavailableResponse,
  UnauthorizedResponse,
  UpdateClientInput,
  UpdateDocumentTemplateInput,
  UpdatePrinterConfigInput
} from './api.schemas';

import { customFetch } from '../custom-fetch';
import type { ErrorType , BodyType } from '../custom-fetch';

type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const getGetDocumentTemplatesUrl = (params?: GetDocumentTemplatesParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/documents/templates?${stringifiedParams}` : `/api/documents/templates`
}

/**
 * @summary List document templates (admin)
 */
export const getDocumentTemplates = async (params?: GetDocumentTemplatesParams, options?: RequestInit): Promise<DocumentTemplate[]> => {

  return customFetch<DocumentTemplate[]>(getGetDocumentTemplatesUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetDocumentTemplatesQueryKey = (params?: GetDocumentTemplatesParams,) => {
    return [
    `/api/documents/templates`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetDocumentTemplatesQueryOptions = <TData = Awaited<ReturnType<typeof getDocumentTemplates>>, TError = ErrorType<UnauthorizedResponse | ForbiddenResponse | ServiceUnavailableResponse>>(params?: GetDocumentTemplatesParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getDocumentTemplates>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetDocumentTemplatesQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getDocumentTemplates>>> = ({ signal }) => getDocumentTemplates(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getDocumentTemplates>>, TError, TData> & { queryKey: QueryKey }
}

export type GetDocumentTemplatesQueryResult = NonNullable<Awaited<ReturnType<typeof getDocumentTemplates>>>
export type GetDocumentTemplatesQueryError = ErrorType<UnauthorizedResponse | ForbiddenResponse | ServiceUnavailableResponse>


/**
 * @summary List document templates (admin)
 */

export function useGetDocumentTemplates<TData = Awaited<ReturnType<typeof getDocumentTemplates>>, TError = ErrorType<UnauthorizedResponse | ForbiddenResponse | ServiceUnavailableResponse>>(
 params?: GetDocumentTemplatesParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getDocumentTemplates>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetDocumentTemplatesQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}







export const getCreateDocumentTemplateUrl = () => {




  return `/api/documents/templates`
}

/**
 * @summary Create a document template (admin)
 */
export const createDocumentTemplate = async (createDocumentTemplateInput: CreateDocumentTemplateInput, options?: RequestInit): Promise<DocumentTemplate> => {

  return customFetch<DocumentTemplate>(getCreateDocumentTemplateUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createDocumentTemplateInput)
  }
);}





export const getCreateDocumentTemplateMutationOptions = <TError = ErrorType<BadRequestResponse | UnauthorizedResponse | ForbiddenResponse | ServiceUnavailableResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createDocumentTemplate>>, TError,{data: BodyType<CreateDocumentTemplateInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof createDocumentTemplate>>, TError,{data: BodyType<CreateDocumentTemplateInput>}, TContext> => {

const mutationKey = ['createDocumentTemplate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createDocumentTemplate>>, {data: BodyType<CreateDocumentTemplateInput>}> = (props) => {
          const {data} = props ?? {};

          return  createDocumentTemplate(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateDocumentTemplateMutationResult = NonNullable<Awaited<ReturnType<typeof createDocumentTemplate>>>
    export type CreateDocumentTemplateMutationBody = BodyType<CreateDocumentTemplateInput>
    export type CreateDocumentTemplateMutationError = ErrorType<BadRequestResponse | UnauthorizedResponse | ForbiddenResponse | ServiceUnavailableResponse>

    /**
 * @summary Create a document template (admin)
 */
export const useCreateDocumentTemplate = <TError = ErrorType<BadRequestResponse | UnauthorizedResponse | ForbiddenResponse | ServiceUnavailableResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createDocumentTemplate>>, TError,{data: BodyType<CreateDocumentTemplateInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof createDocumentTemplate>>,
        TError,
        {data: BodyType<CreateDocumentTemplateInput>},
        TContext
      > => {
      return useMutation(getCreateDocumentTemplateMutationOptions(options));
    }

export const getUpdateDocumentTemplateUrl = (id: string,) => {




  return `/api/documents/templates/${id}`
}

/**
 * @summary Update a document template (admin)
 */
export const updateDocumentTemplate = async (id: string,
    updateDocumentTemplateInput: UpdateDocumentTemplateInput, options?: RequestInit): Promise<DocumentTemplate> => {

  return customFetch<DocumentTemplate>(getUpdateDocumentTemplateUrl(id),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updateDocumentTemplateInput)
  }
);}





export const getUpdateDocumentTemplateMutationOptions = <TError = ErrorType<UnauthorizedResponse | ForbiddenResponse | NotFoundResponse | ServiceUnavailableResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateDocumentTemplate>>, TError,{id: string;data: BodyType<UpdateDocumentTemplateInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof updateDocumentTemplate>>, TError,{id: string;data: BodyType<UpdateDocumentTemplateInput>}, TContext> => {

const mutationKey = ['updateDocumentTemplate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateDocumentTemplate>>, {id: string;data: BodyType<UpdateDocumentTemplateInput>}> = (props) => {
          const {id,data} = props ?? {};

          return  updateDocumentTemplate(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateDocumentTemplateMutationResult = NonNullable<Awaited<ReturnType<typeof updateDocumentTemplate>>>
    export type UpdateDocumentTemplateMutationBody = BodyType<UpdateDocumentTemplateInput>
    export type UpdateDocumentTemplateMutationError = ErrorType<UnauthorizedResponse | ForbiddenResponse | NotFoundResponse | ServiceUnavailableResponse>

    /**
 * @summary Update a document template (admin)
 */
export const useUpdateDocumentTemplate = <TError = ErrorType<UnauthorizedResponse | ForbiddenResponse | NotFoundResponse | ServiceUnavailableResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateDocumentTemplate>>, TError,{id: string;data: BodyType<UpdateDocumentTemplateInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof updateDocumentTemplate>>,
        TError,
        {id: string;data: BodyType<UpdateDocumentTemplateInput>},
        TContext
      > => {
      return useMutation(getUpdateDocumentTemplateMutationOptions(options));
    }

export const getDeleteDocumentTemplateUrl = (id: string,) => {




  return `/api/documents/templates/${id}`
}

/**
 * @summary Soft-delete a template (admin, cannot delete active)
 */
export const deleteDocumentTemplate = async (id: string, options?: RequestInit): Promise<DeleteDocumentTemplate200> => {

  return customFetch<DeleteDocumentTemplate200>(getDeleteDocumentTemplateUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}





export const getDeleteDocumentTemplateMutationOptions = <TError = ErrorType<UnauthorizedResponse | ForbiddenResponse | NotFoundResponse | ConflictResponse | ServiceUnavailableResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteDocumentTemplate>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteDocumentTemplate>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteDocumentTemplate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteDocumentTemplate>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteDocumentTemplate(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteDocumentTemplateMutationResult = NonNullable<Awaited<ReturnType<typeof deleteDocumentTemplate>>>

    export type DeleteDocumentTemplateMutationError = ErrorType<UnauthorizedResponse | ForbiddenResponse | NotFoundResponse | ConflictResponse | ServiceUnavailableResponse>

    /**
 * @summary Soft-delete a template (admin, cannot delete active)
 */
export const useDeleteDocumentTemplate = <TError = ErrorType<UnauthorizedResponse | ForbiddenResponse | NotFoundResponse | ConflictResponse | ServiceUnavailableResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteDocumentTemplate>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof deleteDocumentTemplate>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getDeleteDocumentTemplateMutationOptions(options));
    }

export const getActivateDocumentTemplateUrl = (id: string,) => {




  return `/api/documents/templates/${id}/activate`
}

/**
 * @summary Set template as default (admin)
 */
export const activateDocumentTemplate = async (id: string, options?: RequestInit): Promise<DocumentTemplate> => {

  return customFetch<DocumentTemplate>(getActivateDocumentTemplateUrl(id),
  {
    ...options,
    method: 'POST'


  }
);}





export const getActivateDocumentTemplateMutationOptions = <TError = ErrorType<UnauthorizedResponse | ForbiddenResponse | NotFoundResponse | ServiceUnavailableResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof activateDocumentTemplate>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof activateDocumentTemplate>>, TError,{id: string}, TContext> => {

const mutationKey = ['activateDocumentTemplate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof activateDocumentTemplate>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  activateDocumentTemplate(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ActivateDocumentTemplateMutationResult = NonNullable<Awaited<ReturnType<typeof activateDocumentTemplate>>>

    export type ActivateDocumentTemplateMutationError = ErrorType<UnauthorizedResponse | ForbiddenResponse | NotFoundResponse | ServiceUnavailableResponse>

    /**
 * @summary Set template as default (admin)
 */
export const useActivateDocumentTemplate = <TError = ErrorType<UnauthorizedResponse | ForbiddenResponse | NotFoundResponse | ServiceUnavailableResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof activateDocumentTemplate>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof activateDocumentTemplate>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getActivateDocumentTemplateMutationOptions(options));
    }

export const getDuplicateDocumentTemplateUrl = (id: string,) => {




  return `/api/documents/templates/${id}/duplicate`
}

/**
 * @summary Clone a template (admin)
 */
export const duplicateDocumentTemplate = async (id: string, options?: RequestInit): Promise<DocumentTemplate> => {

  return customFetch<DocumentTemplate>(getDuplicateDocumentTemplateUrl(id),
  {
    ...options,
    method: 'POST'


  }
);}





export const getDuplicateDocumentTemplateMutationOptions = <TError = ErrorType<UnauthorizedResponse | ForbiddenResponse | NotFoundResponse | ServiceUnavailableResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof duplicateDocumentTemplate>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof duplicateDocumentTemplate>>, TError,{id: string}, TContext> => {

const mutationKey = ['duplicateDocumentTemplate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof duplicateDocumentTemplate>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  duplicateDocumentTemplate(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DuplicateDocumentTemplateMutationResult = NonNullable<Awaited<ReturnType<typeof duplicateDocumentTemplate>>>

    export type DuplicateDocumentTemplateMutationError = ErrorType<UnauthorizedResponse | ForbiddenResponse | NotFoundResponse | ServiceUnavailableResponse>

    /**
 * @summary Clone a template (admin)
 */
export const useDuplicateDocumentTemplate = <TError = ErrorType<UnauthorizedResponse | ForbiddenResponse | NotFoundResponse | ServiceUnavailableResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof duplicateDocumentTemplate>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof duplicateDocumentTemplate>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getDuplicateDocumentTemplateMutationOptions(options));
    }

export const getGetPrinterConfigsUrl = () => {




  return `/api/documents/printers`
}

/**
 * @summary List printer configurations (admin)
 */
export const getPrinterConfigs = async ( options?: RequestInit): Promise<PrinterConfig[]> => {

  return customFetch<PrinterConfig[]>(getGetPrinterConfigsUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetPrinterConfigsQueryKey = () => {
    return [
    `/api/documents/printers`
    ] as const;
    }


export const getGetPrinterConfigsQueryOptions = <TData = Awaited<ReturnType<typeof getPrinterConfigs>>, TError = ErrorType<UnauthorizedResponse | ForbiddenResponse | ServiceUnavailableResponse>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getPrinterConfigs>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetPrinterConfigsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getPrinterConfigs>>> = ({ signal }) => getPrinterConfigs({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getPrinterConfigs>>, TError, TData> & { queryKey: QueryKey }
}

export type GetPrinterConfigsQueryResult = NonNullable<Awaited<ReturnType<typeof getPrinterConfigs>>>
export type GetPrinterConfigsQueryError = ErrorType<UnauthorizedResponse | ForbiddenResponse | ServiceUnavailableResponse>


/**
 * @summary List printer configurations (admin)
 */

export function useGetPrinterConfigs<TData = Awaited<ReturnType<typeof getPrinterConfigs>>, TError = ErrorType<UnauthorizedResponse | ForbiddenResponse | ServiceUnavailableResponse>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getPrinterConfigs>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetPrinterConfigsQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}







export const getCreatePrinterConfigUrl = () => {




  return `/api/documents/printers`
}

/**
 * @summary Create printer configuration (admin)
 */
export const createPrinterConfig = async (createPrinterConfigInput: CreatePrinterConfigInput, options?: RequestInit): Promise<PrinterConfig> => {

  return customFetch<PrinterConfig>(getCreatePrinterConfigUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createPrinterConfigInput)
  }
);}





export const getCreatePrinterConfigMutationOptions = <TError = ErrorType<BadRequestResponse | UnauthorizedResponse | ForbiddenResponse | ServiceUnavailableResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createPrinterConfig>>, TError,{data: BodyType<CreatePrinterConfigInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof createPrinterConfig>>, TError,{data: BodyType<CreatePrinterConfigInput>}, TContext> => {

const mutationKey = ['createPrinterConfig'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createPrinterConfig>>, {data: BodyType<CreatePrinterConfigInput>}> = (props) => {
          const {data} = props ?? {};

          return  createPrinterConfig(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreatePrinterConfigMutationResult = NonNullable<Awaited<ReturnType<typeof createPrinterConfig>>>
    export type CreatePrinterConfigMutationBody = BodyType<CreatePrinterConfigInput>
    export type CreatePrinterConfigMutationError = ErrorType<BadRequestResponse | UnauthorizedResponse | ForbiddenResponse | ServiceUnavailableResponse>

    /**
 * @summary Create printer configuration (admin)
 */
export const useCreatePrinterConfig = <TError = ErrorType<BadRequestResponse | UnauthorizedResponse | ForbiddenResponse | ServiceUnavailableResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createPrinterConfig>>, TError,{data: BodyType<CreatePrinterConfigInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof createPrinterConfig>>,
        TError,
        {data: BodyType<CreatePrinterConfigInput>},
        TContext
      > => {
      return useMutation(getCreatePrinterConfigMutationOptions(options));
    }

export const getUpdatePrinterConfigUrl = (id: string,) => {




  return `/api/documents/printers/${id}`
}

/**
 * @summary Update printer configuration (admin)
 */
export const updatePrinterConfig = async (id: string,
    updatePrinterConfigInput: UpdatePrinterConfigInput, options?: RequestInit): Promise<PrinterConfig> => {

  return customFetch<PrinterConfig>(getUpdatePrinterConfigUrl(id),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updatePrinterConfigInput)
  }
);}





export const getUpdatePrinterConfigMutationOptions = <TError = ErrorType<UnauthorizedResponse | ForbiddenResponse | NotFoundResponse | ServiceUnavailableResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updatePrinterConfig>>, TError,{id: string;data: BodyType<UpdatePrinterConfigInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof updatePrinterConfig>>, TError,{id: string;data: BodyType<UpdatePrinterConfigInput>}, TContext> => {

const mutationKey = ['updatePrinterConfig'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updatePrinterConfig>>, {id: string;data: BodyType<UpdatePrinterConfigInput>}> = (props) => {
          const {id,data} = props ?? {};

          return  updatePrinterConfig(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdatePrinterConfigMutationResult = NonNullable<Awaited<ReturnType<typeof updatePrinterConfig>>>
    export type UpdatePrinterConfigMutationBody = BodyType<UpdatePrinterConfigInput>
    export type UpdatePrinterConfigMutationError = ErrorType<UnauthorizedResponse | ForbiddenResponse | NotFoundResponse | ServiceUnavailableResponse>

    /**
 * @summary Update printer configuration (admin)
 */
export const useUpdatePrinterConfig = <TError = ErrorType<UnauthorizedResponse | ForbiddenResponse | NotFoundResponse | ServiceUnavailableResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updatePrinterConfig>>, TError,{id: string;data: BodyType<UpdatePrinterConfigInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof updatePrinterConfig>>,
        TError,
        {id: string;data: BodyType<UpdatePrinterConfigInput>},
        TContext
      > => {
      return useMutation(getUpdatePrinterConfigMutationOptions(options));
    }

export const getDeletePrinterConfigUrl = (id: string,) => {




  return `/api/documents/printers/${id}`
}

/**
 * @summary Deactivate printer (admin)
 */
export const deletePrinterConfig = async (id: string, options?: RequestInit): Promise<DeletePrinterConfig200> => {

  return customFetch<DeletePrinterConfig200>(getDeletePrinterConfigUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}





export const getDeletePrinterConfigMutationOptions = <TError = ErrorType<UnauthorizedResponse | ForbiddenResponse | ServiceUnavailableResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deletePrinterConfig>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof deletePrinterConfig>>, TError,{id: string}, TContext> => {

const mutationKey = ['deletePrinterConfig'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deletePrinterConfig>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deletePrinterConfig(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeletePrinterConfigMutationResult = NonNullable<Awaited<ReturnType<typeof deletePrinterConfig>>>

    export type DeletePrinterConfigMutationError = ErrorType<UnauthorizedResponse | ForbiddenResponse | ServiceUnavailableResponse>

    /**
 * @summary Deactivate printer (admin)
 */
export const useDeletePrinterConfig = <TError = ErrorType<UnauthorizedResponse | ForbiddenResponse | ServiceUnavailableResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deletePrinterConfig>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof deletePrinterConfig>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getDeletePrinterConfigMutationOptions(options));
    }

export const getCreateInvoiceUrl = () => {




  return `/api/documents/invoices`
}

/**
 * @summary Issue a full fiscal invoice for an order
 */
export const createInvoice = async (createInvoiceInput: CreateInvoiceInput, options?: RequestInit): Promise<Invoice> => {

  return customFetch<Invoice>(getCreateInvoiceUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createInvoiceInput)
  }
);}





export const getCreateInvoiceMutationOptions = <TError = ErrorType<BadRequestResponse | UnauthorizedResponse | ForbiddenResponse | NotFoundResponse | ServiceUnavailableResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createInvoice>>, TError,{data: BodyType<CreateInvoiceInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof createInvoice>>, TError,{data: BodyType<CreateInvoiceInput>}, TContext> => {

const mutationKey = ['createInvoice'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createInvoice>>, {data: BodyType<CreateInvoiceInput>}> = (props) => {
          const {data} = props ?? {};

          return  createInvoice(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateInvoiceMutationResult = NonNullable<Awaited<ReturnType<typeof createInvoice>>>
    export type CreateInvoiceMutationBody = BodyType<CreateInvoiceInput>
    export type CreateInvoiceMutationError = ErrorType<BadRequestResponse | UnauthorizedResponse | ForbiddenResponse | NotFoundResponse | ServiceUnavailableResponse>

    /**
 * @summary Issue a full fiscal invoice for an order
 */
export const useCreateInvoice = <TError = ErrorType<BadRequestResponse | UnauthorizedResponse | ForbiddenResponse | NotFoundResponse | ServiceUnavailableResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createInvoice>>, TError,{data: BodyType<CreateInvoiceInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof createInvoice>>,
        TError,
        {data: BodyType<CreateInvoiceInput>},
        TContext
      > => {
      return useMutation(getCreateInvoiceMutationOptions(options));
    }

export const getGetInvoiceUrl = (id: string,) => {




  return `/api/documents/invoices/${id}`
}

/**
 * @summary Get invoice by ID
 */
export const getInvoice = async (id: string, options?: RequestInit): Promise<GetInvoice200> => {

  return customFetch<GetInvoice200>(getGetInvoiceUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetInvoiceQueryKey = (id: string,) => {
    return [
    `/api/documents/invoices/${id}`
    ] as const;
    }


export const getGetInvoiceQueryOptions = <TData = Awaited<ReturnType<typeof getInvoice>>, TError = ErrorType<UnauthorizedResponse | ForbiddenResponse | NotFoundResponse | ServiceUnavailableResponse>>(id: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getInvoice>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetInvoiceQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getInvoice>>> = ({ signal }) => getInvoice(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getInvoice>>, TError, TData> & { queryKey: QueryKey }
}

export type GetInvoiceQueryResult = NonNullable<Awaited<ReturnType<typeof getInvoice>>>
export type GetInvoiceQueryError = ErrorType<UnauthorizedResponse | ForbiddenResponse | NotFoundResponse | ServiceUnavailableResponse>


/**
 * @summary Get invoice by ID
 */

export function useGetInvoice<TData = Awaited<ReturnType<typeof getInvoice>>, TError = ErrorType<UnauthorizedResponse | ForbiddenResponse | NotFoundResponse | ServiceUnavailableResponse>>(
 id: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getInvoice>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetInvoiceQueryOptions(id,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}







export const getRectifyInvoiceUrl = (id: string,) => {




  return `/api/documents/invoices/${id}/rectify`
}

/**
 * @summary Create a rectificativa (admin)
 */
export const rectifyInvoice = async (id: string,
    rectifyInvoiceInput: RectifyInvoiceInput, options?: RequestInit): Promise<RectifyInvoice201> => {

  return customFetch<RectifyInvoice201>(getRectifyInvoiceUrl(id),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(rectifyInvoiceInput)
  }
);}





export const getRectifyInvoiceMutationOptions = <TError = ErrorType<BadRequestResponse | UnauthorizedResponse | ForbiddenResponse | NotFoundResponse | ConflictResponse | ServiceUnavailableResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof rectifyInvoice>>, TError,{id: string;data: BodyType<RectifyInvoiceInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof rectifyInvoice>>, TError,{id: string;data: BodyType<RectifyInvoiceInput>}, TContext> => {

const mutationKey = ['rectifyInvoice'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof rectifyInvoice>>, {id: string;data: BodyType<RectifyInvoiceInput>}> = (props) => {
          const {id,data} = props ?? {};

          return  rectifyInvoice(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type RectifyInvoiceMutationResult = NonNullable<Awaited<ReturnType<typeof rectifyInvoice>>>
    export type RectifyInvoiceMutationBody = BodyType<RectifyInvoiceInput>
    export type RectifyInvoiceMutationError = ErrorType<BadRequestResponse | UnauthorizedResponse | ForbiddenResponse | NotFoundResponse | ConflictResponse | ServiceUnavailableResponse>

    /**
 * @summary Create a rectificativa (admin)
 */
export const useRectifyInvoice = <TError = ErrorType<BadRequestResponse | UnauthorizedResponse | ForbiddenResponse | NotFoundResponse | ConflictResponse | ServiceUnavailableResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof rectifyInvoice>>, TError,{id: string;data: BodyType<RectifyInvoiceInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof rectifyInvoice>>,
        TError,
        {id: string;data: BodyType<RectifyInvoiceInput>},
        TContext
      > => {
      return useMutation(getRectifyInvoiceMutationOptions(options));
    }

export const getGetClientsUrl = () => {




  return `/api/documents/clients`
}

/**
 * @summary List saved client data (admin/manager)
 */
export const getClients = async ( options?: RequestInit): Promise<Client[]> => {

  return customFetch<Client[]>(getGetClientsUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetClientsQueryKey = () => {
    return [
    `/api/documents/clients`
    ] as const;
    }


export const getGetClientsQueryOptions = <TData = Awaited<ReturnType<typeof getClients>>, TError = ErrorType<UnauthorizedResponse | ForbiddenResponse | ServiceUnavailableResponse>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getClients>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetClientsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getClients>>> = ({ signal }) => getClients({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getClients>>, TError, TData> & { queryKey: QueryKey }
}

export type GetClientsQueryResult = NonNullable<Awaited<ReturnType<typeof getClients>>>
export type GetClientsQueryError = ErrorType<UnauthorizedResponse | ForbiddenResponse | ServiceUnavailableResponse>


/**
 * @summary List saved client data (admin/manager)
 */

export function useGetClients<TData = Awaited<ReturnType<typeof getClients>>, TError = ErrorType<UnauthorizedResponse | ForbiddenResponse | ServiceUnavailableResponse>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getClients>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetClientsQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}







export const getCreateClientUrl = () => {




  return `/api/documents/clients`
}

/**
 * @summary Save client fiscal data (admin/manager)
 */
export const createClient = async (createClientInput: CreateClientInput, options?: RequestInit): Promise<Client> => {

  return customFetch<Client>(getCreateClientUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createClientInput)
  }
);}





export const getCreateClientMutationOptions = <TError = ErrorType<BadRequestResponse | UnauthorizedResponse | ForbiddenResponse | ServiceUnavailableResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createClient>>, TError,{data: BodyType<CreateClientInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof createClient>>, TError,{data: BodyType<CreateClientInput>}, TContext> => {

const mutationKey = ['createClient'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createClient>>, {data: BodyType<CreateClientInput>}> = (props) => {
          const {data} = props ?? {};

          return  createClient(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateClientMutationResult = NonNullable<Awaited<ReturnType<typeof createClient>>>
    export type CreateClientMutationBody = BodyType<CreateClientInput>
    export type CreateClientMutationError = ErrorType<BadRequestResponse | UnauthorizedResponse | ForbiddenResponse | ServiceUnavailableResponse>

    /**
 * @summary Save client fiscal data (admin/manager)
 */
export const useCreateClient = <TError = ErrorType<BadRequestResponse | UnauthorizedResponse | ForbiddenResponse | ServiceUnavailableResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createClient>>, TError,{data: BodyType<CreateClientInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof createClient>>,
        TError,
        {data: BodyType<CreateClientInput>},
        TContext
      > => {
      return useMutation(getCreateClientMutationOptions(options));
    }

export const getUpdateClientUrl = (id: string,) => {




  return `/api/documents/clients/${id}`
}

/**
 * @summary Update client fiscal data (admin/manager)
 */
export const updateClient = async (id: string,
    updateClientInput: UpdateClientInput, options?: RequestInit): Promise<Client> => {

  return customFetch<Client>(getUpdateClientUrl(id),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updateClientInput)
  }
);}





export const getUpdateClientMutationOptions = <TError = ErrorType<UnauthorizedResponse | ForbiddenResponse | NotFoundResponse | ServiceUnavailableResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateClient>>, TError,{id: string;data: BodyType<UpdateClientInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof updateClient>>, TError,{id: string;data: BodyType<UpdateClientInput>}, TContext> => {

const mutationKey = ['updateClient'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateClient>>, {id: string;data: BodyType<UpdateClientInput>}> = (props) => {
          const {id,data} = props ?? {};

          return  updateClient(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateClientMutationResult = NonNullable<Awaited<ReturnType<typeof updateClient>>>
    export type UpdateClientMutationBody = BodyType<UpdateClientInput>
    export type UpdateClientMutationError = ErrorType<UnauthorizedResponse | ForbiddenResponse | NotFoundResponse | ServiceUnavailableResponse>

    /**
 * @summary Update client fiscal data (admin/manager)
 */
export const useUpdateClient = <TError = ErrorType<UnauthorizedResponse | ForbiddenResponse | NotFoundResponse | ServiceUnavailableResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateClient>>, TError,{id: string;data: BodyType<UpdateClientInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof updateClient>>,
        TError,
        {id: string;data: BodyType<UpdateClientInput>},
        TContext
      > => {
      return useMutation(getUpdateClientMutationOptions(options));
    }

export const getCreateReprintUrl = () => {




  return `/api/documents/reprints`
}

/**
 * @summary Record a document reprint (any authenticated user)
 */
export const createReprint = async (createReprintInput: CreateReprintInput, options?: RequestInit): Promise<DocumentReprint> => {

  return customFetch<DocumentReprint>(getCreateReprintUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createReprintInput)
  }
);}





export const getCreateReprintMutationOptions = <TError = ErrorType<BadRequestResponse | UnauthorizedResponse | ServiceUnavailableResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createReprint>>, TError,{data: BodyType<CreateReprintInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof createReprint>>, TError,{data: BodyType<CreateReprintInput>}, TContext> => {

const mutationKey = ['createReprint'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createReprint>>, {data: BodyType<CreateReprintInput>}> = (props) => {
          const {data} = props ?? {};

          return  createReprint(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateReprintMutationResult = NonNullable<Awaited<ReturnType<typeof createReprint>>>
    export type CreateReprintMutationBody = BodyType<CreateReprintInput>
    export type CreateReprintMutationError = ErrorType<BadRequestResponse | UnauthorizedResponse | ServiceUnavailableResponse>

    /**
 * @summary Record a document reprint (any authenticated user)
 */
export const useCreateReprint = <TError = ErrorType<BadRequestResponse | UnauthorizedResponse | ServiceUnavailableResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createReprint>>, TError,{data: BodyType<CreateReprintInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof createReprint>>,
        TError,
        {data: BodyType<CreateReprintInput>},
        TContext
      > => {
      return useMutation(getCreateReprintMutationOptions(options));
    }

export const getGetDocumentAuditLogUrl = (params?: GetDocumentAuditLogParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/documents/audit?${stringifiedParams}` : `/api/documents/audit`
}

/**
 * @summary Paginated document audit log (admin)
 */
export const getDocumentAuditLog = async (params?: GetDocumentAuditLogParams, options?: RequestInit): Promise<DocumentAuditLog> => {

  return customFetch<DocumentAuditLog>(getGetDocumentAuditLogUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetDocumentAuditLogQueryKey = (params?: GetDocumentAuditLogParams,) => {
    return [
    `/api/documents/audit`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetDocumentAuditLogQueryOptions = <TData = Awaited<ReturnType<typeof getDocumentAuditLog>>, TError = ErrorType<UnauthorizedResponse | ForbiddenResponse | ServiceUnavailableResponse>>(params?: GetDocumentAuditLogParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getDocumentAuditLog>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetDocumentAuditLogQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getDocumentAuditLog>>> = ({ signal }) => getDocumentAuditLog(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getDocumentAuditLog>>, TError, TData> & { queryKey: QueryKey }
}

export type GetDocumentAuditLogQueryResult = NonNullable<Awaited<ReturnType<typeof getDocumentAuditLog>>>
export type GetDocumentAuditLogQueryError = ErrorType<UnauthorizedResponse | ForbiddenResponse | ServiceUnavailableResponse>


/**
 * @summary Paginated document audit log (admin)
 */

export function useGetDocumentAuditLog<TData = Awaited<ReturnType<typeof getDocumentAuditLog>>, TError = ErrorType<UnauthorizedResponse | ForbiddenResponse | ServiceUnavailableResponse>>(
 params?: GetDocumentAuditLogParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getDocumentAuditLog>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetDocumentAuditLogQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}







