/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Api
 * Piccolo TPV API
 * OpenAPI spec version: 0.2.0
 */
export type DocumentTemplateConfig = { [key: string]: unknown };

export interface DocumentTemplate {
  id: string;
  name: string;
  documentType: string;
  printFormat: string;
  isDefault: boolean;
  isBuiltIn: boolean;
  config: DocumentTemplateConfig;
  deletedAt: string | null;
  createdAt: string;
  updatedAt: string;
}

export type CreateDocumentTemplateInputConfig = { [key: string]: unknown };

export interface CreateDocumentTemplateInput {
  name: string;
  documentType: string;
  printFormat?: string;
  config?: CreateDocumentTemplateInputConfig;
}

export type UpdateDocumentTemplateInputConfig = { [key: string]: unknown };

export interface UpdateDocumentTemplateInput {
  name?: string;
  printFormat?: string;
  config?: UpdateDocumentTemplateInputConfig;
}

export interface PrinterConfig {
  id: string;
  name: string;
  printerType: string;
  paperWidth: number;
  location: string;
  documentType: string;
  copies: number;
  autoCut: boolean;
  cashDrawer: boolean;
  autoPrint: boolean;
  active: boolean;
  createdAt: string;
}

export interface CreatePrinterConfigInput {
  name: string;
  id?: string;
  printerType?: string;
  paperWidth?: number;
  location?: string;
  documentType?: string;
  copies?: number;
  autoCut?: boolean;
  cashDrawer?: boolean;
  autoPrint?: boolean;
  active?: boolean;
  createdAt?: string;
}

export interface UpdatePrinterConfigInput {
  id?: string;
  name?: string;
  printerType?: string;
  paperWidth?: number;
  location?: string;
  documentType?: string;
  copies?: number;
  autoCut?: boolean;
  cashDrawer?: boolean;
  autoPrint?: boolean;
  active?: boolean;
  createdAt?: string;
}

export interface CreateInvoiceInput {
  orderId: string;
  clientName?: string;
  clientNif?: string;
  clientAddress?: string;
  clientCp?: string;
  clientCity?: string;
  clientProvince?: string;
  clientCountry?: string;
  clientEmail?: string;
  clientPhone?: string;
  notes?: string;
}

export type InvoiceVerifactuResponse = { [key: string]: unknown } | null;

export type TaxBreakdownItemRate = typeof TaxBreakdownItemRate[keyof typeof TaxBreakdownItemRate];


export const TaxBreakdownItemRate = {
  NUMBER_4: 4,
  NUMBER_10: 10,
  NUMBER_21: 21,
} as const;

/**
 * @pattern ^-?\d+\.\d{2}$
 */
export type Money = string;

export interface TaxBreakdownItem {
  rate: TaxBreakdownItemRate;
  base: Money;
  cuota: Money;
}

export interface Invoice {
  id: string;
  serie: string;
  invoiceNumber: number;
  issuedAt: string;
  operationDate: string | null;
  emisorNombre: string;
  emisorNif: string;
  emisorDireccion: string;
  emisorCp: string;
  emisorPoblacion: string;
  emisorProvincia: string;
  emisorPais: string;
  clientName: string;
  clientNif: string;
  clientEmail: string;
  clientAddress: string;
  clientCp: string;
  clientCity: string;
  clientProvince: string;
  clientCountry: string;
  clientPhone: string;
  orderId: string | null;
  subtotal: string;
  taxTotal: string;
  total: string;
  taxBreakdown: TaxBreakdownItem[] | null;
  paymentMethod: string;
  notes: string;
  status: string;
  verifactuStatus: string;
  originalInvoiceId: string | null;
  rectificationReason: string;
  verifactuResponse: InvoiceVerifactuResponse;
  employeeId: string | null;
  createdAt: string;
}

export interface RectifyInvoiceInput {
  reason: string;
}

export interface Client {
  id: string;
  name: string;
  nif: string;
  address: string;
  cp: string;
  city: string;
  province: string;
  country: string;
  email: string;
  phone: string;
  createdAt: string;
}

export interface CreateClientInput {
  id?: string;
  name: string;
  nif?: string;
  address?: string;
  cp?: string;
  city?: string;
  province?: string;
  country?: string;
  email?: string;
  phone?: string;
  createdAt?: string;
}

export interface UpdateClientInput {
  id?: string;
  name?: string;
  nif?: string;
  address?: string;
  cp?: string;
  city?: string;
  province?: string;
  country?: string;
  email?: string;
  phone?: string;
  createdAt?: string;
}

export interface CreateReprintInput {
  documentId: string;
  documentType: string;
  reason?: string;
}

export interface DocumentReprint {
  id: string;
  documentId: string;
  documentType: string;
  employeeId: string | null;
  employeeName: string;
  reason: string;
  createdAt: string;
}

export interface DocumentAuditEntry {
  id: string;
  action: string;
  documentType: string;
  documentId: string;
  employeeId?: string | null;
  employeeName: string;
  terminal: string;
  printCount: number;
  amount?: string | null;
  details: string;
  createdAt: string;
}

export interface DocumentAuditLog {
  rows: DocumentAuditEntry[];
  page: number;
  limit: number;
}

export interface ErrorResponse {
  error: string;
}

/**
 * Authentication is required or invalid
 */
export type UnauthorizedResponse = ErrorResponse;

/**
 * The authenticated user lacks the required role or permission
 */
export type ForbiddenResponse = ErrorResponse;

/**
 * Session or authorization verification is temporarily unavailable
 */
export type ServiceUnavailableResponse = ErrorResponse;

/**
 * Request validation failed
 */
export type BadRequestResponse = ErrorResponse;

/**
 * Requested resource was not found
 */
export type NotFoundResponse = ErrorResponse;

/**
 * Current resource state conflicts with the operation
 */
export type ConflictResponse = ErrorResponse;

export type GetDocumentTemplatesParams = {
documentType?: string;
};

export type DeleteDocumentTemplate200 = {
  ok: boolean;
};

export type DeletePrinterConfig200 = {
  ok: boolean;
};

export type GetInvoice200ItemsItem = {
  productName: string;
  quantity: number;
  unitPrice: string;
};

export type GetInvoice200 = {
  invoice: Invoice;
  items: GetInvoice200ItemsItem[];
};

export type RectifyInvoice201 = {
  rectificativa: Invoice;
  originalId: string;
};

export type GetDocumentAuditLogParams = {
page?: number;
limit?: number;
};

