/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Api
 * Piccolo TPV API
 * OpenAPI spec version: 0.2.0
 */
export interface OpeningHoursDay {
  open: string;
  close: string;
  open2?: string;
  close2?: string;
}

/**
 * Weekday keys such as mon, tue, wed, thu, fri, sat, sun.
 */
export interface OpeningHours {[key: string]: OpeningHoursDay}

export interface BrandingThemeColors {
  primary?: string;
  background?: string;
  accent?: string;
  infoTextColor?: string;
  categoryCardBg?: string;
  categoryCardText?: string;
  callButtonBg?: string;
  callButtonText?: string;
  scheduleButtonBg?: string;
  scheduleButtonText?: string;
  heroTitleColor?: string;
  heroTaglineColor?: string;
  heroEstablishedColor?: string;
  tapDetailsColor?: string;
  [key: string]: unknown;
 }

export interface BrandingThemeFonts {
  heading?: string;
  body?: string;
  headingColor?: string;
  bodyColor?: string;
}

export type BrandingCardSettingsLayout = typeof BrandingCardSettingsLayout[keyof typeof BrandingCardSettingsLayout];


export const BrandingCardSettingsLayout = {
  grid: 'grid',
  list: 'list',
  compact: 'compact',
} as const;

export interface BrandingCardSettings {
  showImage?: boolean;
  showDescription?: boolean;
  showTags?: boolean;
  showAllergens?: boolean;
  showPrice?: boolean;
  showHalfPortion?: boolean;
  showQuantity?: boolean;
  layout?: BrandingCardSettingsLayout;
}

export interface QrShift {
  open: boolean;
  openTime: string;
  closeTime: string;
}

export interface QrDaySchedule {
  day: string;
  shift1: QrShift;
  shift2: QrShift;
}

export interface PublicBrandingResponse {
  restaurantName: string;
  tagline: string;
  heroImageUrl: string;
  heroVideoUrl: string;
  address: string;
  city: string;
  province: string;
  postalCode: string;
  country: string;
  phone: string;
  establishedYear?: number | null;
  openingHours?: OpeningHours | null;
  cardLayout: string;
  accentColor: string;
  logoUrl: string;
  themeColors?: BrandingThemeColors | null;
  themeFonts?: BrandingThemeFonts | null;
  cardSettings?: BrandingCardSettings | null;
  schedule?: QrDaySchedule[] | null;
  nombreComercial: string;
  foundedYear?: number | null;
}

export type QrNotConfiguredErrorCode = typeof QrNotConfiguredErrorCode[keyof typeof QrNotConfiguredErrorCode];


export const QrNotConfiguredErrorCode = {
  QR_NOT_CONFIGURED: 'QR_NOT_CONFIGURED',
} as const;

export interface QrNotConfiguredError {
  error: string;
  code: QrNotConfiguredErrorCode;
}

export interface AdminBranding {
  nombreComercial: string;
  tagline: string;
  heroImageUrl: string;
  heroVideoUrl: string;
  address: string;
  phone: string;
  foundedYear?: number | null;
  openingHours?: OpeningHours | null;
  cardLayout: string;
  accentColor: string;
  logoUrl: string;
}

export interface BrandingInput {
  nombreComercial?: string;
  tagline?: string;
  heroImageUrl?: string;
  heroVideoUrl?: string;
  address?: string;
  phone?: string;
  foundedYear?: number | null;
  openingHours?: OpeningHours | null;
  cardLayout?: string;
  accentColor?: string;
  logoUrl?: string;
}

export interface QrBranding {
  restaurantName: string;
  tagline: string;
  heroImageUrl: string;
  heroVideoUrl: string;
  address: string;
  city: string;
  province: string;
  postalCode: string;
  country: string;
  phone: string;
  establishedYear: string;
  logoUrl: string;
  themeColors?: BrandingThemeColors | null;
  themeFonts?: BrandingThemeFonts | null;
  cardSettings?: BrandingCardSettings | null;
  schedule?: QrDaySchedule[] | null;
}

export interface UpdateQrBrandingInput {
  restaurantName?: string;
  tagline?: string;
  heroImageUrl?: string;
  heroVideoUrl?: string;
  address?: string;
  city?: string;
  province?: string;
  postalCode?: string;
  country?: string;
  phone?: string;
  establishedYear?: string;
  logoUrl?: string;
  themeColors?: BrandingThemeColors | null;
  themeFonts?: BrandingThemeFonts | null;
  cardSettings?: BrandingCardSettings | null;
  schedule?: QrDaySchedule[] | null;
}

export interface QrBrandingOkResponse {
  ok: boolean;
}

export interface ErrorResponse {
  error: string;
}

/**
 * Authentication is required or invalid
 */
export type UnauthorizedResponse = ErrorResponse;

/**
 * The authenticated user lacks the required role or permission
 */
export type ForbiddenResponse = ErrorResponse;

/**
 * Session or authorization verification is temporarily unavailable
 */
export type ServiceUnavailableResponse = ErrorResponse;

