/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Api
 * Piccolo TPV API
 * OpenAPI spec version: 0.2.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AdminBranding,
  BrandingInput,
  ForbiddenResponse,
  PublicBrandingResponse,
  QrBranding,
  QrBrandingOkResponse,
  QrNotConfiguredError,
  ServiceUnavailableResponse,
  UnauthorizedResponse,
  UpdateQrBrandingInput
} from './api.schemas';

import { customFetch } from '../custom-fetch';
import type { ErrorType , BodyType } from '../custom-fetch';

type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const getGetPublicBrandingUrl = () => {




  return `/api/public/branding`
}

/**
 * Returns branding for the public carta. In production, responds with 503 when business configuration has not been seeded.
 * @summary Get public QR carta branding (no authentication required)
 */
export const getPublicBranding = async ( options?: RequestInit): Promise<PublicBrandingResponse> => {

  return customFetch<PublicBrandingResponse>(getGetPublicBrandingUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetPublicBrandingQueryKey = () => {
    return [
    `/api/public/branding`
    ] as const;
    }


export const getGetPublicBrandingQueryOptions = <TData = Awaited<ReturnType<typeof getPublicBranding>>, TError = ErrorType<QrNotConfiguredError>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getPublicBranding>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetPublicBrandingQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getPublicBranding>>> = ({ signal }) => getPublicBranding({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getPublicBranding>>, TError, TData> & { queryKey: QueryKey }
}

export type GetPublicBrandingQueryResult = NonNullable<Awaited<ReturnType<typeof getPublicBranding>>>
export type GetPublicBrandingQueryError = ErrorType<QrNotConfiguredError>


/**
 * @summary Get public QR carta branding (no authentication required)
 */

export function useGetPublicBranding<TData = Awaited<ReturnType<typeof getPublicBranding>>, TError = ErrorType<QrNotConfiguredError>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getPublicBranding>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetPublicBrandingQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}







export const getGetAdminBrandingUrl = () => {




  return `/api/admin/branding`
}

/**
 * @summary Get admin branding settings for the legacy carta editor
 */
export const getAdminBranding = async ( options?: RequestInit): Promise<AdminBranding> => {

  return customFetch<AdminBranding>(getGetAdminBrandingUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetAdminBrandingQueryKey = () => {
    return [
    `/api/admin/branding`
    ] as const;
    }


export const getGetAdminBrandingQueryOptions = <TData = Awaited<ReturnType<typeof getAdminBranding>>, TError = ErrorType<UnauthorizedResponse | ForbiddenResponse | ServiceUnavailableResponse>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getAdminBranding>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAdminBrandingQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAdminBranding>>> = ({ signal }) => getAdminBranding({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAdminBranding>>, TError, TData> & { queryKey: QueryKey }
}

export type GetAdminBrandingQueryResult = NonNullable<Awaited<ReturnType<typeof getAdminBranding>>>
export type GetAdminBrandingQueryError = ErrorType<UnauthorizedResponse | ForbiddenResponse | ServiceUnavailableResponse>


/**
 * @summary Get admin branding settings for the legacy carta editor
 */

export function useGetAdminBranding<TData = Awaited<ReturnType<typeof getAdminBranding>>, TError = ErrorType<UnauthorizedResponse | ForbiddenResponse | ServiceUnavailableResponse>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getAdminBranding>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetAdminBrandingQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}







export const getPatchAdminBrandingUrl = () => {




  return `/api/admin/branding`
}

/**
 * @summary Partially update admin branding settings
 */
export const patchAdminBranding = async (brandingInput: BrandingInput, options?: RequestInit): Promise<AdminBranding> => {

  return customFetch<AdminBranding>(getPatchAdminBrandingUrl(),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(brandingInput)
  }
);}





export const getPatchAdminBrandingMutationOptions = <TError = ErrorType<UnauthorizedResponse | ForbiddenResponse | ServiceUnavailableResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchAdminBranding>>, TError,{data: BodyType<BrandingInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof patchAdminBranding>>, TError,{data: BodyType<BrandingInput>}, TContext> => {

const mutationKey = ['patchAdminBranding'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchAdminBranding>>, {data: BodyType<BrandingInput>}> = (props) => {
          const {data} = props ?? {};

          return  patchAdminBranding(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PatchAdminBrandingMutationResult = NonNullable<Awaited<ReturnType<typeof patchAdminBranding>>>
    export type PatchAdminBrandingMutationBody = BodyType<BrandingInput>
    export type PatchAdminBrandingMutationError = ErrorType<UnauthorizedResponse | ForbiddenResponse | ServiceUnavailableResponse>

    /**
 * @summary Partially update admin branding settings
 */
export const usePatchAdminBranding = <TError = ErrorType<UnauthorizedResponse | ForbiddenResponse | ServiceUnavailableResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchAdminBranding>>, TError,{data: BodyType<BrandingInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof patchAdminBranding>>,
        TError,
        {data: BodyType<BrandingInput>},
        TContext
      > => {
      return useMutation(getPatchAdminBrandingMutationOptions(options));
    }

export const getGetAdminQrBrandingUrl = () => {




  return `/api/admin/qr-branding`
}

/**
 * @summary Get full QR branding settings for the admin editor
 */
export const getAdminQrBranding = async ( options?: RequestInit): Promise<QrBranding> => {

  return customFetch<QrBranding>(getGetAdminQrBrandingUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetAdminQrBrandingQueryKey = () => {
    return [
    `/api/admin/qr-branding`
    ] as const;
    }


export const getGetAdminQrBrandingQueryOptions = <TData = Awaited<ReturnType<typeof getAdminQrBranding>>, TError = ErrorType<UnauthorizedResponse | ForbiddenResponse | ServiceUnavailableResponse>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getAdminQrBranding>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAdminQrBrandingQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAdminQrBranding>>> = ({ signal }) => getAdminQrBranding({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAdminQrBranding>>, TError, TData> & { queryKey: QueryKey }
}

export type GetAdminQrBrandingQueryResult = NonNullable<Awaited<ReturnType<typeof getAdminQrBranding>>>
export type GetAdminQrBrandingQueryError = ErrorType<UnauthorizedResponse | ForbiddenResponse | ServiceUnavailableResponse>


/**
 * @summary Get full QR branding settings for the admin editor
 */

export function useGetAdminQrBranding<TData = Awaited<ReturnType<typeof getAdminQrBranding>>, TError = ErrorType<UnauthorizedResponse | ForbiddenResponse | ServiceUnavailableResponse>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getAdminQrBranding>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetAdminQrBrandingQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}







export const getPutAdminQrBrandingUrl = () => {




  return `/api/admin/qr-branding`
}

/**
 * @summary Replace QR branding settings
 */
export const putAdminQrBranding = async (updateQrBrandingInput: UpdateQrBrandingInput, options?: RequestInit): Promise<QrBrandingOkResponse> => {

  return customFetch<QrBrandingOkResponse>(getPutAdminQrBrandingUrl(),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updateQrBrandingInput)
  }
);}





export const getPutAdminQrBrandingMutationOptions = <TError = ErrorType<UnauthorizedResponse | ForbiddenResponse | ServiceUnavailableResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putAdminQrBranding>>, TError,{data: BodyType<UpdateQrBrandingInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof putAdminQrBranding>>, TError,{data: BodyType<UpdateQrBrandingInput>}, TContext> => {

const mutationKey = ['putAdminQrBranding'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putAdminQrBranding>>, {data: BodyType<UpdateQrBrandingInput>}> = (props) => {
          const {data} = props ?? {};

          return  putAdminQrBranding(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PutAdminQrBrandingMutationResult = NonNullable<Awaited<ReturnType<typeof putAdminQrBranding>>>
    export type PutAdminQrBrandingMutationBody = BodyType<UpdateQrBrandingInput>
    export type PutAdminQrBrandingMutationError = ErrorType<UnauthorizedResponse | ForbiddenResponse | ServiceUnavailableResponse>

    /**
 * @summary Replace QR branding settings
 */
export const usePutAdminQrBranding = <TError = ErrorType<UnauthorizedResponse | ForbiddenResponse | ServiceUnavailableResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putAdminQrBranding>>, TError,{data: BodyType<UpdateQrBrandingInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof putAdminQrBranding>>,
        TError,
        {data: BodyType<UpdateQrBrandingInput>},
        TContext
      > => {
      return useMutation(getPutAdminQrBrandingMutationOptions(options));
    }

