/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Api
 * Piccolo TPV API
 * OpenAPI spec version: 0.2.0
 */
export type ReservationStatus = typeof ReservationStatus[keyof typeof ReservationStatus];


export const ReservationStatus = {
  pendiente: 'pendiente',
  confirmada: 'confirmada',
  recordatorio_enviado: 'recordatorio_enviado',
  cliente_avisado: 'cliente_avisado',
  cliente_llegado: 'cliente_llegado',
  sentada: 'sentada',
  en_espera: 'en_espera',
  cancelada_cliente: 'cancelada_cliente',
  cancelada_restaurante: 'cancelada_restaurante',
  no_presentado: 'no_presentado',
  finalizada: 'finalizada',
} as const;

export interface Reservation {
  id: string;
  fecha: string;
  hora: string;
  nombre: string;
  telefono: string;
  email: string;
  personas: number;
  clientId: string | null;
  shiftId: string | null;
  zonaPreferida: string | null;
  mesaId: string | null;
  duracionMinutos: number;
  idioma: string;
  alergias: string;
  trona: boolean;
  accesibilidad: boolean;
  mascota: boolean;
  ocasion: string | null;
  canal: string;
  recordatorioEnviado: boolean;
  confirmacionRequerida: boolean;
  notes: string;
  notasInternas: string;
  status: ReservationStatus;
  createdBy: string | null;
  createdAt: string;
  updatedAt: string;
  isDemo: boolean;
}

export type ReservationListItem = Reservation & ({
  clientNombre: string | null;
  clientApellidos: string | null;
  clientEmail: string | null;
  clientTelefono: string | null;
  mesaNumero: string | null;
});

export interface CreateReservationInput {
  fecha: string;
  hora: string;
  /** @minLength 1 */
  nombre: string;
  telefono?: string;
  email?: string;
  personas?: number;
  clientId?: string | null;
  shiftId?: string | null;
  zonaPreferida?: string | null;
  mesaId?: string | null;
  duracionMinutos?: number;
  idioma?: string;
  alergias?: string;
  trona?: boolean;
  accesibilidad?: boolean;
  mascota?: boolean;
  ocasion?: string | null;
  canal?: string;
  confirmacionRequerida?: boolean;
  notes?: string;
  notasInternas?: string;
}

export interface TableSuggestion {
  id: string;
  tableNumber: string;
  capacity: number;
  status: string;
  zoneId: string;
  zoneName: string | null;
  score: number;
}

export interface SuggestTableResponse {
  /** @maxItems 5 */
  suggestions: TableSuggestion[];
  busyTableCount: number;
}

export interface ReservationStatusHistory {
  id: string;
  reservationId: string;
  statusFrom: string;
  statusTo: string;
  changedBy: string | null;
  changedAt: string;
  notes: string;
}

export type ReservationDetail = Reservation & ({
  clientNombre: string | null;
  mesaNumero: string | null;
  history: ReservationStatusHistory[];
});

export interface UpdateReservationInput {
  fecha?: string;
  hora?: string;
  nombre?: string;
  telefono?: string;
  email?: string;
  personas?: number;
  clientId?: string | null;
  shiftId?: string | null;
  zonaPreferida?: string | null;
  mesaId?: string | null;
  duracionMinutos?: number;
  idioma?: string;
  alergias?: string;
  trona?: boolean;
  accesibilidad?: boolean;
  mascota?: boolean;
  ocasion?: string | null;
  canal?: string;
  confirmacionRequerida?: boolean;
  recordatorioEnviado?: boolean;
  notes?: string;
  notasInternas?: string;
  /** Unknown values are ignored by the current handler. */
  status?: string;
  statusNotes?: string;
}

export interface ArriveReservationInput {
  openTable?: boolean;
}

export type ArriveReservationResponseTableOpened = {
  tableId: string;
  orderId: string;
} | null;

export type ArriveReservationResponsePrefill = {
  guestCount: number;
  clientName: string;
  notes: string;
  mesaId: string | null;
  alergias: string;
  trona: boolean;
};

export interface ArriveReservationResponse {
  reservation: Reservation;
  tableOpened: ArriveReservationResponseTableOpened;
  prefill: ArriveReservationResponsePrefill;
}

export interface ErrorResponse {
  error: string;
}

/**
 * Authentication is required or invalid
 */
export type UnauthorizedResponse = ErrorResponse;

/**
 * Session or authorization verification is temporarily unavailable
 */
export type ServiceUnavailableResponse = ErrorResponse;

/**
 * Request validation failed
 */
export type BadRequestResponse = ErrorResponse;

/**
 * Current resource state conflicts with the operation
 */
export type ConflictResponse = ErrorResponse;

/**
 * Requested resource was not found
 */
export type NotFoundResponse = ErrorResponse;

/**
 * The authenticated user lacks the required role or permission
 */
export type ForbiddenResponse = ErrorResponse;

export type GetReservationsParams = {
date?: string;
from?: string;
to?: string;
/**
 * Unknown values are ignored by the current handler.
 */
status?: string;
clientId?: string;
};

export type SuggestReservationTableParams = {
fecha: string;
hora: string;
duracion?: number;
personas?: number;
zona?: string;
};

