/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Api
 * Piccolo TPV API
 * OpenAPI spec version: 0.2.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ArriveReservationInput,
  ArriveReservationResponse,
  BadRequestResponse,
  ConflictResponse,
  CreateReservationInput,
  ForbiddenResponse,
  GetReservationsParams,
  NotFoundResponse,
  Reservation,
  ReservationDetail,
  ReservationListItem,
  ReservationStatusHistory,
  ServiceUnavailableResponse,
  SuggestReservationTableParams,
  SuggestTableResponse,
  UnauthorizedResponse,
  UpdateReservationInput
} from './api.schemas';

import { customFetch } from '../custom-fetch';
import type { ErrorType , BodyType } from '../custom-fetch';

type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const getGetReservationsUrl = (params?: GetReservationsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/reservations?${stringifiedParams}` : `/api/reservations`
}

/**
 * @summary List reservations ordered by date and time
 */
export const getReservations = async (params?: GetReservationsParams, options?: RequestInit): Promise<ReservationListItem[]> => {

  return customFetch<ReservationListItem[]>(getGetReservationsUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetReservationsQueryKey = (params?: GetReservationsParams,) => {
    return [
    `/api/reservations`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetReservationsQueryOptions = <TData = Awaited<ReturnType<typeof getReservations>>, TError = ErrorType<UnauthorizedResponse | ServiceUnavailableResponse>>(params?: GetReservationsParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getReservations>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetReservationsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getReservations>>> = ({ signal }) => getReservations(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getReservations>>, TError, TData> & { queryKey: QueryKey }
}

export type GetReservationsQueryResult = NonNullable<Awaited<ReturnType<typeof getReservations>>>
export type GetReservationsQueryError = ErrorType<UnauthorizedResponse | ServiceUnavailableResponse>


/**
 * @summary List reservations ordered by date and time
 */

export function useGetReservations<TData = Awaited<ReturnType<typeof getReservations>>, TError = ErrorType<UnauthorizedResponse | ServiceUnavailableResponse>>(
 params?: GetReservationsParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getReservations>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetReservationsQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}







export const getCreateReservationUrl = () => {




  return `/api/reservations`
}

/**
 * @summary Create a pending reservation
 */
export const createReservation = async (createReservationInput: CreateReservationInput, options?: RequestInit): Promise<Reservation> => {

  return customFetch<Reservation>(getCreateReservationUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createReservationInput)
  }
);}





export const getCreateReservationMutationOptions = <TError = ErrorType<BadRequestResponse | UnauthorizedResponse | ConflictResponse | ServiceUnavailableResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createReservation>>, TError,{data: BodyType<CreateReservationInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof createReservation>>, TError,{data: BodyType<CreateReservationInput>}, TContext> => {

const mutationKey = ['createReservation'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createReservation>>, {data: BodyType<CreateReservationInput>}> = (props) => {
          const {data} = props ?? {};

          return  createReservation(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateReservationMutationResult = NonNullable<Awaited<ReturnType<typeof createReservation>>>
    export type CreateReservationMutationBody = BodyType<CreateReservationInput>
    export type CreateReservationMutationError = ErrorType<BadRequestResponse | UnauthorizedResponse | ConflictResponse | ServiceUnavailableResponse>

    /**
 * @summary Create a pending reservation
 */
export const useCreateReservation = <TError = ErrorType<BadRequestResponse | UnauthorizedResponse | ConflictResponse | ServiceUnavailableResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createReservation>>, TError,{data: BodyType<CreateReservationInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof createReservation>>,
        TError,
        {data: BodyType<CreateReservationInput>},
        TContext
      > => {
      return useMutation(getCreateReservationMutationOptions(options));
    }

export const getSuggestReservationTableUrl = (params: SuggestReservationTableParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/reservations/suggest-table?${stringifiedParams}` : `/api/reservations/suggest-table`
}

/**
 * @summary Suggest up to five available tables for a reservation time window
 */
export const suggestReservationTable = async (params: SuggestReservationTableParams, options?: RequestInit): Promise<SuggestTableResponse> => {

  return customFetch<SuggestTableResponse>(getSuggestReservationTableUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getSuggestReservationTableQueryKey = (params?: SuggestReservationTableParams,) => {
    return [
    `/api/reservations/suggest-table`, ...(params ? [params] : [])
    ] as const;
    }


export const getSuggestReservationTableQueryOptions = <TData = Awaited<ReturnType<typeof suggestReservationTable>>, TError = ErrorType<BadRequestResponse | UnauthorizedResponse | ServiceUnavailableResponse>>(params: SuggestReservationTableParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof suggestReservationTable>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getSuggestReservationTableQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof suggestReservationTable>>> = ({ signal }) => suggestReservationTable(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof suggestReservationTable>>, TError, TData> & { queryKey: QueryKey }
}

export type SuggestReservationTableQueryResult = NonNullable<Awaited<ReturnType<typeof suggestReservationTable>>>
export type SuggestReservationTableQueryError = ErrorType<BadRequestResponse | UnauthorizedResponse | ServiceUnavailableResponse>


/**
 * @summary Suggest up to five available tables for a reservation time window
 */

export function useSuggestReservationTable<TData = Awaited<ReturnType<typeof suggestReservationTable>>, TError = ErrorType<BadRequestResponse | UnauthorizedResponse | ServiceUnavailableResponse>>(
 params: SuggestReservationTableParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof suggestReservationTable>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getSuggestReservationTableQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}







export const getGetReservationUrl = (id: string,) => {




  return `/api/reservations/${id}`
}

/**
 * @summary Get a reservation with its status history
 */
export const getReservation = async (id: string, options?: RequestInit): Promise<ReservationDetail> => {

  return customFetch<ReservationDetail>(getGetReservationUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetReservationQueryKey = (id: string,) => {
    return [
    `/api/reservations/${id}`
    ] as const;
    }


export const getGetReservationQueryOptions = <TData = Awaited<ReturnType<typeof getReservation>>, TError = ErrorType<UnauthorizedResponse | NotFoundResponse | ServiceUnavailableResponse>>(id: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getReservation>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetReservationQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getReservation>>> = ({ signal }) => getReservation(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getReservation>>, TError, TData> & { queryKey: QueryKey }
}

export type GetReservationQueryResult = NonNullable<Awaited<ReturnType<typeof getReservation>>>
export type GetReservationQueryError = ErrorType<UnauthorizedResponse | NotFoundResponse | ServiceUnavailableResponse>


/**
 * @summary Get a reservation with its status history
 */

export function useGetReservation<TData = Awaited<ReturnType<typeof getReservation>>, TError = ErrorType<UnauthorizedResponse | NotFoundResponse | ServiceUnavailableResponse>>(
 id: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getReservation>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetReservationQueryOptions(id,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}







export const getPatchReservationUrl = (id: string,) => {




  return `/api/reservations/${id}`
}

/**
 * @summary Partially update a reservation and optionally its status
 */
export const patchReservation = async (id: string,
    updateReservationInput: UpdateReservationInput, options?: RequestInit): Promise<Reservation> => {

  return customFetch<Reservation>(getPatchReservationUrl(id),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updateReservationInput)
  }
);}





export const getPatchReservationMutationOptions = <TError = ErrorType<UnauthorizedResponse | NotFoundResponse | ConflictResponse | ServiceUnavailableResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchReservation>>, TError,{id: string;data: BodyType<UpdateReservationInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof patchReservation>>, TError,{id: string;data: BodyType<UpdateReservationInput>}, TContext> => {

const mutationKey = ['patchReservation'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchReservation>>, {id: string;data: BodyType<UpdateReservationInput>}> = (props) => {
          const {id,data} = props ?? {};

          return  patchReservation(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PatchReservationMutationResult = NonNullable<Awaited<ReturnType<typeof patchReservation>>>
    export type PatchReservationMutationBody = BodyType<UpdateReservationInput>
    export type PatchReservationMutationError = ErrorType<UnauthorizedResponse | NotFoundResponse | ConflictResponse | ServiceUnavailableResponse>

    /**
 * @summary Partially update a reservation and optionally its status
 */
export const usePatchReservation = <TError = ErrorType<UnauthorizedResponse | NotFoundResponse | ConflictResponse | ServiceUnavailableResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchReservation>>, TError,{id: string;data: BodyType<UpdateReservationInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof patchReservation>>,
        TError,
        {id: string;data: BodyType<UpdateReservationInput>},
        TContext
      > => {
      return useMutation(getPatchReservationMutationOptions(options));
    }

export const getDeleteReservationUrl = (id: string,) => {




  return `/api/reservations/${id}`
}

/**
 * @summary Delete a reservation
 */
export const deleteReservation = async (id: string, options?: RequestInit): Promise<void> => {

  return customFetch<void>(getDeleteReservationUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}





export const getDeleteReservationMutationOptions = <TError = ErrorType<UnauthorizedResponse | ForbiddenResponse | NotFoundResponse | ServiceUnavailableResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteReservation>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteReservation>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteReservation'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteReservation>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteReservation(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteReservationMutationResult = NonNullable<Awaited<ReturnType<typeof deleteReservation>>>

    export type DeleteReservationMutationError = ErrorType<UnauthorizedResponse | ForbiddenResponse | NotFoundResponse | ServiceUnavailableResponse>

    /**
 * @summary Delete a reservation
 */
export const useDeleteReservation = <TError = ErrorType<UnauthorizedResponse | ForbiddenResponse | NotFoundResponse | ServiceUnavailableResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteReservation>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof deleteReservation>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getDeleteReservationMutationOptions(options));
    }

export const getArriveReservationUrl = (id: string,) => {




  return `/api/reservations/${id}/arrive`
}

/**
 * @summary Mark a reservation as arrived and optionally open its assigned table
 */
export const arriveReservation = async (id: string,
    arriveReservationInput?: ArriveReservationInput, options?: RequestInit): Promise<ArriveReservationResponse> => {

  return customFetch<ArriveReservationResponse>(getArriveReservationUrl(id),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(arriveReservationInput)
  }
);}





export const getArriveReservationMutationOptions = <TError = ErrorType<UnauthorizedResponse | NotFoundResponse | ConflictResponse | ServiceUnavailableResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof arriveReservation>>, TError,{id: string;data?: BodyType<ArriveReservationInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof arriveReservation>>, TError,{id: string;data?: BodyType<ArriveReservationInput>}, TContext> => {

const mutationKey = ['arriveReservation'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof arriveReservation>>, {id: string;data?: BodyType<ArriveReservationInput>}> = (props) => {
          const {id,data} = props ?? {};

          return  arriveReservation(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ArriveReservationMutationResult = NonNullable<Awaited<ReturnType<typeof arriveReservation>>>
    export type ArriveReservationMutationBody = BodyType<ArriveReservationInput> | undefined
    export type ArriveReservationMutationError = ErrorType<UnauthorizedResponse | NotFoundResponse | ConflictResponse | ServiceUnavailableResponse>

    /**
 * @summary Mark a reservation as arrived and optionally open its assigned table
 */
export const useArriveReservation = <TError = ErrorType<UnauthorizedResponse | NotFoundResponse | ConflictResponse | ServiceUnavailableResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof arriveReservation>>, TError,{id: string;data?: BodyType<ArriveReservationInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof arriveReservation>>,
        TError,
        {id: string;data?: BodyType<ArriveReservationInput>},
        TContext
      > => {
      return useMutation(getArriveReservationMutationOptions(options));
    }

export const getGetReservationHistoryUrl = (id: string,) => {




  return `/api/reservations/${id}/history`
}

/**
 * @summary Get reservation status transitions
 */
export const getReservationHistory = async (id: string, options?: RequestInit): Promise<ReservationStatusHistory[]> => {

  return customFetch<ReservationStatusHistory[]>(getGetReservationHistoryUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetReservationHistoryQueryKey = (id: string,) => {
    return [
    `/api/reservations/${id}/history`
    ] as const;
    }


export const getGetReservationHistoryQueryOptions = <TData = Awaited<ReturnType<typeof getReservationHistory>>, TError = ErrorType<UnauthorizedResponse | ServiceUnavailableResponse>>(id: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getReservationHistory>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetReservationHistoryQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getReservationHistory>>> = ({ signal }) => getReservationHistory(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getReservationHistory>>, TError, TData> & { queryKey: QueryKey }
}

export type GetReservationHistoryQueryResult = NonNullable<Awaited<ReturnType<typeof getReservationHistory>>>
export type GetReservationHistoryQueryError = ErrorType<UnauthorizedResponse | ServiceUnavailableResponse>


/**
 * @summary Get reservation status transitions
 */

export function useGetReservationHistory<TData = Awaited<ReturnType<typeof getReservationHistory>>, TError = ErrorType<UnauthorizedResponse | ServiceUnavailableResponse>>(
 id: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getReservationHistory>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetReservationHistoryQueryOptions(id,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}







