/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Api
 * Piccolo TPV API
 * OpenAPI spec version: 0.2.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  BadRequestResponse,
  ConflictResponse,
  CreateCrmGiftCardInput,
  CrmGiftCard,
  CrmGiftCardDetail,
  CrmWallet,
  CrmWalletDetail,
  ForbiddenResponse,
  GetCrmGiftCardsParams,
  LookupCrmGiftCardParams,
  NotFoundResponse,
  PayWithCrmGiftCardInput,
  PayWithCrmGiftCardResult,
  RechargeCrmGiftCardInput,
  ServiceUnavailableResponse,
  UnauthorizedResponse,
  WalletAddInput,
  WalletAdjustInput,
  WalletPayInput,
  WalletPayResult
} from './api.schemas';

import { customFetch } from '../custom-fetch';
import type { ErrorType , BodyType } from '../custom-fetch';

type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const getGetCrmGiftCardsUrl = (params?: GetCrmGiftCardsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/crm/gift-cards?${stringifiedParams}` : `/api/crm/gift-cards`
}

/**
 * @summary List gift cards
 */
export const getCrmGiftCards = async (params?: GetCrmGiftCardsParams, options?: RequestInit): Promise<CrmGiftCard[]> => {

  return customFetch<CrmGiftCard[]>(getGetCrmGiftCardsUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetCrmGiftCardsQueryKey = (params?: GetCrmGiftCardsParams,) => {
    return [
    `/api/crm/gift-cards`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetCrmGiftCardsQueryOptions = <TData = Awaited<ReturnType<typeof getCrmGiftCards>>, TError = ErrorType<UnauthorizedResponse | ForbiddenResponse | ServiceUnavailableResponse>>(params?: GetCrmGiftCardsParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getCrmGiftCards>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetCrmGiftCardsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getCrmGiftCards>>> = ({ signal }) => getCrmGiftCards(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getCrmGiftCards>>, TError, TData> & { queryKey: QueryKey }
}

export type GetCrmGiftCardsQueryResult = NonNullable<Awaited<ReturnType<typeof getCrmGiftCards>>>
export type GetCrmGiftCardsQueryError = ErrorType<UnauthorizedResponse | ForbiddenResponse | ServiceUnavailableResponse>


/**
 * @summary List gift cards
 */

export function useGetCrmGiftCards<TData = Awaited<ReturnType<typeof getCrmGiftCards>>, TError = ErrorType<UnauthorizedResponse | ForbiddenResponse | ServiceUnavailableResponse>>(
 params?: GetCrmGiftCardsParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getCrmGiftCards>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetCrmGiftCardsQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}







export const getCreateCrmGiftCardUrl = () => {




  return `/api/crm/gift-cards`
}

/**
 * @summary Create a new gift card
 */
export const createCrmGiftCard = async (createCrmGiftCardInput: CreateCrmGiftCardInput, options?: RequestInit): Promise<CrmGiftCard> => {

  return customFetch<CrmGiftCard>(getCreateCrmGiftCardUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createCrmGiftCardInput)
  }
);}





export const getCreateCrmGiftCardMutationOptions = <TError = ErrorType<BadRequestResponse | UnauthorizedResponse | ForbiddenResponse | ServiceUnavailableResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createCrmGiftCard>>, TError,{data: BodyType<CreateCrmGiftCardInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof createCrmGiftCard>>, TError,{data: BodyType<CreateCrmGiftCardInput>}, TContext> => {

const mutationKey = ['createCrmGiftCard'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createCrmGiftCard>>, {data: BodyType<CreateCrmGiftCardInput>}> = (props) => {
          const {data} = props ?? {};

          return  createCrmGiftCard(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateCrmGiftCardMutationResult = NonNullable<Awaited<ReturnType<typeof createCrmGiftCard>>>
    export type CreateCrmGiftCardMutationBody = BodyType<CreateCrmGiftCardInput>
    export type CreateCrmGiftCardMutationError = ErrorType<BadRequestResponse | UnauthorizedResponse | ForbiddenResponse | ServiceUnavailableResponse>

    /**
 * @summary Create a new gift card
 */
export const useCreateCrmGiftCard = <TError = ErrorType<BadRequestResponse | UnauthorizedResponse | ForbiddenResponse | ServiceUnavailableResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createCrmGiftCard>>, TError,{data: BodyType<CreateCrmGiftCardInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof createCrmGiftCard>>,
        TError,
        {data: BodyType<CreateCrmGiftCardInput>},
        TContext
      > => {
      return useMutation(getCreateCrmGiftCardMutationOptions(options));
    }

export const getLookupCrmGiftCardUrl = (params: LookupCrmGiftCardParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/crm/gift-cards/lookup?${stringifiedParams}` : `/api/crm/gift-cards/lookup`
}

/**
 * @summary Look up a gift card by code (POS balance check)
 */
export const lookupCrmGiftCard = async (params: LookupCrmGiftCardParams, options?: RequestInit): Promise<CrmGiftCard> => {

  return customFetch<CrmGiftCard>(getLookupCrmGiftCardUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getLookupCrmGiftCardQueryKey = (params?: LookupCrmGiftCardParams,) => {
    return [
    `/api/crm/gift-cards/lookup`, ...(params ? [params] : [])
    ] as const;
    }


export const getLookupCrmGiftCardQueryOptions = <TData = Awaited<ReturnType<typeof lookupCrmGiftCard>>, TError = ErrorType<BadRequestResponse | UnauthorizedResponse | ForbiddenResponse | NotFoundResponse | ServiceUnavailableResponse>>(params: LookupCrmGiftCardParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof lookupCrmGiftCard>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getLookupCrmGiftCardQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof lookupCrmGiftCard>>> = ({ signal }) => lookupCrmGiftCard(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof lookupCrmGiftCard>>, TError, TData> & { queryKey: QueryKey }
}

export type LookupCrmGiftCardQueryResult = NonNullable<Awaited<ReturnType<typeof lookupCrmGiftCard>>>
export type LookupCrmGiftCardQueryError = ErrorType<BadRequestResponse | UnauthorizedResponse | ForbiddenResponse | NotFoundResponse | ServiceUnavailableResponse>


/**
 * @summary Look up a gift card by code (POS balance check)
 */

export function useLookupCrmGiftCard<TData = Awaited<ReturnType<typeof lookupCrmGiftCard>>, TError = ErrorType<BadRequestResponse | UnauthorizedResponse | ForbiddenResponse | NotFoundResponse | ServiceUnavailableResponse>>(
 params: LookupCrmGiftCardParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof lookupCrmGiftCard>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getLookupCrmGiftCardQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}







export const getPayWithCrmGiftCardUrl = () => {




  return `/api/crm/gift-cards/pay`
}

/**
 * @summary Pay with a gift card at POS
 */
export const payWithCrmGiftCard = async (payWithCrmGiftCardInput: PayWithCrmGiftCardInput, options?: RequestInit): Promise<PayWithCrmGiftCardResult> => {

  return customFetch<PayWithCrmGiftCardResult>(getPayWithCrmGiftCardUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(payWithCrmGiftCardInput)
  }
);}





export const getPayWithCrmGiftCardMutationOptions = <TError = ErrorType<BadRequestResponse | UnauthorizedResponse | ForbiddenResponse | NotFoundResponse | ConflictResponse | ServiceUnavailableResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof payWithCrmGiftCard>>, TError,{data: BodyType<PayWithCrmGiftCardInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof payWithCrmGiftCard>>, TError,{data: BodyType<PayWithCrmGiftCardInput>}, TContext> => {

const mutationKey = ['payWithCrmGiftCard'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof payWithCrmGiftCard>>, {data: BodyType<PayWithCrmGiftCardInput>}> = (props) => {
          const {data} = props ?? {};

          return  payWithCrmGiftCard(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PayWithCrmGiftCardMutationResult = NonNullable<Awaited<ReturnType<typeof payWithCrmGiftCard>>>
    export type PayWithCrmGiftCardMutationBody = BodyType<PayWithCrmGiftCardInput>
    export type PayWithCrmGiftCardMutationError = ErrorType<BadRequestResponse | UnauthorizedResponse | ForbiddenResponse | NotFoundResponse | ConflictResponse | ServiceUnavailableResponse>

    /**
 * @summary Pay with a gift card at POS
 */
export const usePayWithCrmGiftCard = <TError = ErrorType<BadRequestResponse | UnauthorizedResponse | ForbiddenResponse | NotFoundResponse | ConflictResponse | ServiceUnavailableResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof payWithCrmGiftCard>>, TError,{data: BodyType<PayWithCrmGiftCardInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof payWithCrmGiftCard>>,
        TError,
        {data: BodyType<PayWithCrmGiftCardInput>},
        TContext
      > => {
      return useMutation(getPayWithCrmGiftCardMutationOptions(options));
    }

export const getGetCrmGiftCardUrl = (id: string,) => {




  return `/api/crm/gift-cards/${id}`
}

/**
 * @summary Get gift card detail with transaction history
 */
export const getCrmGiftCard = async (id: string, options?: RequestInit): Promise<CrmGiftCardDetail> => {

  return customFetch<CrmGiftCardDetail>(getGetCrmGiftCardUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetCrmGiftCardQueryKey = (id: string,) => {
    return [
    `/api/crm/gift-cards/${id}`
    ] as const;
    }


export const getGetCrmGiftCardQueryOptions = <TData = Awaited<ReturnType<typeof getCrmGiftCard>>, TError = ErrorType<UnauthorizedResponse | ForbiddenResponse | NotFoundResponse | ServiceUnavailableResponse>>(id: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getCrmGiftCard>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetCrmGiftCardQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getCrmGiftCard>>> = ({ signal }) => getCrmGiftCard(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getCrmGiftCard>>, TError, TData> & { queryKey: QueryKey }
}

export type GetCrmGiftCardQueryResult = NonNullable<Awaited<ReturnType<typeof getCrmGiftCard>>>
export type GetCrmGiftCardQueryError = ErrorType<UnauthorizedResponse | ForbiddenResponse | NotFoundResponse | ServiceUnavailableResponse>


/**
 * @summary Get gift card detail with transaction history
 */

export function useGetCrmGiftCard<TData = Awaited<ReturnType<typeof getCrmGiftCard>>, TError = ErrorType<UnauthorizedResponse | ForbiddenResponse | NotFoundResponse | ServiceUnavailableResponse>>(
 id: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getCrmGiftCard>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetCrmGiftCardQueryOptions(id,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}







export const getRechargeCrmGiftCardUrl = (id: string,) => {




  return `/api/crm/gift-cards/${id}/recharge`
}

/**
 * @summary Recharge a gift card balance
 */
export const rechargeCrmGiftCard = async (id: string,
    rechargeCrmGiftCardInput: RechargeCrmGiftCardInput, options?: RequestInit): Promise<CrmGiftCard> => {

  return customFetch<CrmGiftCard>(getRechargeCrmGiftCardUrl(id),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(rechargeCrmGiftCardInput)
  }
);}





export const getRechargeCrmGiftCardMutationOptions = <TError = ErrorType<BadRequestResponse | UnauthorizedResponse | ForbiddenResponse | NotFoundResponse | ConflictResponse | ServiceUnavailableResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof rechargeCrmGiftCard>>, TError,{id: string;data: BodyType<RechargeCrmGiftCardInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof rechargeCrmGiftCard>>, TError,{id: string;data: BodyType<RechargeCrmGiftCardInput>}, TContext> => {

const mutationKey = ['rechargeCrmGiftCard'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof rechargeCrmGiftCard>>, {id: string;data: BodyType<RechargeCrmGiftCardInput>}> = (props) => {
          const {id,data} = props ?? {};

          return  rechargeCrmGiftCard(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type RechargeCrmGiftCardMutationResult = NonNullable<Awaited<ReturnType<typeof rechargeCrmGiftCard>>>
    export type RechargeCrmGiftCardMutationBody = BodyType<RechargeCrmGiftCardInput>
    export type RechargeCrmGiftCardMutationError = ErrorType<BadRequestResponse | UnauthorizedResponse | ForbiddenResponse | NotFoundResponse | ConflictResponse | ServiceUnavailableResponse>

    /**
 * @summary Recharge a gift card balance
 */
export const useRechargeCrmGiftCard = <TError = ErrorType<BadRequestResponse | UnauthorizedResponse | ForbiddenResponse | NotFoundResponse | ConflictResponse | ServiceUnavailableResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof rechargeCrmGiftCard>>, TError,{id: string;data: BodyType<RechargeCrmGiftCardInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof rechargeCrmGiftCard>>,
        TError,
        {id: string;data: BodyType<RechargeCrmGiftCardInput>},
        TContext
      > => {
      return useMutation(getRechargeCrmGiftCardMutationOptions(options));
    }

export const getBlockCrmGiftCardUrl = (id: string,) => {




  return `/api/crm/gift-cards/${id}/block`
}

/**
 * @summary Toggle block/unblock on a gift card
 */
export const blockCrmGiftCard = async (id: string, options?: RequestInit): Promise<CrmGiftCard> => {

  return customFetch<CrmGiftCard>(getBlockCrmGiftCardUrl(id),
  {
    ...options,
    method: 'POST'


  }
);}





export const getBlockCrmGiftCardMutationOptions = <TError = ErrorType<UnauthorizedResponse | ForbiddenResponse | NotFoundResponse | ServiceUnavailableResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof blockCrmGiftCard>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof blockCrmGiftCard>>, TError,{id: string}, TContext> => {

const mutationKey = ['blockCrmGiftCard'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof blockCrmGiftCard>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  blockCrmGiftCard(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type BlockCrmGiftCardMutationResult = NonNullable<Awaited<ReturnType<typeof blockCrmGiftCard>>>

    export type BlockCrmGiftCardMutationError = ErrorType<UnauthorizedResponse | ForbiddenResponse | NotFoundResponse | ServiceUnavailableResponse>

    /**
 * @summary Toggle block/unblock on a gift card
 */
export const useBlockCrmGiftCard = <TError = ErrorType<UnauthorizedResponse | ForbiddenResponse | NotFoundResponse | ServiceUnavailableResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof blockCrmGiftCard>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof blockCrmGiftCard>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getBlockCrmGiftCardMutationOptions(options));
    }

export const getGetCrmClientWalletUrl = (id: string,) => {




  return `/api/crm/clients/${id}/wallet`
}

/**
 * @summary Get client wallet with recent transactions
 */
export const getCrmClientWallet = async (id: string, options?: RequestInit): Promise<CrmWalletDetail> => {

  return customFetch<CrmWalletDetail>(getGetCrmClientWalletUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetCrmClientWalletQueryKey = (id: string,) => {
    return [
    `/api/crm/clients/${id}/wallet`
    ] as const;
    }


export const getGetCrmClientWalletQueryOptions = <TData = Awaited<ReturnType<typeof getCrmClientWallet>>, TError = ErrorType<UnauthorizedResponse | ForbiddenResponse | ServiceUnavailableResponse>>(id: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getCrmClientWallet>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetCrmClientWalletQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getCrmClientWallet>>> = ({ signal }) => getCrmClientWallet(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getCrmClientWallet>>, TError, TData> & { queryKey: QueryKey }
}

export type GetCrmClientWalletQueryResult = NonNullable<Awaited<ReturnType<typeof getCrmClientWallet>>>
export type GetCrmClientWalletQueryError = ErrorType<UnauthorizedResponse | ForbiddenResponse | ServiceUnavailableResponse>


/**
 * @summary Get client wallet with recent transactions
 */

export function useGetCrmClientWallet<TData = Awaited<ReturnType<typeof getCrmClientWallet>>, TError = ErrorType<UnauthorizedResponse | ForbiddenResponse | ServiceUnavailableResponse>>(
 id: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getCrmClientWallet>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetCrmClientWalletQueryOptions(id,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}







export const getAddCrmWalletBalanceUrl = (id: string,) => {




  return `/api/crm/clients/${id}/wallet/add`
}

/**
 * @summary Add balance to a client wallet
 */
export const addCrmWalletBalance = async (id: string,
    walletAddInput: WalletAddInput, options?: RequestInit): Promise<CrmWallet> => {

  return customFetch<CrmWallet>(getAddCrmWalletBalanceUrl(id),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(walletAddInput)
  }
);}





export const getAddCrmWalletBalanceMutationOptions = <TError = ErrorType<BadRequestResponse | UnauthorizedResponse | ForbiddenResponse | NotFoundResponse | ServiceUnavailableResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof addCrmWalletBalance>>, TError,{id: string;data: BodyType<WalletAddInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof addCrmWalletBalance>>, TError,{id: string;data: BodyType<WalletAddInput>}, TContext> => {

const mutationKey = ['addCrmWalletBalance'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof addCrmWalletBalance>>, {id: string;data: BodyType<WalletAddInput>}> = (props) => {
          const {id,data} = props ?? {};

          return  addCrmWalletBalance(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AddCrmWalletBalanceMutationResult = NonNullable<Awaited<ReturnType<typeof addCrmWalletBalance>>>
    export type AddCrmWalletBalanceMutationBody = BodyType<WalletAddInput>
    export type AddCrmWalletBalanceMutationError = ErrorType<BadRequestResponse | UnauthorizedResponse | ForbiddenResponse | NotFoundResponse | ServiceUnavailableResponse>

    /**
 * @summary Add balance to a client wallet
 */
export const useAddCrmWalletBalance = <TError = ErrorType<BadRequestResponse | UnauthorizedResponse | ForbiddenResponse | NotFoundResponse | ServiceUnavailableResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof addCrmWalletBalance>>, TError,{id: string;data: BodyType<WalletAddInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof addCrmWalletBalance>>,
        TError,
        {id: string;data: BodyType<WalletAddInput>},
        TContext
      > => {
      return useMutation(getAddCrmWalletBalanceMutationOptions(options));
    }

export const getPayWithCrmWalletUrl = (id: string,) => {




  return `/api/crm/clients/${id}/wallet/pay`
}

/**
 * @summary Pay using client wallet balance
 */
export const payWithCrmWallet = async (id: string,
    walletPayInput: WalletPayInput, options?: RequestInit): Promise<WalletPayResult> => {

  return customFetch<WalletPayResult>(getPayWithCrmWalletUrl(id),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(walletPayInput)
  }
);}





export const getPayWithCrmWalletMutationOptions = <TError = ErrorType<BadRequestResponse | UnauthorizedResponse | ForbiddenResponse | ConflictResponse | ServiceUnavailableResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof payWithCrmWallet>>, TError,{id: string;data: BodyType<WalletPayInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof payWithCrmWallet>>, TError,{id: string;data: BodyType<WalletPayInput>}, TContext> => {

const mutationKey = ['payWithCrmWallet'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof payWithCrmWallet>>, {id: string;data: BodyType<WalletPayInput>}> = (props) => {
          const {id,data} = props ?? {};

          return  payWithCrmWallet(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PayWithCrmWalletMutationResult = NonNullable<Awaited<ReturnType<typeof payWithCrmWallet>>>
    export type PayWithCrmWalletMutationBody = BodyType<WalletPayInput>
    export type PayWithCrmWalletMutationError = ErrorType<BadRequestResponse | UnauthorizedResponse | ForbiddenResponse | ConflictResponse | ServiceUnavailableResponse>

    /**
 * @summary Pay using client wallet balance
 */
export const usePayWithCrmWallet = <TError = ErrorType<BadRequestResponse | UnauthorizedResponse | ForbiddenResponse | ConflictResponse | ServiceUnavailableResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof payWithCrmWallet>>, TError,{id: string;data: BodyType<WalletPayInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof payWithCrmWallet>>,
        TError,
        {id: string;data: BodyType<WalletPayInput>},
        TContext
      > => {
      return useMutation(getPayWithCrmWalletMutationOptions(options));
    }

export const getAdjustCrmWalletUrl = (id: string,) => {




  return `/api/crm/clients/${id}/wallet/adjust`
}

/**
 * @summary Manually adjust client wallet balance (admin)
 */
export const adjustCrmWallet = async (id: string,
    walletAdjustInput: WalletAdjustInput, options?: RequestInit): Promise<CrmWallet> => {

  return customFetch<CrmWallet>(getAdjustCrmWalletUrl(id),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(walletAdjustInput)
  }
);}





export const getAdjustCrmWalletMutationOptions = <TError = ErrorType<BadRequestResponse | UnauthorizedResponse | ForbiddenResponse | ServiceUnavailableResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adjustCrmWallet>>, TError,{id: string;data: BodyType<WalletAdjustInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof adjustCrmWallet>>, TError,{id: string;data: BodyType<WalletAdjustInput>}, TContext> => {

const mutationKey = ['adjustCrmWallet'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof adjustCrmWallet>>, {id: string;data: BodyType<WalletAdjustInput>}> = (props) => {
          const {id,data} = props ?? {};

          return  adjustCrmWallet(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AdjustCrmWalletMutationResult = NonNullable<Awaited<ReturnType<typeof adjustCrmWallet>>>
    export type AdjustCrmWalletMutationBody = BodyType<WalletAdjustInput>
    export type AdjustCrmWalletMutationError = ErrorType<BadRequestResponse | UnauthorizedResponse | ForbiddenResponse | ServiceUnavailableResponse>

    /**
 * @summary Manually adjust client wallet balance (admin)
 */
export const useAdjustCrmWallet = <TError = ErrorType<BadRequestResponse | UnauthorizedResponse | ForbiddenResponse | ServiceUnavailableResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adjustCrmWallet>>, TError,{id: string;data: BodyType<WalletAdjustInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof adjustCrmWallet>>,
        TError,
        {id: string;data: BodyType<WalletAdjustInput>},
        TContext
      > => {
      return useMutation(getAdjustCrmWalletMutationOptions(options));
    }

