/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Api
 * Piccolo TPV API
 * OpenAPI spec version: 0.2.0
 */
export type CrmGiftCardEstado = typeof CrmGiftCardEstado[keyof typeof CrmGiftCardEstado];


export const CrmGiftCardEstado = {
  activa: 'activa',
  bloqueada: 'bloqueada',
  consumida: 'consumida',
  caducada: 'caducada',
} as const;

export interface CrmGiftCard {
  id: string;
  codigo: string;
  saldoInicial: string;
  saldoActual: string;
  clientId?: string | null;
  estado: CrmGiftCardEstado;
  fechaCaducidad?: string | null;
  notas: string;
  empleadoId?: string | null;
  empleadoNombre: string;
  beneficiarioEmail: string;
  beneficiarioNombre: string;
  mensajePersonalizado: string;
  tipoEntrega: string;
  createdAt: string;
  updatedAt: string;
}

export interface CreateCrmGiftCardInput {
  saldo: string;
  clientId?: string;
  fechaCaducidad?: string;
  notas?: string;
  beneficiarioEmail?: string;
  beneficiarioNombre?: string;
  mensajePersonalizado?: string;
  tipoEntrega?: string;
}

export interface PayWithCrmGiftCardInput {
  codigo: string;
  importe: string;
  orderId?: string;
}

export interface PayWithCrmGiftCardResult {
  card: CrmGiftCard;
  pagado: string;
  saldoRestante: string;
}

export type CrmGiftCardTransactionTipo = typeof CrmGiftCardTransactionTipo[keyof typeof CrmGiftCardTransactionTipo];


export const CrmGiftCardTransactionTipo = {
  emision: 'emision',
  recarga: 'recarga',
  pago: 'pago',
  bloqueo: 'bloqueo',
  desbloqueo: 'desbloqueo',
  caducidad: 'caducidad',
  devolucion: 'devolucion',
} as const;

export interface CrmGiftCardTransaction {
  id: string;
  giftCardId: string;
  orderId?: string | null;
  tipo: CrmGiftCardTransactionTipo;
  importe: string;
  saldoAnterior: string;
  saldoPosterior: string;
  empleadoId?: string | null;
  empleadoNombre: string;
  notas: string;
  createdAt: string;
}

export interface CrmGiftCardDetail {
  card: CrmGiftCard;
  transactions: CrmGiftCardTransaction[];
}

export interface RechargeCrmGiftCardInput {
  importe: string;
}

export interface CrmWallet {
  id: string;
  clientId: string;
  saldoReal: string;
  saldoPromo: string;
  saldoCompensacion: string;
  createdAt: string;
  updatedAt: string;
}

export type CrmWalletTransactionTipo = typeof CrmWalletTransactionTipo[keyof typeof CrmWalletTransactionTipo];


export const CrmWalletTransactionTipo = {
  recarga: 'recarga',
  pago: 'pago',
  devolucion: 'devolucion',
  compensacion: 'compensacion',
  promo: 'promo',
  ajuste: 'ajuste',
  caducidad: 'caducidad',
} as const;

export interface CrmWalletTransaction {
  id: string;
  clientId: string;
  tipo: CrmWalletTransactionTipo;
  subtipo: string;
  importe: string;
  saldoAnterior: string;
  saldoPosterior: string;
  descripcion: string;
  orderId?: string | null;
  empleadoId?: string | null;
  empleadoNombre: string;
  createdAt: string;
}

export interface CrmWalletDetail {
  wallet: CrmWallet;
  transactions: CrmWalletTransaction[];
}

export type WalletAddInputSubtipo = typeof WalletAddInputSubtipo[keyof typeof WalletAddInputSubtipo];


export const WalletAddInputSubtipo = {
  real: 'real',
  promo: 'promo',
  compensacion: 'compensacion',
} as const;

export interface WalletAddInput {
  importe: string;
  subtipo?: WalletAddInputSubtipo;
  descripcion?: string;
}

export type WalletPayInputSubtipo = typeof WalletPayInputSubtipo[keyof typeof WalletPayInputSubtipo];


export const WalletPayInputSubtipo = {
  real: 'real',
  promo: 'promo',
  compensacion: 'compensacion',
} as const;

export interface WalletPayInput {
  importe: string;
  orderId?: string;
  subtipo?: WalletPayInputSubtipo;
}

export interface WalletPayResult {
  wallet: CrmWallet;
  pagado: string;
}

export type WalletAdjustInputSubtipo = typeof WalletAdjustInputSubtipo[keyof typeof WalletAdjustInputSubtipo];


export const WalletAdjustInputSubtipo = {
  real: 'real',
  promo: 'promo',
  compensacion: 'compensacion',
} as const;

export interface WalletAdjustInput {
  importe: string;
  subtipo?: WalletAdjustInputSubtipo;
  descripcion?: string;
}

export interface ErrorResponse {
  error: string;
}

/**
 * Authentication is required or invalid
 */
export type UnauthorizedResponse = ErrorResponse;

/**
 * The authenticated user lacks the required role or permission
 */
export type ForbiddenResponse = ErrorResponse;

/**
 * Session or authorization verification is temporarily unavailable
 */
export type ServiceUnavailableResponse = ErrorResponse;

/**
 * Request validation failed
 */
export type BadRequestResponse = ErrorResponse;

/**
 * Requested resource was not found
 */
export type NotFoundResponse = ErrorResponse;

/**
 * Current resource state conflicts with the operation
 */
export type ConflictResponse = ErrorResponse;

export type GetCrmGiftCardsParams = {
/**
 * Filter by card code
 */
q?: string;
};

export type LookupCrmGiftCardParams = {
codigo: string;
};

