/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Api
 * Piccolo TPV API
 * OpenAPI spec version: 0.2.0
 */
/**
 * CRM customer master record (crm_clients)
 */
export interface CrmClient {
  id: string;
  nombre: string;
  apellidos: string;
  telefono: string;
  email: string;
  fechaNacimiento?: string | null;
  direccion: string;
  observaciones: string;
  activo: boolean;
  rgpdConsentimiento: boolean;
  rgpdFecha?: string | null;
  totalGasto: string;
  totalVisitas: number;
  ultimaVisita?: string | null;
  puntosSaldo: number;
  idioma: string;
  mesaFavoritaId?: string | null;
  zonaFavorita?: string | null;
  rgpdMarketing: boolean;
  notasInternas: string;
  flagNoPresentado: boolean;
  bloqueoOnline: boolean;
  cancelaciones: number;
  noPresentados: number;
  numCliente?: number | null;
  qrToken?: string | null;
  nivelId?: string | null;
  nivelNombre: string;
  saldoMonedero: string;
  createdAt: string;
  updatedAt: string;
}

export interface CreateCrmClientInput {
  nombre: string;
  apellidos?: string;
  telefono?: string;
  email?: string;
  fechaNacimiento?: string;
  direccion?: string;
  observaciones?: string;
  rgpdConsentimiento?: boolean;
}

export type CrmClientConflictErrorClienteExistente = {
  id: string;
  nombre: string;
};

export interface CrmClientConflictError {
  error: string;
  clienteExistente: CrmClientConflictErrorClienteExistente;
}

export interface UpdateCrmClientInput {
  nombre?: string;
  apellidos?: string;
  telefono?: string;
  email?: string;
  fechaNacimiento?: string | null;
  direccion?: string;
  observaciones?: string;
  activo?: boolean;
  rgpdConsentimiento?: boolean;
}

export type CrmClientHistoryReservationsItem = { [key: string]: unknown };

export interface CrmClientHistoryOrderSummary {
  id: string;
  createdAt: string;
  status: string;
}

export type CrmLoyaltyPointTipo = typeof CrmLoyaltyPointTipo[keyof typeof CrmLoyaltyPointTipo];


export const CrmLoyaltyPointTipo = {
  emision: 'emision',
  canje: 'canje',
  expiracion: 'expiracion',
  ajuste_positivo: 'ajuste_positivo',
  ajuste_negativo: 'ajuste_negativo',
} as const;

export interface CrmLoyaltyPoint {
  id: string;
  clientId: string;
  tipo: CrmLoyaltyPointTipo;
  puntos: number;
  saldoAnterior: number;
  saldoPosterior: number;
  descripcion: string;
  orderId?: string | null;
  campaniaId?: string | null;
  empleadoId?: string | null;
  empleadoNombre: string;
  expiraEn?: string | null;
  createdAt: string;
}

export type CrmGiftCardEstado = typeof CrmGiftCardEstado[keyof typeof CrmGiftCardEstado];


export const CrmGiftCardEstado = {
  activa: 'activa',
  bloqueada: 'bloqueada',
  consumida: 'consumida',
  caducada: 'caducada',
} as const;

export interface CrmGiftCard {
  id: string;
  codigo: string;
  saldoInicial: string;
  saldoActual: string;
  clientId?: string | null;
  estado: CrmGiftCardEstado;
  fechaCaducidad?: string | null;
  notas: string;
  empleadoId?: string | null;
  empleadoNombre: string;
  beneficiarioEmail: string;
  beneficiarioNombre: string;
  mensajePersonalizado: string;
  tipoEntrega: string;
  createdAt: string;
  updatedAt: string;
}

export interface CrmClientHistoryStats {
  totalGasto: number;
  totalVisitas: number;
  ticketMedio: number;
  puntosSaldo: number;
  ultimaVisita?: string | null;
}

export interface CrmClientHistory {
  client: CrmClient;
  orders: CrmClientHistoryOrderSummary[];
  reservations: CrmClientHistoryReservationsItem[];
  points: CrmLoyaltyPoint[];
  giftCards: CrmGiftCard[];
  stats: CrmClientHistoryStats;
}

export type CrmLoyaltyConfigBonificacionesCategorias = {[key: string]: number};

export type CrmLoyaltyConfigReglasPorProducto = { [key: string]: unknown };

/**
 * Singleton loyalty configuration (crm_loyalty_config)
 */
export interface CrmLoyaltyConfig {
  id: string;
  activo: boolean;
  puntosPorEuro: string;
  valorPunto: string;
  caducidadDias: number;
  canjeMinimo: number;
  bonificacionesCategorias: CrmLoyaltyConfigBonificacionesCategorias;
  puntosExtraCumpleanos: number;
  puntosExtraPrimeraCompra: number;
  puntosExtraReserva: number;
  puntosExtraRecogida: number;
  puntosExtraOnline: number;
  reglasPorProducto: CrmLoyaltyConfigReglasPorProducto;
  canjeMaxPorOperacion: number;
  caducidadAvisoDias: number;
  nivelesActivos: boolean;
  monederoActivo: boolean;
  createdAt: string;
  updatedAt: string;
}

export type UpdateCrmLoyaltyConfigInputBonificacionesCategorias = {[key: string]: number};

export type UpdateCrmLoyaltyConfigInputReglasPorProducto = { [key: string]: unknown };

export interface UpdateCrmLoyaltyConfigInput {
  activo?: boolean;
  puntosPorEuro?: string;
  valorPunto?: string;
  caducidadDias?: number;
  canjeMinimo?: number;
  bonificacionesCategorias?: UpdateCrmLoyaltyConfigInputBonificacionesCategorias;
  puntosExtraCumpleanos?: number;
  puntosExtraPrimeraCompra?: number;
  puntosExtraReserva?: number;
  puntosExtraRecogida?: number;
  puntosExtraOnline?: number;
  reglasPorProducto?: UpdateCrmLoyaltyConfigInputReglasPorProducto;
  canjeMaxPorOperacion?: number;
  caducidadAvisoDias?: number;
  nivelesActivos?: boolean;
  monederoActivo?: boolean;
}

export interface IssueCrmPointsInput {
  puntos: number;
  descripcion?: string;
}

export interface RedeemCrmPointsInput {
  puntos: number;
  orderId?: string;
}

export interface RedeemCrmPointsResult {
  valorEuros: number;
  saldoPosterior: number;
}

export interface CreateCrmGiftCardInput {
  saldo: string;
  clientId?: string;
  fechaCaducidad?: string;
  notas?: string;
  beneficiarioEmail?: string;
  beneficiarioNombre?: string;
  mensajePersonalizado?: string;
  tipoEntrega?: string;
}

export interface PayWithCrmGiftCardInput {
  codigo: string;
  importe: string;
  orderId?: string;
}

export interface PayWithCrmGiftCardResult {
  card: CrmGiftCard;
  pagado: string;
  saldoRestante: string;
}

export type CrmGiftCardTransactionTipo = typeof CrmGiftCardTransactionTipo[keyof typeof CrmGiftCardTransactionTipo];


export const CrmGiftCardTransactionTipo = {
  emision: 'emision',
  recarga: 'recarga',
  pago: 'pago',
  bloqueo: 'bloqueo',
  desbloqueo: 'desbloqueo',
  caducidad: 'caducidad',
  devolucion: 'devolucion',
} as const;

export interface CrmGiftCardTransaction {
  id: string;
  giftCardId: string;
  orderId?: string | null;
  tipo: CrmGiftCardTransactionTipo;
  importe: string;
  saldoAnterior: string;
  saldoPosterior: string;
  empleadoId?: string | null;
  empleadoNombre: string;
  notas: string;
  createdAt: string;
}

export interface CrmGiftCardDetail {
  card: CrmGiftCard;
  transactions: CrmGiftCardTransaction[];
}

export interface RechargeCrmGiftCardInput {
  importe: string;
}

export type CrmPromotionTipo = typeof CrmPromotionTipo[keyof typeof CrmPromotionTipo];


export const CrmPromotionTipo = {
  descuento_fijo: 'descuento_fijo',
  descuento_porcentual: 'descuento_porcentual',
  '2x1': '2x1',
  '3x2': '3x2',
  menu_promocional: 'menu_promocional',
  envio_gratis: 'envio_gratis',
  producto_gratis: 'producto_gratis',
} as const;

export interface CrmPromotion {
  id: string;
  nombre: string;
  descripcion: string;
  tipo: CrmPromotionTipo;
  valor: string;
  codigo: string;
  activo: boolean;
  fechaInicio?: string | null;
  fechaFin?: string | null;
  diasSemana: number[];
  horaInicio: string;
  horaFin: string;
  categoriaIds: string[];
  productIds: string[];
  montoMinimo: string;
  usoMaximo: number;
  usoActual: number;
  usoMaximoPorCliente: number;
  canal: string;
  compatible: boolean;
  codigoUnico: boolean;
  productoGratisId?: string | null;
  createdAt: string;
  updatedAt: string;
}

export interface CreateCrmPromotionInput {
  nombre: string;
  tipo: string;
  valor?: string;
  descripcion?: string;
  codigo?: string;
  activo?: boolean;
  fechaInicio?: string;
  fechaFin?: string;
  diasSemana?: number[];
  horaInicio?: string;
  horaFin?: string;
  categoriaIds?: string[];
  productIds?: string[];
  montoMinimo?: string;
  usoMaximo?: number;
  usoMaximoPorCliente?: number;
  canal?: string;
  compatible?: boolean;
  codigoUnico?: boolean;
  productoGratisId?: string;
}

export interface ValidateCrmPromotionInput {
  promoId?: string;
  codigo?: string;
  orderAmount: number;
}

/**
 * Always returned with HTTP 200; check valid before applying discount
 */
export interface ValidateCrmPromotionResult {
  valid: boolean;
  reason?: string;
  descuento: number;
  promo: CrmPromotion;
}

export interface UseCrmPromotionInput {
  promotionId: string;
  clientId?: string;
  orderId?: string;
}

export interface CrmCouponUse {
  id: string;
  promotionId: string;
  clientId?: string | null;
  orderId?: string | null;
  usedAt: string;
}

export interface UpdateCrmPromotionInput {
  nombre?: string;
  descripcion?: string;
  tipo?: string;
  valor?: string;
  codigo?: string;
  activo?: boolean;
  fechaInicio?: string | null;
  fechaFin?: string | null;
  diasSemana?: number[];
  horaInicio?: string;
  horaFin?: string;
  categoriaIds?: string[];
  productIds?: string[];
  montoMinimo?: string;
  usoMaximo?: number;
}

export interface CrmReportsClientStats {
  total: number;
  activos: number;
  nuevos30d: number;
  inactivos90d: number;
  gastoTotal: number;
}

export interface CrmReportsTopClient {
  id: string;
  nombre: string;
  apellidos: string;
  totalGasto: string;
  totalVisitas: number;
  puntosSaldo: number;
}

export interface CrmReportsPointsStats {
  totalEmitidos: number;
  totalCanjeados: number;
}

export interface CrmReportsGiftCardStats {
  totalActivas: number;
  totalConsumidas: number;
  saldoTotal?: string | null;
}

export interface CrmReportsPromotionStats {
  totalPromociones: number;
  activas: number;
  totalUsos?: string | null;
}

export interface CrmReports {
  clientes: CrmReportsClientStats;
  topClientes: CrmReportsTopClient[];
  puntos: CrmReportsPointsStats;
  tarjetasRegalo: CrmReportsGiftCardStats;
  promociones: CrmReportsPromotionStats;
}

export type CrmAuditLogDatos = { [key: string]: unknown } | null;

export interface CrmAuditLog {
  id: string;
  accion: string;
  clientId?: string | null;
  entidadTipo: string;
  entidadId?: string | null;
  empleadoId?: string | null;
  empleadoNombre: string;
  terminal: string;
  datos?: CrmAuditLogDatos;
  createdAt: string;
}

export interface CrmLoyaltyLevel {
  id: string;
  nombre: string;
  descripcion: string;
  orden: number;
  requisitosGasto: string;
  requisitosVisitas: number;
  multiplicadorPuntos: string;
  descuentoPct: string;
  beneficios: string[];
  color: string;
  icono: string;
  activo: boolean;
  createdAt: string;
  updatedAt: string;
}

export interface CreateCrmLoyaltyLevelInput {
  nombre: string;
  descripcion?: string;
  orden?: number;
  requisitosGasto?: string;
  requisitosVisitas?: number;
  multiplicadorPuntos?: string;
  descuentoPct?: string;
  beneficios?: string[];
  color?: string;
  icono?: string;
}

export interface UpdateCrmLoyaltyLevelInput {
  nombre?: string;
  descripcion?: string;
  orden?: number;
  requisitosGasto?: string;
  requisitosVisitas?: number;
  multiplicadorPuntos?: string;
  descuentoPct?: string;
  beneficios?: string[];
  color?: string;
  icono?: string;
  activo?: boolean;
}

export interface CrmReviewLevelsResult {
  updated: number;
}

export interface CrmWallet {
  id: string;
  clientId: string;
  saldoReal: string;
  saldoPromo: string;
  saldoCompensacion: string;
  createdAt: string;
  updatedAt: string;
}

export type CrmWalletTransactionTipo = typeof CrmWalletTransactionTipo[keyof typeof CrmWalletTransactionTipo];


export const CrmWalletTransactionTipo = {
  recarga: 'recarga',
  pago: 'pago',
  devolucion: 'devolucion',
  compensacion: 'compensacion',
  promo: 'promo',
  ajuste: 'ajuste',
  caducidad: 'caducidad',
} as const;

export interface CrmWalletTransaction {
  id: string;
  clientId: string;
  tipo: CrmWalletTransactionTipo;
  subtipo: string;
  importe: string;
  saldoAnterior: string;
  saldoPosterior: string;
  descripcion: string;
  orderId?: string | null;
  empleadoId?: string | null;
  empleadoNombre: string;
  createdAt: string;
}

export interface CrmWalletDetail {
  wallet: CrmWallet;
  transactions: CrmWalletTransaction[];
}

export type WalletAddInputSubtipo = typeof WalletAddInputSubtipo[keyof typeof WalletAddInputSubtipo];


export const WalletAddInputSubtipo = {
  real: 'real',
  promo: 'promo',
  compensacion: 'compensacion',
} as const;

export interface WalletAddInput {
  importe: string;
  subtipo?: WalletAddInputSubtipo;
  descripcion?: string;
}

export type WalletPayInputSubtipo = typeof WalletPayInputSubtipo[keyof typeof WalletPayInputSubtipo];


export const WalletPayInputSubtipo = {
  real: 'real',
  promo: 'promo',
  compensacion: 'compensacion',
} as const;

export interface WalletPayInput {
  importe: string;
  orderId?: string;
  subtipo?: WalletPayInputSubtipo;
}

export interface WalletPayResult {
  wallet: CrmWallet;
  pagado: string;
}

export type WalletAdjustInputSubtipo = typeof WalletAdjustInputSubtipo[keyof typeof WalletAdjustInputSubtipo];


export const WalletAdjustInputSubtipo = {
  real: 'real',
  promo: 'promo',
  compensacion: 'compensacion',
} as const;

export interface WalletAdjustInput {
  importe: string;
  subtipo?: WalletAdjustInputSubtipo;
  descripcion?: string;
}

export type CrmConsentTipo = typeof CrmConsentTipo[keyof typeof CrmConsentTipo];


export const CrmConsentTipo = {
  operativo: 'operativo',
  marketing_email: 'marketing_email',
  marketing_sms: 'marketing_sms',
  marketing_whatsapp: 'marketing_whatsapp',
  perfilado: 'perfilado',
  fidelizacion: 'fidelizacion',
} as const;

export interface CrmConsent {
  id: string;
  clientId: string;
  tipo: CrmConsentTipo;
  valor: boolean;
  canalOrigen: string;
  textoAceptado: string;
  versionLegal: string;
  ip: string;
  revocadoEn?: string | null;
  createdAt: string;
}

export interface CreateCrmConsentInput {
  tipo: string;
  valor: boolean;
  canalOrigen?: string;
  textoAceptado?: string;
  versionLegal?: string;
}

export interface CrmExpiringPointsResponse {
  rows: CrmLoyaltyPoint[];
  totalExpiring: number;
  days: number;
}

export interface CrmExpirePointsResult {
  clientesAfectados: number;
  puntosExpirados: number;
}

export type CrmCampaignTipo = typeof CrmCampaignTipo[keyof typeof CrmCampaignTipo];


export const CrmCampaignTipo = {
  manual: 'manual',
  automatica: 'automatica',
  cumpleanos: 'cumpleanos',
  inactividad: 'inactividad',
  puntos_caducidad: 'puntos_caducidad',
} as const;

export type CrmCampaignEstado = typeof CrmCampaignEstado[keyof typeof CrmCampaignEstado];


export const CrmCampaignEstado = {
  borrador: 'borrador',
  programada: 'programada',
  enviando: 'enviando',
  completada: 'completada',
  pausada: 'pausada',
} as const;

export type CrmCampaignCanal = typeof CrmCampaignCanal[keyof typeof CrmCampaignCanal];


export const CrmCampaignCanal = {
  email: 'email',
  sms: 'sms',
  whatsapp: 'whatsapp',
  web: 'web',
  ticket: 'ticket',
  cupon_cuenta: 'cupon_cuenta',
} as const;

export type CrmCampaignSegmento = { [key: string]: unknown };

export interface CrmCampaign {
  id: string;
  nombre: string;
  descripcion: string;
  tipo: CrmCampaignTipo;
  estado: CrmCampaignEstado;
  canal: CrmCampaignCanal;
  asunto: string;
  contenido: string;
  segmento: CrmCampaignSegmento;
  fechaEnvio?: string | null;
  fechaFin?: string | null;
  totalDestinatarios: number;
  totalEnviados: number;
  totalEntregados: number;
  totalFallidos: number;
  totalUsados: number;
  promotionId?: string | null;
  empleadoId?: string | null;
  empleadoNombre: string;
  createdAt: string;
  updatedAt: string;
}

export type CreateCrmCampaignInputSegmento = { [key: string]: unknown };

export interface CreateCrmCampaignInput {
  nombre: string;
  descripcion?: string;
  tipo?: string;
  canal?: string;
  asunto?: string;
  contenido?: string;
  segmento?: CreateCrmCampaignInputSegmento;
  fechaEnvio?: string;
  promotionId?: string;
}

export type UpdateCrmCampaignInputSegmento = { [key: string]: unknown };

export interface UpdateCrmCampaignInput {
  nombre?: string;
  descripcion?: string;
  tipo?: string;
  estado?: string;
  canal?: string;
  asunto?: string;
  contenido?: string;
  segmento?: UpdateCrmCampaignInputSegmento;
  fechaEnvio?: string | null;
  fechaFin?: string | null;
  promotionId?: string | null;
}

export type CrmCampaignSendEstado = typeof CrmCampaignSendEstado[keyof typeof CrmCampaignSendEstado];


export const CrmCampaignSendEstado = {
  pendiente: 'pendiente',
  enviado: 'enviado',
  entregado: 'entregado',
  fallido: 'fallido',
  usado: 'usado',
  baja: 'baja',
} as const;

export interface CrmCampaignSend {
  id: string;
  campaignId: string;
  clientId: string;
  estado: CrmCampaignSendEstado;
  canal: string;
  enviadoEn?: string | null;
  fallidoEn?: string | null;
  error?: string | null;
  usadoEn?: string | null;
  createdAt: string;
}

export interface CrmCampaignSendResult {
  destinatarios: number;
  enviados: number;
}

export interface CrmSegmentClientSummary {
  id: string;
  nombre: string;
  email: string;
  telefono: string;
  totalGasto: string;
  totalVisitas: number;
  ultimaVisita?: string | null;
  puntosSaldo: number;
}

export interface CrmSegmentPreviewResult {
  total: number;
  muestra: CrmSegmentClientSummary[];
}

export interface CrmDemoDataItem {
  tabla: string;
  rowId: string;
}

export interface CrmDemoDataResult {
  created: number;
  items: CrmDemoDataItem[];
}

export interface CrmDemoDataDeleteResult {
  deleted: number;
}

export interface CrmExtendedReportsLevelStats {
  totalNiveles: number;
}

export interface CrmExtendedReportsLevelDistribution {
  nivelNombre: string;
  count: number;
}

export type CrmExtendedReportsNiveles = {
  stats: CrmExtendedReportsLevelStats;
  distribucion: CrmExtendedReportsLevelDistribution[];
};

export interface CrmExtendedReportsWalletStats {
  clientesConMonedero: number;
  totalSaldoReal?: string | null;
  totalSaldoPromo?: string | null;
}

export interface CrmExtendedReportsCampaignStats {
  total: number;
  enviadas: number;
}

export interface CrmExtendedReportsPoints30d {
  emitidos: number;
  canjeados: number;
  expirados: number;
}

export interface CrmExtendedReports {
  niveles: CrmExtendedReportsNiveles;
  monedero: CrmExtendedReportsWalletStats;
  campañas: CrmExtendedReportsCampaignStats;
  puntosProximosACaducar30d: number;
  puntos30d: CrmExtendedReportsPoints30d;
}

export interface ErrorResponse {
  error: string;
}

/**
 * Authentication is required or invalid
 */
export type UnauthorizedResponse = ErrorResponse;

/**
 * The authenticated user lacks the required role or permission
 */
export type ForbiddenResponse = ErrorResponse;

/**
 * Session or authorization verification is temporarily unavailable
 */
export type ServiceUnavailableResponse = ErrorResponse;

/**
 * Request validation failed
 */
export type BadRequestResponse = ErrorResponse;

/**
 * Requested resource was not found
 */
export type NotFoundResponse = ErrorResponse;

/**
 * Current resource state conflicts with the operation
 */
export type ConflictResponse = ErrorResponse;

export type GetCrmClientsParams = {
/**
 * Search by name, surname, phone or email
 */
q?: string;
/**
 * @maximum 200
 */
limit?: number;
};

export type GetCrmGiftCardsParams = {
/**
 * Filter by card code
 */
q?: string;
};

export type LookupCrmGiftCardParams = {
codigo: string;
};

export type GetCrmAuditParams = {
/**
 * @maximum 500
 */
limit?: number;
clientId?: string;
};

export type GetCrmExpiringPointsParams = {
days?: number;
};

/**
 * Segment criteria (gastoMinimo, inactivoDias, nivelId, etc.)
 */
export type PreviewCrmSegmentBody = { [key: string]: unknown };

export type ExportCrmSegmentParams = {
nivelId?: string;
inactivoDias?: number;
puntosMinimos?: number;
gastoMinimo?: string;
visitasMinimas?: number;
cumpleanosEsteMes?: boolean;
};

